package com.brainserve.clientonboarding.payments.infrastructure.persistence;

import static com.brainserve.clientonboarding.payments.domain.model.PaymentModels.*;
import static com.brainserve.clientonboarding.common.infrastructure.persistence.JdbcValues.timestamp;
import com.brainserve.clientonboarding.billing.application.BillingErrors;
import com.brainserve.clientonboarding.common.domain.model.PageSlice;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
public class PaymentRepository {
    private final JdbcClient jdbc;
    public PaymentRepository(JdbcClient jdbc){this.jdbc=jdbc;}
    public Optional<Session> session(UUID org,UUID id){return jdbc.sql("SELECT * FROM payments WHERE organization_id=? AND id=?").params(org,id).query(this::session).optional();}
    public Optional<Session> order(UUID org,String id){return jdbc.sql("SELECT * FROM payments WHERE organization_id=? AND provider_order_id=?").params(org,id).query(this::session).optional();}
    public Optional<Session> open(UUID org,UUID invoice){return jdbc.sql("SELECT * FROM payments WHERE organization_id=? AND invoice_id=? AND status IN ('CREATING','READY','UNKNOWN')").params(org,invoice).query(this::session).optional();}
    public Optional<Session> sessionKey(UUID org,String key,String hash){var r=jdbc.sql("SELECT * FROM payments WHERE organization_id=? AND idempotency_key=?").params(org,key).query(this::session).optional();r.ifPresent(s->same(s.requestHash(),hash));return r;}
    public void insert(Session s,UUID actor){jdbc.sql("INSERT INTO payments(id,organization_id,invoice_id,provider,amount_minor,currency,status,idempotency_key,request_hash,created_at,created_by,updated_at,updated_by) VALUES(?,?,?,'RAZORPAY',?,?,'CREATING',?,?,?,?,?,?)").params(s.id(),s.organizationId(),s.invoiceId(),s.amountMinor(),s.currency(),s.idempotencyKey(),s.requestHash(),timestamp(s.createdAt()),actor,timestamp(s.createdAt()),actor).update();}
    public void sessionState(Session s,String order,SessionStatus state,UUID actor,Instant now){if(jdbc.sql("UPDATE payments SET provider_order_id=?,status=?,updated_at=?,updated_by=?,version=version+1 WHERE organization_id=? AND id=? AND version=?").params(order,state.name(),timestamp(now),actor,s.organizationId(),s.id(),s.version()).update()!=1)throw BillingErrors.conflict();}
    public Optional<Transaction> transaction(UUID org,UUID id){return jdbc.sql("SELECT * FROM payment_transactions WHERE organization_id=? AND id=?").params(org,id).query(this::transaction).optional();}
    public Optional<Transaction> providerTransaction(UUID org,String id){return jdbc.sql("SELECT * FROM payment_transactions WHERE organization_id=? AND provider_payment_id=?").params(org,id).query(this::transaction).optional();}
    public Optional<Transaction> manualKey(UUID org,String key,String hash){var r=jdbc.sql("SELECT * FROM payment_transactions WHERE organization_id=? AND idempotency_key=?").params(org,key).query(this::transaction).optional();if(r.isPresent())same(jdbc.sql("SELECT request_hash FROM payment_transactions WHERE organization_id=? AND id=?").params(org,r.get().id()).query(String.class).single(),hash);return r;}
    public void insert(Transaction t,String key,String hash,UUID actor){jdbc.sql("INSERT INTO payment_transactions(id,organization_id,invoice_id,payment_id,provider,provider_payment_id,status,amount_minor,refunded_minor,currency,reference,reason,idempotency_key,request_hash,created_at,created_by,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").params(t.id(),t.organizationId(),t.invoiceId(),t.paymentId(),t.provider(),t.providerPaymentId(),t.status().name(),t.amountMinor(),t.refundedMinor(),t.currency(),t.reference(),t.reason(),key,hash,timestamp(t.createdAt()),actor,timestamp(t.createdAt()),actor).update();}
    public void transactionState(Transaction t,TransactionStatus state,long refunded,UUID actor,Instant now){if(jdbc.sql("UPDATE payment_transactions SET status=?,refunded_minor=?,updated_at=?,updated_by=?,version=version+1 WHERE organization_id=? AND id=? AND version=?").params(state.name(),refunded,timestamp(now),actor,t.organizationId(),t.id(),t.version()).update()!=1)throw BillingErrors.conflict();}
    public Balances balances(UUID org,UUID invoice){var values=jdbc.sql("SELECT coalesce(sum(amount_minor),0) captured,coalesce(sum(refunded_minor),0) refunded FROM payment_transactions WHERE organization_id=? AND invoice_id=? AND status IN ('CAPTURED','REFUNDED','PARTIALLY_REFUNDED')").params(org,invoice).query((r,n)->new long[]{r.getLong("captured"),r.getLong("refunded")}).single();long reserved=jdbc.sql("SELECT coalesce(sum(amount_minor),0) FROM payments WHERE organization_id=? AND invoice_id=? AND status IN ('CREATING','READY','UNKNOWN')").params(org,invoice).query(Long.class).single();return new Balances(values[0],values[1],reserved);}
    public PageSlice<Transaction> transactions(UUID org,UUID invoice,int page,int size){return new PageSlice<>(jdbc.sql("SELECT * FROM payment_transactions WHERE organization_id=? AND invoice_id=? ORDER BY created_at DESC,id LIMIT ? OFFSET ?").params(org,invoice,size,(long)page*size).query(this::transaction).list(),page,size,jdbc.sql("SELECT count(*) FROM payment_transactions WHERE organization_id=? AND invoice_id=?").params(org,invoice).query(Long.class).single());}
    public PageSlice<Refund> refunds(UUID org,UUID transaction,int page,int size){return new PageSlice<>(jdbc.sql("SELECT * FROM refunds WHERE organization_id=? AND transaction_id=? ORDER BY created_at DESC,id LIMIT ? OFFSET ?").params(org,transaction,size,(long)page*size).query(this::refund).list(),page,size,jdbc.sql("SELECT count(*) FROM refunds WHERE organization_id=? AND transaction_id=?").params(org,transaction).query(Long.class).single());}
    public Optional<Refund> refund(UUID org,UUID id){return jdbc.sql("SELECT * FROM refunds WHERE organization_id=? AND id=?").params(org,id).query(this::refund).optional();}
    public Optional<Refund> providerRefund(UUID org,String id){return jdbc.sql("SELECT * FROM refunds WHERE organization_id=? AND provider_refund_id=?").params(org,id).query(this::refund).optional();}
    public Optional<Refund> refundKey(UUID org,String key,String hash){var r=jdbc.sql("SELECT * FROM refunds WHERE organization_id=? AND idempotency_key=?").params(org,key).query(this::refund).optional();r.ifPresent(s->same(s.requestHash(),hash));return r;}
    public long committedRefunds(UUID org,UUID transaction){return jdbc.sql("SELECT coalesce(sum(amount_minor),0) FROM refunds WHERE organization_id=? AND transaction_id=? AND status<>'FAILED'").params(org,transaction).query(Long.class).single();}
    public long processedRefunds(UUID org,UUID transaction){return jdbc.sql("SELECT coalesce(sum(amount_minor),0) FROM refunds WHERE organization_id=? AND transaction_id=? AND status='PROCESSED'").params(org,transaction).query(Long.class).single();}
    public long pendingRefunds(UUID org,UUID transaction){return jdbc.sql("SELECT coalesce(sum(amount_minor),0) FROM refunds WHERE organization_id=? AND transaction_id=? AND status IN ('CREATING','PENDING','UNKNOWN')").params(org,transaction).query(Long.class).single();}
    public void insert(Refund r,UUID actor){jdbc.sql("INSERT INTO refunds(id,organization_id,transaction_id,provider_refund_id,amount_minor,status,reason,idempotency_key,request_hash,created_at,created_by,updated_at,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").params(r.id(),r.organizationId(),r.transactionId(),r.providerRefundId(),r.amountMinor(),r.status().name(),r.reason(),r.idempotencyKey(),r.requestHash(),timestamp(r.createdAt()),actor,timestamp(r.createdAt()),actor).update();}
    public void refundState(Refund r,String providerId,RefundStatus state,UUID actor,Instant now){if(jdbc.sql("UPDATE refunds SET provider_refund_id=?,status=?,updated_at=?,updated_by=?,version=version+1 WHERE organization_id=? AND id=? AND version=?").params(providerId,state.name(),timestamp(now),actor,r.organizationId(),r.id(),r.version()).update()!=1)throw BillingErrors.conflict();}
    public boolean eventExists(UUID org,String event,String hash){var r=jdbc.sql("SELECT payload_hash FROM payment_webhook_events WHERE organization_id=? AND provider='RAZORPAY' AND provider_event_id=?").params(org,event).query(String.class).optional();r.ifPresent(v->same(v,hash));return r.isPresent();}
    public void event(UUID org,String id,String type,String hash,boolean processed,Instant now){jdbc.sql("INSERT INTO payment_webhook_events(id,organization_id,provider,provider_event_id,event_type,payload_hash,processing_status,received_at,processed_at) VALUES(?,?,'RAZORPAY',?,?,?,?,?,?)").params(UUID.randomUUID(),org,id,type,hash,processed?"PROCESSED":"IGNORED",timestamp(now),timestamp(now)).update();}
    private void same(String actual,String expected){if(!actual.equals(expected))throw BillingErrors.state("The idempotency key or event ID was reused with different content.");}
    private Session session(ResultSet r,int n)throws SQLException{return new Session(r.getObject("id",UUID.class),r.getObject("organization_id",UUID.class),r.getObject("invoice_id",UUID.class),r.getString("provider_order_id"),r.getLong("amount_minor"),r.getString("currency"),SessionStatus.valueOf(r.getString("status")),r.getString("idempotency_key"),r.getString("request_hash"),r.getTimestamp("created_at").toInstant(),r.getLong("version"));}
    private Transaction transaction(ResultSet r,int n)throws SQLException{return new Transaction(r.getObject("id",UUID.class),r.getObject("organization_id",UUID.class),r.getObject("invoice_id",UUID.class),r.getObject("payment_id",UUID.class),r.getString("provider"),r.getString("provider_payment_id"),TransactionStatus.valueOf(r.getString("status")),r.getLong("amount_minor"),r.getLong("refunded_minor"),r.getString("currency"),r.getString("reference"),r.getString("reason"),r.getTimestamp("created_at").toInstant(),r.getLong("version"));}
    private Refund refund(ResultSet r,int n)throws SQLException{return new Refund(r.getObject("id",UUID.class),r.getObject("organization_id",UUID.class),r.getObject("transaction_id",UUID.class),r.getString("provider_refund_id"),r.getLong("amount_minor"),RefundStatus.valueOf(r.getString("status")),r.getString("reason"),r.getString("idempotency_key"),r.getString("request_hash"),r.getTimestamp("created_at").toInstant(),r.getLong("version"));}
}
