package com.brainserve.onboarding.contracts.infrastructure.config;
import com.brainserve.onboarding.contracts.infrastructure.storage.*;import java.net.URI;import java.time.Clock;import org.springframework.beans.factory.annotation.Qualifier;import org.springframework.boot.autoconfigure.condition.*;import org.springframework.context.annotation.*;import software.amazon.awssdk.auth.credentials.*;import software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient;import software.amazon.awssdk.regions.Region;import software.amazon.awssdk.services.s3.*;import software.amazon.awssdk.services.s3.presigner.S3Presigner;
@Configuration
public class ContractStorageConfiguration{
 @Bean(name="contractS3Client",destroyMethod="close")@ConditionalOnProperty(prefix="app.contracts.storage",name="enabled",havingValue="true") S3Client contractS3Client(ContractStorageProperties p){var creds=StaticCredentialsProvider.create(AwsBasicCredentials.create(p.accessKey(),p.secretKey()));return S3Client.builder().endpointOverride(URI.create(p.endpoint())).region(Region.of(p.region())).credentialsProvider(creds).serviceConfiguration(S3Configuration.builder().pathStyleAccessEnabled(p.pathStyleAccess()).build()).httpClientBuilder(UrlConnectionHttpClient.builder()).build();}
 @Bean(name="contractS3Presigner",destroyMethod="close")@ConditionalOnProperty(prefix="app.contracts.storage",name="enabled",havingValue="true") S3Presigner contractS3Presigner(ContractStorageProperties p){var creds=StaticCredentialsProvider.create(AwsBasicCredentials.create(p.accessKey(),p.secretKey()));return S3Presigner.builder().endpointOverride(URI.create(p.endpoint())).region(Region.of(p.region())).credentialsProvider(creds).serviceConfiguration(S3Configuration.builder().pathStyleAccessEnabled(p.pathStyleAccess()).build()).build();}
 @Bean@ConditionalOnProperty(prefix="app.contracts.storage",name="enabled",havingValue="true") ContractDocumentStorage contractDocumentStorage(ContractStorageProperties p,@Qualifier("contractS3Client")S3Client c,@Qualifier("contractS3Presigner")S3Presigner s,Clock clock){return new S3ContractDocumentStorage(p,c,s,clock);}
 @Bean@ConditionalOnMissingBean(ContractDocumentStorage.class) ContractDocumentStorage disabledContractDocumentStorage(){return new DisabledContractDocumentStorage();}
}
