"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { ArrowUpRight,ChartNoAxesCombined,Clock3,FileSignature,Loader2,RefreshCw,TriangleAlert,WalletCards } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { EmptyState } from "@/components/shared/empty-state";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ApiClientError } from "@/services/api-client";
import type { FunnelMetric,OnboardingReportRow,ReportingSnapshot } from "@/types/reporting";

export default function ReportsPage(){
 const{authorizedRequest,hasPermission}=useAuth();const allowed=hasPermission("REPORT_READ");const[data,setData]=useState<ReportingSnapshot|null>(null);const[rows,setRows]=useState<OnboardingReportRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[snapshot,onboardings]=await Promise.all([authorizedRequest<ReportingSnapshot>("/reports/snapshot"),authorizedRequest<OnboardingReportRow[]>("/reports/onboardings?size=12")]);setData(snapshot);setRows(onboardings)}catch(e){setError(msg(e,"Reporting data could not be loaded."))}finally{setLoading(false)}},[authorizedRequest]);
 useEffect(()=>{if(allowed)void load()},[allowed,load]);
 if(!allowed)return <PermissionState/>;if(loading)return <Loading/>;
 if(error&&!data)return <div className="space-y-5"><PageHeading eyebrow="Reports" title="Operational visibility" description="Tenant-scoped reporting is unavailable right now."/><FormMessage>{error}</FormMessage><Button variant="secondary" onClick={()=>void load()}><RefreshCw className="size-4"/>Retry</Button></div>;
 if(!data)return null;const o=data.operational;
 return <><PageHeading eyebrow="Reports & analytics" title="See where onboarding is moving — and where it is stuck." description="Operational, funnel, financial, contract and duration metrics are calculated from tenant-scoped source-of-truth records. No reporting cache can bypass business state." actions={<Button variant="secondary" size="icon" aria-label="Refresh reports" onClick={()=>void load()}><RefreshCw className="size-4"/></Button>}/>
 {error&&<div className="mb-5"><FormMessage>{error}</FormMessage></div>}
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active onboarding" value={o.activeOnboardings} helper={`${o.completionRatePercent}% completion rate`} icon={ChartNoAxesCombined}/><Metric label="Client action" value={o.awaitingClientAction} helper="Projects waiting on clients" icon={Clock3}/><Metric label="Internal review" value={o.awaitingInternalReview} helper={`${o.readyForApproval} ready for approval`} icon={FileSignature}/><Metric label="Overdue steps" value={o.overdueSteps} helper="Incomplete past due requirements" icon={TriangleAlert}/></div>
 <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="panel overflow-hidden"><SectionTitle title="Onboarding funnel" body="Completion by snapshotted workflow requirement type."/><div className="space-y-4 p-5">{data.funnel.length?data.funnel.slice(0,10).map(m=><Funnel key={m.stepType} metric={m}/>):<EmptyState title="No funnel data yet" description="Step analytics appear after onboarding instances are created."/>}</div></section><section className="space-y-6"><div className="panel p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">Financial</p><p className="mt-2 text-3xl font-semibold tracking-[-.04em]">{financialHeadline(data.financial.currencies)}</p><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">Collected · {data.financial.invoicesPaid}/{data.financial.invoicesSent} paid invoices</p><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Overdue" value={data.financial.invoicesOverdue}/><Mini label="Avg payment" value={hours(data.financial.averagePaymentHours)}/></div>{data.financial.currencies.length>0&&<div className="mt-4 space-y-2 border-t pt-4">{data.financial.currencies.map(c=><div key={c.currency} className="flex items-center justify-between gap-3 text-xs"><span className="font-semibold">{c.currency}</span><span className="text-[hsl(var(--muted-foreground))]">{formatMoney(c.collectedMinor,c.currency)} collected · {formatMoney(c.refundedMinor,c.currency)} refunded</span></div>)}</div>}</div><div className="panel p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">Contracts</p><p className="mt-2 text-3xl font-semibold tracking-[-.04em]">{data.contracts.completionRatePercent}%</p><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{data.contracts.contractsSigned}/{data.contracts.contractsSent} sent contracts signed</p><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Declined" value={data.contracts.contractsDeclined}/><Mini label="Avg signature" value={hours(data.contracts.averageSignatureHours)}/></div></div></section></div>
 <section className="panel mt-6 overflow-hidden"><SectionTitle title="Current onboarding portfolio" body="Progress, lifecycle and overdue work across the organization."/>{rows.length===0?<EmptyState title="No onboarding records" description="Portfolio reporting appears after onboarding begins."/>:<div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="border-b bg-[hsl(var(--surface-subtle))] text-xs text-[hsl(var(--muted-foreground))]"><tr><th className="px-5 py-3">Project</th><th className="px-4 py-3">Client</th><th className="px-4 py-3">Onboarding</th><th className="px-4 py-3">Project</th><th className="px-4 py-3">Progress</th><th className="px-4 py-3">Overdue</th><th className="px-5 py-3"/></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.onboardingId}><td className="px-5 py-4 font-semibold">{r.projectName}</td><td className="px-4 py-4 text-[hsl(var(--muted-foreground))]">{r.clientName}</td><td className="px-4 py-4"><StatusBadge status={r.onboardingStatus}/></td><td className="px-4 py-4"><StatusBadge status={r.projectStatus}/></td><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="h-2 w-24 overflow-hidden rounded-full bg-[hsl(var(--surface-subtle))]"><div className="h-full rounded-full bg-[hsl(var(--primary))]" style={{width:`${Math.max(0,Math.min(100,r.progressPercent))}%`}}/></div><span className="text-xs font-semibold">{r.progressPercent}%</span></div></td><td className="px-4 py-4">{r.overdueSteps?<Badge variant="warning">{r.overdueSteps}</Badge>:<span className="text-[hsl(var(--muted-foreground))]">—</span>}</td><td className="px-5 py-4 text-right"><Button asChild variant="ghost" size="sm"><Link href={`/app/projects/${r.projectId}`}>Open<ArrowUpRight className="size-3.5"/></Link></Button></td></tr>)}</tbody></table></div>}</section>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Mini label="Avg onboarding" value={hours(data.durations.averageOnboardingHours)}/><Mini label="Median onboarding" value={hours(data.durations.medianOnboardingHours)}/><Mini label="Client wait" value={hours(data.durations.averageClientActionWaitingHours)}/><Mini label="Internal review wait" value={hours(data.durations.averageInternalReviewWaitingHours)}/><Mini label="Activation lag" value={hours(data.durations.averageActivationHours)}/></div></>;
}
function Metric({label,value,helper,icon:Icon}:{label:string;value:number;helper:string;icon:typeof WalletCards}){return <article className="panel p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-.04em]">{value}</p></div><div className="grid size-10 place-items-center rounded-xl bg-[hsl(var(--primary-soft))] text-[hsl(var(--primary))]"><Icon className="size-4.5"/></div></div><p className="mt-3 text-xs text-[hsl(var(--muted-foreground))]">{helper}</p></article>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border bg-[hsl(var(--surface))] p-4"><p className="text-[11px] font-semibold uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-1.5 text-lg font-semibold">{value}</p></div>}
function Funnel({metric:m}:{metric:FunnelMetric}){return <div><div className="mb-1.5 flex items-center justify-between gap-3"><p className="text-sm font-semibold">{m.stepType.replaceAll('_',' ')}</p><span className="text-xs text-[hsl(var(--muted-foreground))]">{m.completed}/{m.total} · {m.completionRatePercent}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-[hsl(var(--surface-subtle))]"><div className="h-full rounded-full bg-[hsl(var(--primary))]" style={{width:`${Math.max(0,Math.min(100,m.completionRatePercent))}%`}}/></div>{(m.needsRevision>0||m.failed>0)&&<p className="mt-1 text-[11px] text-[hsl(var(--muted-foreground))]">{m.needsRevision} revision · {m.failed} failed</p>}</div>}
function SectionTitle({title,body}:{title:string;body:string}){return <div className="border-b p-5"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{body}</p></div>}
function Loading(){return <div className="panel flex min-h-80 items-center justify-center text-sm text-[hsl(var(--muted-foreground))]"><Loader2 className="mr-2 size-4 animate-spin"/>Building tenant-scoped reports…</div>}
function formatMoney(v:number,currency:string){try{return new Intl.NumberFormat(undefined,{style:"currency",currency,maximumFractionDigits:0}).format(v/100)}catch{return `${currency} ${(v/100).toFixed(0)}`}}function financialHeadline(currencies:ReportingSnapshot["financial"]["currencies"]){if(currencies.length===0)return "No payments";if(currencies.length===1)return formatMoney(currencies[0].collectedMinor,currencies[0].currency);return `${currencies.length} currencies`}function hours(v:number|null){if(v==null)return "—";if(v<48)return `${v.toFixed(1)}h`;return `${(v/24).toFixed(1)}d`}function msg(e:unknown,f:string){return e instanceof ApiClientError?e.message:f}
