package com.brainserve.onboarding.tasks.api.controller;
import com.brainserve.onboarding.common.api.ApiResponse; import com.brainserve.onboarding.common.observability.RequestContext; import com.brainserve.onboarding.common.security.TenantPrincipal;
import com.brainserve.onboarding.tasks.api.request.*; import com.brainserve.onboarding.tasks.api.response.TaskResponse; import com.brainserve.onboarding.tasks.application.service.TaskService; import com.brainserve.onboarding.tasks.domain.model.TaskStatus;
import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import java.util.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/tasks") public class TaskController {private final TaskService service;public TaskController(TaskService service){this.service=service;}
@PostMapping @PreAuthorize("hasAuthority('TASK_MANAGE')") ApiResponse<TaskResponse> create(@AuthenticationPrincipal TenantPrincipal p,@Valid @RequestBody CreateTaskRequest b,HttpServletRequest r){return ApiResponse.success(service.create(p,b,r),RequestContext.requestId());}
@GetMapping @PreAuthorize("hasAnyAuthority('TASK_READ','TASK_MANAGE')") ApiResponse<List<TaskResponse>> list(@AuthenticationPrincipal TenantPrincipal p,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size,@RequestParam(required=false)UUID projectId,@RequestParam(required=false)TaskStatus status,@RequestParam(defaultValue="false")boolean mine){var x=service.list(p,page,size,projectId,status,mine);return ApiResponse.success(x.items(),Map.of("page",x.page(),"size",x.size(),"totalElements",x.totalElements(),"totalPages",x.totalPages()),RequestContext.requestId());}
@GetMapping("/{id}") @PreAuthorize("hasAnyAuthority('TASK_READ','TASK_MANAGE')") ApiResponse<TaskResponse> get(@AuthenticationPrincipal TenantPrincipal p,@PathVariable UUID id){return ApiResponse.success(service.get(p,id),RequestContext.requestId());}
@PutMapping("/{id}") @PreAuthorize("hasAuthority('TASK_MANAGE')") ApiResponse<TaskResponse> update(@AuthenticationPrincipal TenantPrincipal p,@PathVariable UUID id,@Valid @RequestBody UpdateTaskRequest b,HttpServletRequest r){return ApiResponse.success(service.update(p,id,b,r),RequestContext.requestId());}
@PostMapping("/{id}/transition") @PreAuthorize("hasAuthority('TASK_MANAGE') or @taskAuthorization.isInternalAssignee(authentication,#id)") ApiResponse<TaskResponse> transition(@AuthenticationPrincipal TenantPrincipal p,@PathVariable UUID id,@Valid @RequestBody TransitionTaskRequest b,HttpServletRequest r){return ApiResponse.success(service.transition(p,id,b,r),RequestContext.requestId());}
}
