"use client";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { CheckCircle2,ClipboardCheck,Clock3,Filter,Loader2,Plus,RefreshCw } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { EmptyState } from "@/components/shared/empty-state";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError } from "@/services/api-client";
import type { Project } from "@/types/project";
import type { TaskItem,TaskPriority,TaskStatus } from "@/types/tasks";

const statuses:Array<TaskStatus|"ALL">=["ALL","TODO","IN_PROGRESS","BLOCKED","IN_REVIEW","COMPLETED","CANCELLED"];
export default function TasksPage(){
 const{authorizedRequest,hasPermission}=useAuth();const canRead=hasPermission("TASK_READ")||hasPermission("TASK_MANAGE");const canManage=hasPermission("TASK_MANAGE");
 const[tasks,setTasks]=useState<TaskItem[]>([]);const[projects,setProjects]=useState<Project[]>([]);const[status,setStatus]=useState<TaskStatus|"ALL">("ALL");const[mine,setMine]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[create,setCreate]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const q=new URLSearchParams({size:"100",mine:String(mine)});if(status!=="ALL")q.set("status",status);setTasks(await authorizedRequest<TaskItem[]>(`/tasks?${q}`));}catch(e){setError(msg(e,"Tasks could not be loaded."))}finally{setLoading(false)}},[authorizedRequest,mine,status]);
 useEffect(()=>{if(canRead)void load()},[canRead,load]);useEffect(()=>{if(create&&canManage)void authorizedRequest<Project[]>("/projects?size=100").then(setProjects).catch(()=>setProjects([]))},[authorizedRequest,canManage,create]);
 const metrics=useMemo(()=>({open:tasks.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).length,overdue:tasks.filter(t=>t.dueAt&&new Date(t.dueAt)<new Date()&&!['COMPLETED','CANCELLED'].includes(t.status)).length,review:tasks.filter(t=>t.status==='IN_REVIEW').length}),[tasks]);
 if(!canRead)return <PermissionState/>;
 return <><PageHeading eyebrow="Tasks" title="Work that has a clear owner" description="Track manual and workflow-generated work without turning the dashboard into a second workflow engine." actions={<div className="flex gap-2"><Button variant="secondary" size="icon" aria-label="Refresh tasks" onClick={()=>void load()}><RefreshCw className="size-4"/></Button>{canManage&&<Button onClick={()=>setCreate(v=>!v)}><Plus className="size-4"/>New task</Button>}</div>}/>
 <div className="mb-6 grid gap-4 sm:grid-cols-3"><Metric label="Open" value={metrics.open} icon={ClipboardCheck}/><Metric label="Overdue" value={metrics.overdue} icon={Clock3}/><Metric label="In review" value={metrics.review} icon={CheckCircle2}/></div>
 {create&&canManage&&<CreateTask projects={projects} onCancel={()=>setCreate(false)} onCreated={()=>{setCreate(false);void load()}}/>}
 {error&&<div className="mb-5"><FormMessage>{error}</FormMessage></div>}
 <section className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Task queue</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Assignments and state transitions remain server-authoritative.</p></div><div className="flex flex-wrap gap-2"><Select value={status} onChange={e=>setStatus(e.target.value as TaskStatus|"ALL")} className="min-w-44" aria-label="Task status filter">{statuses.map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</Select><Button variant={mine?"default":"secondary"} onClick={()=>setMine(v=>!v)}><Filter className="size-4"/>Assigned to me</Button></div></div>
 {loading?<Loading/>:tasks.length===0?<EmptyState title="No tasks match this view" description="Workflow-generated and manual tasks appear here when they have work to track."/>:<div className="divide-y">{tasks.map(task=><TaskRow key={task.id} task={task} onChanged={load}/>)}</div>}</section></>;
}
function TaskRow({task,onChanged}:{task:TaskItem;onChanged:()=>Promise<void>}){const{authorizedRequest,hasPermission}=useAuth();const[busy,setBusy]=useState(false);const canManage=hasPermission("TASK_MANAGE");async function transition(status:TaskStatus){setBusy(true);try{await authorizedRequest(`/tasks/${task.id}/transition`,{method:"POST",body:JSON.stringify({status,version:task.version})});await onChanged()}finally{setBusy(false)}}const next=task.status==="TODO"?"IN_PROGRESS":task.status==="IN_PROGRESS"?"IN_REVIEW":task.status==="IN_REVIEW"?"COMPLETED":null;return <div className="grid gap-4 p-5 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{task.title}</p><StatusBadge status={task.status}/><Badge variant="neutral">{task.taskType}</Badge><Badge variant={task.priority==="URGENT"?"danger":task.priority==="HIGH"?"warning":"neutral"}>{task.priority}</Badge></div>{task.description&&<p className="mt-2 line-clamp-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{task.description}</p>}<p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{task.dueAt?`Due ${format(task.dueAt)}`:"No due date"}{task.projectId?` · Project ${task.projectId.slice(0,8)}`:""}</p></div><div className="flex flex-wrap gap-2">{task.projectId&&<Button asChild size="sm" variant="secondary"><Link href={`/app/projects/${task.projectId}`}>Project</Link></Button>}{next&&<Button size="sm" disabled={busy} onClick={()=>void transition(next)}>{busy&&<Loader2 className="size-4 animate-spin"/>}{next==="COMPLETED"?"Complete":next.replaceAll('_',' ')}</Button>}{canManage&&!['COMPLETED','CANCELLED'].includes(task.status)&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>void transition("CANCELLED")}>Cancel</Button>}</div></div>}
function CreateTask({projects,onCancel,onCreated}:{projects:Project[];onCancel:()=>void;onCreated:()=>void}){const{authorizedRequest}=useAuth();const[title,setTitle]=useState("");const[description,setDescription]=useState("");const[projectId,setProjectId]=useState("");const[priority,setPriority]=useState<TaskPriority>("MEDIUM");const[dueAt,setDueAt]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{await authorizedRequest("/tasks",{method:"POST",body:JSON.stringify({title,description:description||null,projectId:projectId||null,onboardingId:null,stepId:null,priority,assignedUserId:null,assignedUserType:null,assignedRoleId:null,dueAt:dueAt?new Date(dueAt).toISOString():null})});onCreated()}catch(err){setError(msg(err,"Task could not be created."))}finally{setBusy(false)}}return <section className="panel mb-6 overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Create manual task</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Keep assignments explicit; workflow-generated tasks remain owned by the workflow engine.</p></div><form onSubmit={submit} className="grid gap-4 p-5 lg:grid-cols-2"><Field label="Title"><Input value={title} onChange={e=>setTitle(e.target.value)} maxLength={220} required/></Field><Field label="Project"><Select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><Field label="Priority"><Select value={priority} onChange={e=>setPriority(e.target.value as TaskPriority)}>{["LOW","MEDIUM","HIGH","URGENT"].map(v=><option key={v}>{v}</option>)}</Select></Field><Field label="Due"><Input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></Field><div className="lg:col-span-2"><Field label="Description"><Textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} maxLength={4000}/></Field></div>{error&&<div className="lg:col-span-2"><FormMessage>{error}</FormMessage></div>}<div className="flex justify-end gap-2 lg:col-span-2"><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button><Button disabled={busy||!title.trim()}>{busy&&<Loader2 className="size-4 animate-spin"/>}Create task</Button></div></form></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}function Metric({label,value,icon:Icon}:{label:string;value:number;icon:typeof ClipboardCheck}){return <div className="panel p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-.04em]">{value}</p></div><div className="grid size-10 place-items-center rounded-xl bg-[hsl(var(--surface-subtle))]"><Icon className="size-4.5"/></div></div></div>}function Loading(){return <div className="flex items-center justify-center py-14 text-sm text-[hsl(var(--muted-foreground))]"><Loader2 className="mr-2 size-4 animate-spin"/>Loading tasks…</div>}function format(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}function msg(e:unknown,f:string){return e instanceof ApiClientError?e.message:f}
