"use client";
import { useEffect, useRef, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { billingApi } from "./billing-api";
import { control, errorMessage, money, paise, type InvoiceView, type PaymentHistory, type PaymentTransaction, type Refund } from "./types";

export function BillingAdmin({ view, history, permissions, reload }: { view: InvoiceView; history: PaymentHistory; permissions: string[]; reload: () => Promise<void> }) {
  const [action, setAction] = useState<"VOID" | "CANCELLED" | "MANUAL" | "">(""); const [reason, setReason] = useState(""); const [amount, setAmount] = useState(""); const [reference, setReference] = useState(""); const [order, setOrder] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const key = useRef({ request: "", value: "" });
  async function run(command: () => Promise<unknown>, message: string) { setPending(true); setError(""); try { await command(); await reload(); setMessage(message); setAction(""); setReason(""); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }
  function manual() { const minor = paise(amount); const request = JSON.stringify([minor, reference, reason]); if (key.current.request !== request) key.current = { request, value: crypto.randomUUID() }; return billingApi.manual(view.invoice.id, minor, reference, reason, key.current.value); }
  const open = history.pendingCheckout;
  return <Card><h2 className="text-xl font-bold">Invoice controls</h2>{error && <Alert tone="error" className="mt-4">{error}</Alert>}{message && <Alert tone="success" className="mt-4">{message}</Alert>}<div className="mt-5 flex flex-wrap gap-3">
    {view.invoice.status === "DRAFT" && permissions.includes("INVOICE_SEND") && <Button variant="accent" disabled={pending} onClick={() => run(() => billingApi.publish(view.invoice.id, view.invoice.version), "Invoice published in the client portal.")}>Publish to client portal</Button>}
    {permissions.includes("PAYMENT_RECONCILE") && <Button variant="outline" disabled={pending} onClick={() => run(() => billingApi.sync(view.invoice.id), "Payment requirement recalculated.")}>Sync payment requirement</Button>}
    {permissions.includes("PAYMENT_OVERRIDE") && view.invoice.status !== "DRAFT" && view.balanceMinor > 0 && !view.invoice.reservedMinor && <Button variant="outline" disabled={pending} onClick={() => setAction("MANUAL")}>Record offline payment</Button>}
    {permissions.includes("INVOICE_SEND") && !["VOID", "CANCELLED"].includes(view.invoice.status) && !view.invoice.capturedMinor && !view.invoice.reservedMinor && <><Button variant="outline" disabled={pending} onClick={() => setAction("VOID")}>Void invoice</Button><Button variant="ghost" disabled={pending} onClick={() => setAction("CANCELLED")}>Cancel invoice</Button></>}
  </div>{action && <form className="mt-5 space-y-4 border-t pt-5" onSubmit={(e) => { e.preventDefault(); void run(action === "MANUAL" ? manual : () => billingApi.close(view.invoice.id, view.invoice.version, action === "VOID" ? "VOID" : "CANCELLED", reason), action === "MANUAL" ? "Offline payment recorded." : "Invoice closed; financial history retained."); }}><h3 className="font-bold">{action === "MANUAL" ? "Confirm an offline payment" : `Confirm ${action === "VOID" ? "void" : "cancellation"}`}</h3>{action === "MANUAL" && <><label className="block text-sm font-semibold">Amount received (INR)<input required inputMode="decimal" className={control} value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label className="block text-sm font-semibold">Payment reference<input required maxLength={120} className={control} value={reference} onChange={(e) => setReference(e.target.value)} /></label></>}<label className="block text-sm font-semibold">Reason<textarea required maxLength={2000} className={control} value={reason} onChange={(e) => setReason(e.target.value)} /></label><div className="flex flex-wrap gap-3"><Button type="submit" disabled={pending || !reason.trim()}>Confirm {action === "MANUAL" ? "offline payment" : action === "VOID" ? "void" : "cancellation"}</Button><Button type="button" variant="ghost" disabled={pending} onClick={() => setAction("")}>Keep invoice unchanged</Button></div></form>}
    {open && permissions.includes("PAYMENT_RECONCILE") && <div className="mt-6 border-t pt-5"><h3 className="font-bold">Pending checkout · {money(open.amountMinor)}</h3><p className="mt-2 text-sm text-muted-foreground">{open.status}. Reconcile using Razorpay’s current payment evidence. Closing a checkout does not cancel its order.</p><p className="mt-2 text-xs [overflow-wrap:anywhere]">Receipt: {open.receipt}</p>{!open.orderId && <label className="mt-3 block text-sm font-semibold">Razorpay order ID<input className={control} maxLength={100} value={order} onChange={(e) => setOrder(e.target.value)} placeholder="order_…" /></label>}<Button className="mt-4" variant="outline" disabled={pending || !open.orderId && !order} onClick={() => run(() => billingApi.reconcile(open.id, order || undefined), "Provider order reconciled.")}>Reconcile checkout</Button></div>}
  </Card>;
}

export function RefundPanel({ transaction, reload }: { transaction: PaymentTransaction; reload: () => Promise<void> }) {
  const [rows, setRows] = useState<Refund[]>([]); const [page, setPage] = useState(0); const [amount, setAmount] = useState(""); const [reason, setReason] = useState(""); const [providerIds, setProviderIds] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const key = useRef({ input: "", value: "" });
  useEffect(() => { let active = true; billingApi.refunds(transaction.id, page).then((r) => { if (active) setRows(r); }).catch((e) => { if (active) setError(errorMessage(e)); }); return () => { active = false; }; }, [transaction.id, page]);
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); setRows(await billingApi.refunds(transaction.id, page)); await reload(); setMessage("Refund status updated. Pending refunds are not treated as completed."); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  function create() { const minor = paise(amount); const input = JSON.stringify([minor, reason]); if (key.current.input !== input) key.current = { input, value: crypto.randomUUID() }; return billingApi.refund(transaction.id, minor, reason, key.current.value); }
  return <div className="mt-4 border-t pt-4"><h3 className="font-bold">Refunds</h3>{error && <Alert tone="error" className="mt-3">{error}</Alert>}{message && <Alert className="mt-3">{message}</Alert>}{transaction.amountMinor > transaction.refundedMinor && ["CAPTURED", "PARTIALLY_REFUNDED"].includes(transaction.status) && <form className="mt-4 space-y-3" onSubmit={(e) => { e.preventDefault(); void run(create); }}><p className="text-sm text-muted-foreground">A refund may reopen the onboarding payment requirement. Confirm the amount and reason before submitting.</p><label className="block text-sm font-semibold">Refund amount (INR)<input required inputMode="decimal" className={control} value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label className="block text-sm font-semibold">Refund reason<textarea required maxLength={2000} className={control} value={reason} onChange={(e) => setReason(e.target.value)} /></label><Button type="submit" variant="outline" disabled={busy || !reason.trim()}>Confirm refund</Button></form>}
    {!rows.length && <p className="mt-4 text-sm text-muted-foreground">No refund requests on this page.</p>}<ul className="mt-4 space-y-3">{rows.map((r) => <li key={r.id} className="rounded-lg border p-3"><p className="font-semibold">{money(r.amountMinor)} · {r.status}</p><p className="mt-2 text-sm [overflow-wrap:anywhere]">{r.reason}</p><p className="mt-2 text-xs [overflow-wrap:anywhere]">Receipt: {r.id}</p>{!["PROCESSED", "FAILED"].includes(r.status) && <>{!r.providerRefundId && <label className="mt-3 block text-sm font-semibold">Razorpay refund ID<input className={control} value={providerIds[r.id] || ""} maxLength={100} onChange={(e) => setProviderIds({ ...providerIds, [r.id]: e.target.value })} /></label>}<Button variant="outline" className="mt-3" disabled={busy || !r.providerRefundId && !providerIds[r.id]} onClick={() => run(() => billingApi.reconcileRefund(r.id, providerIds[r.id]))}>Reconcile refund</Button></>}</li>)}</ul><div className="mt-3 flex gap-3"><Button variant="ghost" disabled={!page || busy} onClick={() => setPage(page - 1)}>Newer refunds</Button><Button variant="ghost" disabled={rows.length < 20 || busy} onClick={() => setPage(page + 1)}>Older refunds</Button></div>
  </div>;
}
