"use client";
import { useRef, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { billingApi } from "./billing-api";
import { control, errorMessage, itemPreview, money, paise, type InvoiceView } from "./types";

export function InvoiceCreate({ stepId, created }: { stepId: string; created: (view: InvoiceView) => void }) {
  const [items, setItems] = useState([{ description: "", quantity: 1, amount: "", tax: "0" }]); const [due, setDue] = useState(""); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const key = useRef({ input: "", value: "" });
  const values = () => items.map((item) => ({ description: item.description, quantity: item.quantity, unitAmountMinor: paise(item.amount), taxBasisPoints: paise(item.tax) }));
  let preview: number | undefined; try { preview = itemPreview(values()); } catch { /* Empty draft amounts have no total yet. */ }
  const change = (index: number, patch: Partial<typeof items[number]>) => setItems(items.map((item, i) => i === index ? { ...item, ...patch } : item));
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); setPending(true); try { const lines = values(); const input = JSON.stringify([stepId, due, note, lines]); if (key.current.input !== input) key.current = { input, value: crypto.randomUUID() }; created(await billingApi.create(stepId, due, note, lines, key.current.value)); } catch (e) { setError(errorMessage(e)); } finally { setPending(false); } }
  return <Card className="mt-6"><h1 className="text-3xl font-bold">Create invoice</h1><p className="mt-3 text-sm text-muted-foreground">The payment policy comes from this project’s workflow. Review the draft before publishing it to the client.</p>{error && <Alert tone="error" className="mt-5">{error}</Alert>}<form className="mt-6 space-y-5" onSubmit={submit}><fieldset disabled={pending} className="space-y-4"><legend className="sr-only">Invoice items</legend>{items.map((item, index) => <div key={index} className="rounded-lg border p-4"><h2 className="font-semibold">Item {index + 1}</h2><div className="mt-3 grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold sm:col-span-3">Description<input required maxLength={500} className={control} value={item.description} onChange={(e) => change(index, { description: e.target.value })} /></label><label className="text-sm font-semibold">Quantity<input required type="number" min={1} max={10000} className={control} value={item.quantity} onChange={(e) => change(index, { quantity: Number(e.target.value) })} /></label><label className="text-sm font-semibold">Unit price (INR)<input required inputMode="decimal" className={control} value={item.amount} onChange={(e) => change(index, { amount: e.target.value })} /></label><label className="text-sm font-semibold">Tax (%)<input required inputMode="decimal" className={control} value={item.tax} onChange={(e) => change(index, { tax: e.target.value })} /></label></div><Button type="button" variant="ghost" className="mt-3" disabled={items.length === 1} onClick={() => setItems(items.filter((_, i) => i !== index))}>Remove item {index + 1}</Button></div>)}<Button type="button" variant="outline" disabled={items.length >= 50} onClick={() => setItems([...items, { description: "", quantity: 1, amount: "", tax: "0" }])}>Add invoice item</Button><label className="block text-sm font-semibold">Due date<input required type="date" className={control} value={due} onChange={(e) => setDue(e.target.value)} /></label><label className="block text-sm font-semibold">Client note (optional)<textarea maxLength={2000} className={control} value={note} onChange={(e) => setNote(e.target.value)} /></label></fieldset><p className="text-lg font-bold">Estimated total: {preview === undefined ? "Enter item amounts" : money(preview)}</p><p className="text-sm text-muted-foreground">The server confirms tax rounding and totals. Draft content is retained; void and replace it to correct an item.</p><Button type="submit" variant="accent" disabled={pending}>{pending ? "Creating…" : "Create draft invoice"}</Button></form></Card>;
}
