"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, ArrowDown, ArrowLeft, ArrowUp, CheckCircle2, GitBranch, Layers3, Loader2, LockKeyhole, Plus, Rocket, Save, Trash2 } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError } from "@/services/api-client";
import type { Role } from "@/types/organization";
import type { PublishedFormVersion } from "@/types/forms";
import type { PublishedPlatformAccessGuide } from "@/types/platform-access";
import type { ContractTemplateVersion } from "@/types/contracts";
import type { ReminderPolicy } from "@/types/reminders";
import type { DependencyMode, WorkflowStep, WorkflowStepType, WorkflowTemplate, WorkflowVersion } from "@/types/workflow";

const stepTypes: WorkflowStepType[] = ["WELCOME","INSTRUCTION","FORM","FILE_UPLOAD","PAYMENT","CONTRACT","PLATFORM_ACCESS","MANUAL_TASK","APPROVAL","EXTERNAL_LINK","VIDEO_GUIDE","MEETING","CUSTOM"];

export default function WorkflowBuilderPage() {
  const params = useParams<{ templateId: string }>(); const { authorizedRequest, hasPermission } = useAuth();
  const canRead = hasPermission("WORKFLOW_READ") || hasPermission("WORKFLOW_MANAGE"); const canManage = hasPermission("WORKFLOW_MANAGE");
  const [template, setTemplate] = useState<WorkflowTemplate | null>(null); const [selected, setSelected] = useState<WorkflowVersion | null>(null);
  const [roles, setRoles] = useState<Role[]>([]); const [formVersions, setFormVersions] = useState<PublishedFormVersion[]>([]); const [accessGuides, setAccessGuides] = useState<PublishedPlatformAccessGuide[]>([]); const [contractVersions, setContractVersions] = useState<ContractTemplateVersion[]>([]); const [reminderPolicies, setReminderPolicies] = useState<ReminderPolicy[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [draftSteps, setDraftSteps] = useState<WorkflowStep[]>([]);

  const loadVersion = useCallback(async (versionId: string) => { const value = await authorizedRequest<WorkflowVersion>(`/workflow-templates/versions/${versionId}`); setSelected(value); setDraftSteps(value.steps); }, [authorizedRequest]);
  const load = useCallback(async () => { if (!params.templateId) return; setLoading(true); setError(null); try { const value = await authorizedRequest<WorkflowTemplate>(`/workflow-templates/${params.templateId}`); setTemplate(value); const choice = [...value.versions].sort((a,b) => (a.status === "DRAFT" ? -1 : b.versionNumber-a.versionNumber))[0]; if (choice) await loadVersion(choice.id); if (hasPermission("ROLE_READ") || hasPermission("ROLE_MANAGE")) { try { setRoles(await authorizedRequest<Role[]>("/roles")); } catch { setRoles([]); } } if (hasPermission("FORM_READ") || hasPermission("FORM_MANAGE")) { try { setFormVersions(await authorizedRequest<PublishedFormVersion[]>("/forms/published-versions")); } catch { setFormVersions([]); } } if (hasPermission("ACCESS_READ") || hasPermission("ACCESS_MANAGE")) { try { setAccessGuides(await authorizedRequest<PublishedPlatformAccessGuide[]>("/platform-access-types/published-versions")); } catch { setAccessGuides([]); } } if (hasPermission("CONTRACT_CREATE")) { try { setContractVersions(await authorizedRequest<ContractTemplateVersion[]>("/contract-templates/published-versions")); } catch { setContractVersions([]); } } if (hasPermission("REMINDER_MANAGE")) { try { setReminderPolicies((await authorizedRequest<ReminderPolicy[]>("/reminder-policies?size=100")).filter(p=>p.status==="ACTIVE")); } catch { setReminderPolicies([]); } } } catch (e) { setError(message(e,"Workflow could not be loaded.")); } finally { setLoading(false); } }, [authorizedRequest, hasPermission, loadVersion, params.templateId]);
  useEffect(() => { if (canRead) void load(); }, [canRead, load]);

  async function saveDraft() { if (!selected || selected.status !== "DRAFT") return; setBusy(true); setError(null); setNotice(null); try { const payload = draftSteps.map((step,index) => ({ stepKey: step.stepKey, name: step.name, description: step.description, stepType: step.stepType, displayOrder:index, required:step.required, blocking:step.blocking, clientVisible:step.clientVisible, requiresReview:step.requiresReview, dependencyMode:step.dependencyMode, conditionExpression:step.conditionExpression ?? {op:"ALWAYS"}, assignedRoleId:step.assignedRoleId, dueAfterHours:step.dueAfterHours, reminderPolicyId:step.reminderPolicyId, allowSkip:step.allowSkip, allowReopen:step.allowReopen, configuration:step.configuration ?? {}, dependencyKeys:step.dependencyKeys })); const value = await authorizedRequest<WorkflowVersion>(`/workflow-templates/versions/${selected.id}`, { method:"PUT", body:JSON.stringify({ version:selected.version, changeNote:selected.changeNote, steps:payload }) }); setSelected(value); setDraftSteps(value.steps); setNotice("Draft saved and revalidated."); await refreshTemplate(); } catch(e){setError(message(e,"Draft could not be saved."));} finally{setBusy(false);} }
  async function publish(){ if(!selected||selected.status!=="DRAFT"||!confirm("Publish this version? Its workflow definition becomes immutable."))return;setBusy(true);setError(null);setNotice(null);try{const value=await authorizedRequest<WorkflowVersion>(`/workflow-templates/versions/${selected.id}/publish`,{method:"POST",body:JSON.stringify({version:selected.version})});setSelected(value);setDraftSteps(value.steps);setNotice(`Version ${value.versionNumber} is published and immutable.`);await refreshTemplate()}catch(e){setError(message(e,"Workflow could not be published."))}finally{setBusy(false)}}
  async function newVersion(){ if(!template)return;setBusy(true);setError(null);try{const value=await authorizedRequest<WorkflowVersion>(`/workflow-templates/${template.id}/versions`,{method:"POST",body:JSON.stringify({changeNote:"New revision"})});setSelected(value);setDraftSteps(value.steps);await refreshTemplate()}catch(e){setError(message(e,"A new version could not be created."))}finally{setBusy(false)}}
  async function refreshTemplate(){if(!template)return;setTemplate(await authorizedRequest<WorkflowTemplate>(`/workflow-templates/${template.id}`))}

  const hasDraft = template?.versions.some(v=>v.status==="DRAFT") ?? false;
  if(!canRead)return <PermissionState/>;
  if(loading)return <div className="panel flex min-h-72 items-center justify-center text-sm text-[hsl(var(--muted-foreground))]"><Loader2 className="mr-2 size-4 animate-spin"/>Loading workflow builder…</div>;
  if(!template)return <div className="space-y-4"><Button asChild variant="ghost"><Link href="/app/workflows"><ArrowLeft className="size-4"/>Back to workflows</Link></Button><FormMessage>{error??"Workflow was not found."}</FormMessage></div>;

  return <>
    <Button asChild variant="ghost" className="mb-5 -ml-2"><Link href="/app/workflows"><ArrowLeft className="size-4"/>Back to workflows</Link></Button>
    <PageHeading eyebrow="Workflow builder" title={template.name} description={template.description || "Configure steps, dependencies, conditions, assignments, visibility, review requirements, and readiness behavior."} actions={<div className="flex flex-wrap gap-2">{canManage&&!hasDraft&&template.versions.some(v=>v.status==="PUBLISHED")&&<Button variant="secondary" onClick={()=>void newVersion()} disabled={busy}><Layers3 className="size-4"/>New version</Button>}{canManage&&selected?.status==="DRAFT"&&<><Button variant="secondary" onClick={()=>void saveDraft()} disabled={busy}><Save className="size-4"/>Save draft</Button><Button onClick={()=>void publish()} disabled={busy||draftSteps.length===0}><Rocket className="size-4"/>Publish</Button></>}</div>}/>
    {(error||notice)&&<div className="mb-5">{error?<FormMessage>{error}</FormMessage>:<div className="rounded-xl border border-[hsl(var(--success)/.2)] bg-[hsl(var(--success-soft))] px-4 py-3 text-sm text-[hsl(var(--success))]"><CheckCircle2 className="mr-2 inline size-4"/>{notice}</div>}</div>}

    <div className="grid gap-6 xl:grid-cols-[17rem_minmax(0,1fr)]">
      <aside className="panel h-fit overflow-hidden xl:sticky xl:top-8"><div className="border-b px-4 py-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">Versions</p><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Published versions never change. Drafts remain private.</p></div><div className="p-2">{[...template.versions].sort((a,b)=>b.versionNumber-a.versionNumber).map(version=><button key={version.id} onClick={()=>void loadVersion(version.id)} className={`w-full rounded-xl px-3 py-3 text-left transition ${selected?.id===version.id?"bg-[hsl(var(--ink))] text-white":"hover:bg-[hsl(var(--surface-subtle))]"}`}><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">Version {version.versionNumber}</span><Badge variant={version.status==="PUBLISHED"?"success":"warning"}>{version.status}</Badge></div><p className={`mt-1 text-xs ${selected?.id===version.id?"text-white/65":"text-[hsl(var(--muted-foreground))]"}`}>{version.stepCount} steps · {formatDate(version.updatedAt)}</p></button>)}</div></aside>

      <main className="min-w-0 space-y-5">
        {selected&&<section className="panel overflow-hidden"><div className="flex flex-col gap-4 border-b bg-[hsl(var(--surface-subtle)/.5)] p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold tracking-[-.02em]">Version {selected.versionNumber}</h2><StatusBadge status={selected.status}/>{selected.status==="PUBLISHED"&&<Badge variant="neutral"><LockKeyhole className="mr-1 size-3"/>Immutable</Badge>}</div><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{selected.status==="DRAFT"?"Changes affect only this draft until it is published.":"Existing and future onboardings can safely reference this exact definition."}</p></div><div className="text-left sm:text-right"><p className="text-2xl font-semibold tracking-[-.03em]">{draftSteps.length}</p><p className="text-xs text-[hsl(var(--muted-foreground))]">configured steps</p></div></div>
          {selected.status==="DRAFT"?<div className="space-y-4 p-4 sm:p-5">{draftSteps.length===0&&<div className="rounded-2xl border border-dashed p-8 text-center"><GitBranch className="mx-auto size-7 text-[hsl(var(--muted-foreground))]"/><p className="mt-3 font-semibold">Build the first step</p><p className="mx-auto mt-1 max-w-md text-sm leading-6 text-[hsl(var(--muted-foreground))]">Start with an instruction or task, then add dependencies to create sequential or parallel paths.</p></div>}{draftSteps.map((step,index)=><StepEditor key={`${step.id}-${index}`} step={step} index={index} allSteps={draftSteps} roles={roles} formVersions={formVersions} accessGuides={accessGuides} contractVersions={contractVersions} reminderPolicies={reminderPolicies} onChange={value=>setDraftSteps(current=>current.map((item,i)=>i===index?value:item))} onRemove={()=>setDraftSteps(current=>current.filter((_,i)=>i!==index))} onMove={direction=>setDraftSteps(current=>move(current,index,direction))}/>)}<Button variant="secondary" className="w-full border-dashed" onClick={()=>setDraftSteps(current=>[...current,newStep(current.length)])}><Plus className="size-4"/>Add workflow step</Button><div className="rounded-xl bg-[hsl(var(--info-soft))] p-4 text-xs leading-5 text-[hsl(var(--foreground))]"><AlertTriangle className="mr-2 inline size-4 text-[hsl(var(--info))]"/>Conditions use a bounded JSON DSL; they are validated by the server and are never executed as code. Attach an active reminder policy only when this step genuinely needs a bounded follow-up cadence; completed and cancelled work is always suppressed.</div></div>:<PublishedSteps steps={draftSteps}/>}
        </section>}
      </main>
    </div>
  </>;
}

function StepEditor({step,index,allSteps,roles,formVersions,accessGuides,contractVersions,reminderPolicies,onChange,onRemove,onMove}:{step:WorkflowStep;index:number;allSteps:WorkflowStep[];roles:Role[];formVersions:PublishedFormVersion[];accessGuides:PublishedPlatformAccessGuide[];contractVersions:ContractTemplateVersion[];reminderPolicies:ReminderPolicy[];onChange:(step:WorkflowStep)=>void;onRemove:()=>void;onMove:(direction:-1|1)=>void}){
  const [conditionText,setConditionText]=useState(()=>JSON.stringify(step.conditionExpression??{op:"ALWAYS"}));
  const update=<K extends keyof WorkflowStep>(key:K,value:WorkflowStep[K])=>onChange({...step,[key]:value});
  function syncCondition(value:string){setConditionText(value);try{update("conditionExpression",JSON.parse(value) as Record<string,unknown>)}catch{/* keep text local until valid JSON */}}
  const dependencyOptions=allSteps.filter((_,i)=>i!==index);
  return <article className="rounded-2xl border bg-[hsl(var(--surface))] p-4 sm:p-5"><div className="mb-4 flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-[hsl(var(--ink))] text-xs font-bold text-white">{index+1}</div><div className="min-w-0 flex-1"><Input value={step.name} onChange={e=>update("name",e.target.value)} maxLength={180} aria-label={`Step ${index+1} name`} className="font-semibold"/><div className="mt-2 flex flex-wrap gap-1.5">{step.blocking&&<Badge variant="danger">Blocking</Badge>}{step.required?<Badge variant="info">Required</Badge>:<Badge variant="neutral">Optional</Badge>}{step.clientVisible&&<Badge variant="success">Client visible</Badge>}{step.requiresReview&&<Badge variant="warning">Review</Badge>}</div></div><div className="flex shrink-0"><Button variant="ghost" size="icon" onClick={()=>onMove(-1)} disabled={index===0} aria-label="Move step up"><ArrowUp className="size-4"/></Button><Button variant="ghost" size="icon" onClick={()=>onMove(1)} disabled={index===allSteps.length-1} aria-label="Move step down"><ArrowDown className="size-4"/></Button><Button variant="ghost" size="icon" onClick={onRemove} aria-label="Remove step"><Trash2 className="size-4"/></Button></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Step key"><Input value={step.stepKey} onChange={e=>update("stepKey",e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,"_"))} maxLength={80}/></Field><Field label="Step type"><Select value={step.stepType} onChange={e=>{const type=e.target.value as WorkflowStepType;const safeguards=type==="PLATFORM_ACCESS"?{requiresReview:true,clientVisible:true}:type==="APPROVAL"?{requiresReview:false,clientVisible:false}:type==="MANUAL_TASK"?{clientVisible:false}:{};onChange({...step,stepType:type,configuration:{},...safeguards})}}>{stepTypes.map(type=><option key={type}>{type}</option>)}</Select></Field><Field label="Dependency mode"><Select value={step.dependencyMode} onChange={e=>update("dependencyMode",e.target.value as DependencyMode)}><option value="NONE">No prerequisites</option><option value="ALL">All prerequisites</option><option value="ANY">Any prerequisite</option></Select></Field><Field label="Assigned role"><Select value={step.assignedRoleId??""} onChange={e=>update("assignedRoleId",e.target.value||null)}><option value="">Unassigned</option>{roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</Select></Field><Field label="Due after hours"><Input type="number" min={0} max={8760} value={step.dueAfterHours??""} onChange={e=>update("dueAfterHours",e.target.value===""?null:Number(e.target.value))}/></Field><Field label="Reminder policy"><Select value={step.reminderPolicyId??""} onChange={e=>update("reminderPolicyId",e.target.value||null)}><option value="">No reminders</option>{reminderPolicies.map(policy=><option key={policy.id} value={policy.id}>{policy.name} · max {policy.maximumReminders}</option>)}</Select></Field><Field label="Prerequisite steps"><Select multiple className="min-h-24" value={step.dependencyKeys} onChange={e=>update("dependencyKeys",Array.from(e.target.selectedOptions).map(option=>option.value))} disabled={step.dependencyMode==="NONE"}>{dependencyOptions.map(other=><option key={other.id} value={other.stepKey}>{other.name||other.stepKey}</option>)}</Select></Field></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><Field label="Description"><Textarea value={step.description??""} onChange={e=>update("description",e.target.value||null)} maxLength={2000} rows={3}/></Field><Field label="Condition DSL"><Textarea value={conditionText} onChange={e=>syncCondition(e.target.value)} rows={3} className="font-mono text-xs"/><p className="mt-1 text-[11px] text-[hsl(var(--muted-foreground))]">Example: {`{"op":"EQ","field":"service.code","value":"META_ADS"}`}</p></Field></div>
    {step.stepType==="FORM"&&<div className="mt-4 rounded-xl border bg-[hsl(var(--info-soft)/.35)] p-4"><Field label="Published questionnaire version"><Select value={String(step.configuration?.formVersionId??"")} onChange={e=>update("configuration",{...step.configuration,formVersionId:e.target.value})}><option value="">Choose a published form version</option>{formVersions.map(v=><option key={v.versionId} value={v.versionId}>{v.formName} · v{v.versionNumber} · {v.fieldCount} fields</option>)}</Select></Field><p className="mt-2 text-xs leading-5 text-[hsl(var(--muted-foreground))]">The server validates that this version belongs to your organization and is published before the workflow can be published.</p></div>}
    {step.stepType==="PLATFORM_ACCESS"&&<div className="mt-4 rounded-xl border bg-[hsl(var(--info-soft)/.35)] p-4"><Field label="Published platform access guide"><Select value={String(step.configuration?.platformAccessTypeVersionId??"")} onChange={e=>update("configuration",{platformAccessTypeVersionId:e.target.value})}><option value="">Choose a published access guide</option>{accessGuides.map(v=><option key={v.versionId} value={v.versionId}>{v.name} · v{v.versionNumber}</option>)}</Select></Field><p className="mt-2 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Platform-access steps are always client-visible and require internal verification. The server rejects workflow publication if those safety rules are weakened.</p></div>}
    {step.stepType==="CONTRACT"&&<div className="mt-4 grid gap-4 rounded-xl border bg-[hsl(var(--info-soft)/.35)] p-4 md:grid-cols-2"><Field label="Published contract template version"><Select value={String(step.configuration?.contractTemplateVersionId??"")} onChange={e=>update("configuration",{...step.configuration,contractTemplateVersionId:e.target.value})}><option value="">Choose a published contract version</option>{contractVersions.map(v=><option key={v.id} value={v.id}>{v.title} · v{v.versionNumber}</option>)}</Select></Field><Field label="Expires after days"><Input type="number" min={1} max={365} value={String(step.configuration?.expiresAfterDays??30)} onChange={e=>update("configuration",{...step.configuration,expiresAfterDays:Number(e.target.value)})}/></Field><p className="text-xs leading-5 text-[hsl(var(--muted-foreground))] md:col-span-2">The server freezes the published legal version when the contract is generated; sent legal content is immutable.</p></div>}
    <div className="mt-4 flex flex-wrap gap-x-5 gap-y-3 border-t pt-4">{([ ["required","Required"],["blocking","Blocking"],["clientVisible","Client visible"],["requiresReview","Requires review"],["allowSkip","Allow skip"],["allowReopen","Allow reopen"] ] as const).map(([key,label])=><label key={key} className="flex cursor-pointer items-center gap-2 text-sm"><input type="checkbox" checked={step[key]} disabled={(step.stepType==="PLATFORM_ACCESS"&&(key==="clientVisible"||key==="requiresReview"))||((step.stepType==="MANUAL_TASK"||step.stepType==="APPROVAL")&&key==="clientVisible")||(step.stepType==="APPROVAL"&&key==="requiresReview")} onChange={e=>update(key,e.target.checked)} className="size-4 rounded border"/><span>{label}</span></label>)}</div>
  </article>;
}
function PublishedSteps({steps}:{steps:WorkflowStep[]}){return <div className="divide-y">{steps.map((step,index)=><div key={step.id} className="flex gap-4 p-5"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-[hsl(var(--surface-subtle))] text-xs font-bold">{index+1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{step.name}</p><Badge variant="neutral">{step.stepType}</Badge>{step.blocking&&<Badge variant="danger">Blocking</Badge>}</div><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{step.description||"No description."}</p><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{step.dependencyMode==="NONE"?"Available without prerequisites":`${step.dependencyMode}: ${step.dependencyKeys.join(", ")}`}</p></div></div>)}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function newStep(index:number):WorkflowStep{return{id:`draft-${crypto.randomUUID()}`,stepKey:`STEP_${index+1}`,name:"New step",description:null,stepType:"MANUAL_TASK",displayOrder:index,required:true,blocking:true,clientVisible:false,requiresReview:false,dependencyMode:"NONE",dependencyKeys:[],conditionExpression:{op:"ALWAYS"},assignedRoleId:null,dueAfterHours:null,reminderPolicyId:null,allowSkip:false,allowReopen:false,configuration:{},};}
function move(items:WorkflowStep[],index:number,direction:-1|1){const next=index+direction;if(next<0||next>=items.length)return items;const copy=[...items];[copy[index],copy[next]]=[copy[next],copy[index]];return copy;}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value))}
function message(error:unknown,fallback:string){return error instanceof ApiClientError?error.message:fallback}
