package com.brainserve.onboarding.reminders.domain.model;
import com.fasterxml.jackson.databind.JsonNode;import jakarta.persistence.*;import java.time.*;import java.util.*;import org.hibernate.annotations.JdbcTypeCode;import org.hibernate.type.SqlTypes;
@Entity @Table(name="reminder_policies",schema="client_onboarding") public class ReminderPolicy {
@Id private UUID id;@Column(name="organization_id",nullable=false)private UUID organizationId;@Column(nullable=false,length=180)private String name;@Column(length=1000)private String description;@Column(name="initial_delay_minutes",nullable=false)private int initialDelayMinutes;@Column(name="repeat_interval_minutes",nullable=false)private int repeatIntervalMinutes;@Column(name="maximum_reminders",nullable=false)private int maximumReminders;@Column(name="business_hours_only",nullable=false)private boolean businessHoursOnly;@Column(nullable=false,length=64)private String timezone;@JdbcTypeCode(SqlTypes.JSON)@Column(nullable=false,columnDefinition="jsonb")private JsonNode channels;@Column(name="stop_when_completed",nullable=false)private boolean stopWhenCompleted;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private ReminderPolicyStatus status;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="created_by",nullable=false)private UUID createdBy;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Column(name="updated_by",nullable=false)private UUID updatedBy;@Version private long version;protected ReminderPolicy(){}
public ReminderPolicy(UUID id,UUID org,String name,String description,int initialDelay,int repeat,int max,boolean businessHours,String timezone,JsonNode channels,boolean stop,UUID actor,Instant now){this.id=id;this.organizationId=org;apply(name,description,initialDelay,repeat,max,businessHours,timezone,channels,stop);this.status=ReminderPolicyStatus.ACTIVE;this.createdAt=now;this.updatedAt=now;this.createdBy=actor;this.updatedBy=actor;}
public void update(String name,String description,int initialDelay,int repeat,int max,boolean businessHours,String timezone,JsonNode channels,boolean stop,UUID actor,Instant now){if(status!=ReminderPolicyStatus.ACTIVE)throw new IllegalStateException("Archived reminder policies cannot be edited");apply(name,description,initialDelay,repeat,max,businessHours,timezone,channels,stop);updatedBy=actor;updatedAt=now;}public void archive(UUID actor,Instant now){status=ReminderPolicyStatus.ARCHIVED;updatedBy=actor;updatedAt=now;}
private void apply(String n,String d,int initial,int repeat,int max,boolean bh,String tz,JsonNode ch,boolean stop){name=text(n,180,"Reminder policy name");description=optional(d,1000);if(initial<0||initial>525600)throw new IllegalArgumentException("Initial delay is out of range");if(repeat<15||repeat>525600)throw new IllegalArgumentException("Repeat interval is out of range");if(max<1||max>50)throw new IllegalArgumentException("Maximum reminders is out of range");try{ZoneId.of(tz);}catch(Exception ex){throw new IllegalArgumentException("Timezone is invalid");}initialDelayMinutes=initial;repeatIntervalMinutes=repeat;maximumReminders=max;businessHoursOnly=bh;timezone=tz;channels=ch.deepCopy();stopWhenCompleted=stop;}
private static String text(String v,int max,String l){if(v==null||v.isBlank())throw new IllegalArgumentException(l+" is required");String x=v.trim();if(x.length()>max)throw new IllegalArgumentException(l+" is too long");return x;}private static String optional(String v,int max){if(v==null||v.isBlank())return null;String x=v.trim();if(x.length()>max)throw new IllegalArgumentException("Value is too long");return x;}
public UUID getId(){return id;}public UUID getOrganizationId(){return organizationId;}public String getName(){return name;}public String getDescription(){return description;}public int getInitialDelayMinutes(){return initialDelayMinutes;}public int getRepeatIntervalMinutes(){return repeatIntervalMinutes;}public int getMaximumReminders(){return maximumReminders;}public boolean isBusinessHoursOnly(){return businessHoursOnly;}public String getTimezone(){return timezone;}public JsonNode getChannels(){return channels.deepCopy();}public boolean isStopWhenCompleted(){return stopWhenCompleted;}public ReminderPolicyStatus getStatus(){return status;}public Instant getUpdatedAt(){return updatedAt;}public long getVersion(){return version;}
}
