"use client";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowRight,CheckCircle2,KeyRound,Loader2,Plus,RefreshCw,Search,ShieldCheck } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { EmptyState } from "@/components/shared/empty-state";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError } from "@/services/api-client";
import type { PlatformAccessQueueItem,PlatformAccessTypeDetail,PlatformAccessTypeSummary } from "@/types/platform-access";

export default function AccessPage(){
 const{authorizedRequest,hasPermission}=useAuth();const canRead=hasPermission("ACCESS_READ")||hasPermission("ACCESS_VERIFY")||hasPermission("ACCESS_MANAGE");const canManage=hasPermission("ACCESS_MANAGE");
 const[types,setTypes]=useState<PlatformAccessTypeSummary[]>([]);const[requests,setRequests]=useState<PlatformAccessQueueItem[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[query,setQuery]=useState("");const[showCreate,setShowCreate]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [a,b]=await Promise.all([authorizedRequest<PlatformAccessTypeSummary[]>("/platform-access-types?size=100"),authorizedRequest<PlatformAccessQueueItem[]>("/platform-access-requests?size=100")]);setTypes(a);setRequests(b)}catch(e){setError(message(e,"Platform access workspace could not be loaded."))}finally{setLoading(false)}},[authorizedRequest]);useEffect(()=>{if(canRead)void load()},[canRead,load]);
 const pending=requests.filter(r=>r.status==="CLIENT_SUBMITTED"||r.status==="UNDER_VERIFICATION");const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return q?types.filter(t=>`${t.name} ${t.code} ${t.description??""}`.toLowerCase().includes(q)):types},[query,types]);
 if(!canRead)return <PermissionState/>;return <><PageHeading eyebrow="Platform access" title="Access without credential sharing" description="Give clients reproducible, versioned instructions for granting third-party access. Clients confirm that access was granted; only authorized team members can verify it." actions={<div className="flex gap-2"><Button variant="secondary" size="icon" onClick={()=>void load()} aria-label="Refresh platform access"><RefreshCw className="size-4"/></Button>{canManage&&<Button onClick={()=>setShowCreate(v=>!v)}><Plus className="size-4"/>New access type</Button>}</div>}/>
 <div className="mb-6 grid gap-4 sm:grid-cols-3"><Metric label="Access types" value={types.length} icon={KeyRound}/><Metric label="Needs review" value={pending.length} icon={ShieldCheck}/><Metric label="Verified" value={requests.filter(r=>r.status==="VERIFIED").length} icon={CheckCircle2}/></div>
 {showCreate&&canManage&&<CreateAccessType onCancel={()=>setShowCreate(false)} onCreated={v=>{setShowCreate(false);setTypes(cur=>[{id:v.id,code:v.code,name:v.name,description:v.description,status:v.status,publishedVersion:null,updatedAt:v.updatedAt,version:v.version},...cur])}}/>}
 {error&&<div className="mb-5"><FormMessage>{error}</FormMessage></div>}
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(22rem,.9fr)]"><section className="panel overflow-hidden"><div className="border-b p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Access guides</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Published versions are immutable and snapshotted into onboarding.</p></div><label className="relative sm:w-72"><span className="sr-only">Search access guides</span><Search className="absolute left-3 top-3 size-4 text-[hsl(var(--muted-foreground))]"/><Input className="pl-9" placeholder="Search guides…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div></div>{loading?<Loading/>:filtered.length===0?<EmptyState title="No access guides" description="Create a guide for Google Ads, Analytics, Shopify, WordPress, or any third-party platform your onboarding requires."/>:<div className="divide-y">{filtered.map(t=><Link key={t.id} href={`/app/access/types/${t.id}`} className="group flex items-center gap-4 p-5 hover:bg-[hsl(var(--surface-subtle)/.55)]"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[hsl(var(--primary-soft))] text-[hsl(var(--primary))]"><KeyRound className="size-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{t.name}</p><Badge variant="neutral">{t.code}</Badge><StatusBadge status={t.status}/>{t.publishedVersion?<Badge variant="success">Published v{t.publishedVersion}</Badge>:<Badge variant="warning">No published guide</Badge>}</div><p className="mt-1 line-clamp-2 text-sm text-[hsl(var(--muted-foreground))]">{t.description||"No description."}</p></div><ArrowRight className="size-4 text-[hsl(var(--muted-foreground))] transition-transform group-hover:translate-x-0.5"/></Link>)}</div>}</section>
 <section className="panel h-fit overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Verification queue</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Clients can submit. Your team remains the authority that verifies access.</p></div>{loading?<Loading/>:pending.length===0?<div className="p-6 text-sm text-[hsl(var(--muted-foreground))]">Nothing is waiting for verification.</div>:<div className="divide-y">{pending.slice(0,12).map(r=><Link key={r.id} href={`/app/access/requests/${r.id}`} className="block p-5 hover:bg-[hsl(var(--surface-subtle)/.55)]"><div className="flex items-center justify-between gap-3"><p className="font-medium">{r.accessTypeName}</p><StatusBadge status={r.status}/></div><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{r.accountIdentifier||"No account identifier supplied"}</p><p className="mt-2 text-[11px] text-[hsl(var(--muted-foreground))]">Updated {format(r.updatedAt)}</p></Link>)}</div>}</section></div></>;
}
function Metric({label,value,icon:Icon}:{label:string;value:number;icon:typeof KeyRound}){return <div className="panel p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-.04em]">{value}</p></div><div className="grid size-10 place-items-center rounded-xl bg-[hsl(var(--surface-subtle))]"><Icon className="size-4.5"/></div></div></div>}
function Loading(){return <div className="flex items-center justify-center py-12 text-sm text-[hsl(var(--muted-foreground))]"><Loader2 className="mr-2 size-4 animate-spin"/>Loading…</div>}
function CreateAccessType({onCancel,onCreated}:{onCancel:()=>void;onCreated:(value:PlatformAccessTypeDetail)=>void}){const{authorizedRequest}=useAuth();const[code,setCode]=useState("");const[name,setName]=useState("");const[description,setDescription]=useState("");const[instructions,setInstructions]=useState("Grant access through the platform's own user or role invitation controls. Never share passwords, API keys, tokens, or other authentication secrets.");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{onCreated(await authorizedRequest<PlatformAccessTypeDetail>("/platform-access-types",{method:"POST",body:JSON.stringify({code,name,description:description||null,instructionsMarkdown:instructions,helpUrl:null,changeNote:"Initial guide"})}))}catch(err){setError(message(err,"Access type could not be created."))}finally{setBusy(false)}}return <section className="panel mb-6 overflow-hidden"><div className="border-b bg-[hsl(var(--primary-soft)/.55)] p-5"><p className="font-semibold">Create a safe access guide</p><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Describe how to grant role-based access. The server rejects instructions that request passwords, tokens, API keys, or private keys.</p></div><form onSubmit={submit} className="grid gap-4 p-5 lg:grid-cols-2"><div className="space-y-2"><Label htmlFor="access-code">Code</Label><Input id="access-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,"_"))} maxLength={80} placeholder="GOOGLE_ADS" required/></div><div className="space-y-2"><Label htmlFor="access-name">Name</Label><Input id="access-name" value={name} onChange={e=>setName(e.target.value)} maxLength={180} placeholder="Google Ads" required/></div><div className="space-y-2 lg:col-span-2"><Label htmlFor="access-description">Description</Label><Input id="access-description" value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000} placeholder="What access the project requires."/></div><div className="space-y-2 lg:col-span-2"><Label htmlFor="access-instructions">Initial draft instructions</Label><Textarea id="access-instructions" value={instructions} onChange={e=>setInstructions(e.target.value)} rows={5} maxLength={20000} required/></div>{error&&<div className="lg:col-span-2"><FormMessage>{error}</FormMessage></div>}<div className="flex justify-end gap-2 lg:col-span-2"><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button><Button disabled={busy||!code||!name.trim()||!instructions.trim()}>{busy&&<Loader2 className="size-4 animate-spin"/>}Create draft</Button></div></form></section>}
function message(e:unknown,fallback:string){return e instanceof ApiClientError?e.message:fallback}function format(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}
