package com.brainserve.onboarding.notifications.application.service;
import com.brainserve.onboarding.notifications.domain.model.*;import com.brainserve.onboarding.notifications.infrastructure.persistence.*;import java.time.*;import java.util.*;import java.util.concurrent.ThreadLocalRandom;import org.slf4j.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.mail.SimpleMailMessage;import org.springframework.mail.javamail.JavaMailSender;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;import org.springframework.transaction.support.TransactionTemplate;
@Component public class EmailDeliveryWorker {
private static final Logger log=LoggerFactory.getLogger(EmailDeliveryWorker.class);private static final int MAX_ATTEMPTS=5;private final NotificationDeliveryRepository deliveries;private final NotificationRepository notifications;private final JavaMailSender mail;private final TransactionTemplate tx;private final Clock clock;private final String from;
public EmailDeliveryWorker(NotificationDeliveryRepository deliveries,NotificationRepository notifications,JavaMailSender mail,TransactionTemplate tx,Clock clock,@Value("${app.mail.from:no-reply@example.invalid}")String from){this.deliveries=deliveries;this.notifications=notifications;this.mail=mail;this.tx=tx;this.clock=clock;this.from=from;}
@Scheduled(fixedDelayString="${app.notifications.delivery-poll-ms:5000}")public void poll(){recover();for(NotificationDelivery d:deliveries.findTop50ByStatusInAndNextAttemptAtLessThanEqualOrderByNextAttemptAtAscIdAsc(List.of(NotificationDeliveryStatus.QUEUED,NotificationDeliveryStatus.FAILED),clock.instant())){Claim c=tx.execute(s->claim(d.getOrganizationId(),d.getId()));if(c==null)continue;try{SimpleMailMessage m=new SimpleMailMessage();m.setFrom(from);m.setTo(c.address);m.setSubject(c.subject);m.setText(c.body);mail.send(m);tx.executeWithoutResult(s->finish(c.organizationId,c.deliveryId,true,null));}catch(RuntimeException ex){log.warn("Notification email delivery failed id={}",c.deliveryId,ex);tx.executeWithoutResult(s->finish(c.organizationId,c.deliveryId,false,ex.getMessage()));}}}
private Claim claim(UUID organizationId,UUID id){NotificationDelivery d=deliveries.findForUpdate(organizationId,id).orElse(null);if(d==null||d.getChannel()!=NotificationChannel.EMAIL||!(d.getStatus()==NotificationDeliveryStatus.QUEUED||d.getStatus()==NotificationDeliveryStatus.FAILED)||d.getNextAttemptAt().isAfter(clock.instant()))return null;d.processing(clock.instant());deliveries.saveAndFlush(d);var n=notifications.findByOrganizationIdAndId(organizationId,d.getNotificationId()).orElse(null);if(n==null)return null;return new Claim(organizationId,d.getId(),d.getRecipientAddress(),n.getTitle(),n.getBody());}
private void finish(UUID organizationId,UUID id,boolean success,String error){NotificationDelivery d=deliveries.findForUpdate(organizationId,id).orElse(null);if(d==null)return;Instant now=clock.instant();if(success)d.sent(now);else{boolean dead=d.getAttemptCount()>=MAX_ATTEMPTS;long base=Math.min(3600L,30L*(1L<<Math.min(d.getAttemptCount(),6)));long jitter=ThreadLocalRandom.current().nextLong(0,Math.max(1,base/5));d.failed(error,now.plusSeconds(base+jitter),dead,now);}deliveries.saveAndFlush(d);}
private void recover(){Instant cutoff=clock.instant();for(NotificationDelivery d:deliveries.findTop50ByStatusInAndNextAttemptAtLessThanEqualOrderByNextAttemptAtAscIdAsc(List.of(NotificationDeliveryStatus.PROCESSING),cutoff)){tx.executeWithoutResult(s->{NotificationDelivery locked=deliveries.findForUpdate(d.getOrganizationId(),d.getId()).orElse(null);if(locked!=null&&locked.getStatus()==NotificationDeliveryStatus.PROCESSING){Instant now=clock.instant();boolean dead=locked.getAttemptCount()>=MAX_ATTEMPTS;locked.failed("Recovered stale email delivery claim",now,dead,now);}});}}
private record Claim(UUID organizationId,UUID deliveryId,String address,String subject,String body){}
}
