package com.brainserve.onboarding.notifications.application.service;
import java.time.Clock;import java.util.*;import org.springframework.boot.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;
@Component public class NotificationTemplateBootstrap implements ApplicationRunner {
private final JdbcTemplate jdbc;private final Clock clock;public NotificationTemplateBootstrap(JdbcTemplate jdbc,Clock clock){this.jdbc=jdbc;this.clock=clock;}
@Override @Transactional public void run(ApplicationArguments args){for(DefaultTemplate t:defaults())jdbc.update("INSERT INTO client_onboarding.notification_templates(id,organization_id,code,name,event_type,recipient_scope,required_permission,subject_template,body_template,action_path_template,channels,mandatory,status,created_at,updated_at) SELECT ?,o.id,?,?,?,?,?,?,?,?,CAST(? AS jsonb),?, 'ACTIVE',?,? FROM client_onboarding.organizations o WHERE o.status='ACTIVE' ON CONFLICT (organization_id,event_type) DO NOTHING",UUID.randomUUID(),t.code,t.name,t.event,t.scope,t.permission,t.subject,t.body,t.action,t.channelsJson,t.mandatory,clock.instant(),clock.instant());}
private static List<DefaultTemplate> defaults(){return List.of(
 new DefaultTemplate("FORM_SUBMITTED","Questionnaire submitted","FORM_SUBMITTED","PERMISSION","FORM_REVIEW","Questionnaire ready for review","A client submitted a questionnaire. Review it in the workspace.","/app/form-submissions", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("FORM_REVISION_REQUESTED","Questionnaire revision","FORM_REVISION_REQUESTED","PROJECT_CLIENTS",null,"Questionnaire needs revision","Your team requested changes to a questionnaire.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("FORM_APPROVED","Questionnaire approved","FORM_APPROVED","PROJECT_CLIENTS",null,"Questionnaire approved","Your questionnaire has been approved.","/portal/projects/{{project_id}}", "[\"IN_APP\"]",false),
 new DefaultTemplate("ASSET_UPLOADED","Asset uploaded","ASSET_UPLOADED","PERMISSION","ASSET_REVIEW","Asset ready for review","A client uploaded a project asset.","/app/assets", "[\"IN_APP\"]",false),
 new DefaultTemplate("ASSET_APPROVED","Asset approved","ASSET_APPROVED","PROJECT_CLIENTS",null,"Asset approved","A project asset has been approved.","/portal/projects/{{project_id}}", "[\"IN_APP\"]",false),
 new DefaultTemplate("ASSET_REVISION_REQUESTED","Asset revision","ASSET_REVISION_REQUESTED","PROJECT_CLIENTS",null,"Asset needs revision","Your team requested a replacement or revision for an asset.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("ACCESS_SUBMITTED","Access submitted","ACCESS_SUBMITTED","PERMISSION","ACCESS_VERIFY","Platform access ready for verification","A client submitted platform access for verification.","/app/access", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("ACCESS_VERIFIED","Access verified","ACCESS_VERIFIED","PROJECT_CLIENTS",null,"Platform access verified","Your platform access has been verified.","/portal/projects/{{project_id}}", "[\"IN_APP\"]",false),
 new DefaultTemplate("ACCESS_REVISION_REQUESTED","Access revision","ACCESS_REVISION_REQUESTED","PROJECT_CLIENTS",null,"Platform access needs attention","Your team requested an update to platform access.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("INVOICE_SENT","Invoice sent","INVOICE_SENT","PROJECT_CLIENTS",null,"A new invoice is available","A project invoice is ready to review.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("PAYMENT_CONFIRMED","Payment confirmed","PAYMENT_CONFIRMED","PROJECT_CLIENTS",null,"Payment confirmed","Your payment was confirmed successfully.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("CONTRACT_SENT","Contract sent","CONTRACT_SENT","PROJECT_CLIENTS",null,"Contract ready for signature","A project contract is ready for review and signature.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("CONTRACT_SIGNED","Contract signed","CONTRACT_SIGNED","PROJECT_CLIENTS",null,"Contract signed","The contract has been signed successfully.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("ONBOARDING_READY_FOR_REVIEW","Ready for final review","ONBOARDING_READY_FOR_REVIEW","PERMISSION","ONBOARDING_REVIEW","Onboarding is ready for review","All blocking requirements are complete. Final review can begin.","/app/projects/{{project_id}}/review", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("ONBOARDING_REVISION_REQUESTED","Final review revision","ONBOARDING_REVISION_REQUESTED","PROJECT_CLIENTS",null,"Onboarding needs revision","Your team requested changes during final onboarding review. Open the project to see your next action.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("ONBOARDING_COMPLETED","Onboarding completed","ONBOARDING_COMPLETED","PROJECT_CLIENTS",null,"Onboarding approved","All onboarding requirements have passed final review. Your project is ready for activation.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true),
 new DefaultTemplate("PROJECT_ACTIVATED","Project activated","PROJECT_ACTIVATED","PROJECT_CLIENTS",null,"Your project is active","Final review is complete and the project has been activated.","/portal/projects/{{project_id}}", "[\"IN_APP\",\"EMAIL\"]",true)
 );}
private record DefaultTemplate(String code,String name,String event,String scope,String permission,String subject,String body,String action,String channelsJson,boolean mandatory){}
}
