package com.brainserve.onboarding.notifications.application.service;
import com.brainserve.onboarding.audit.application.service.AuditService;import com.brainserve.onboarding.common.error.ApiException;import com.brainserve.onboarding.common.security.TenantPrincipal;import com.brainserve.onboarding.notifications.api.request.*;import com.brainserve.onboarding.notifications.api.response.NotificationTemplateResponse;import com.brainserve.onboarding.notifications.domain.model.NotificationTemplate;import com.brainserve.onboarding.notifications.infrastructure.persistence.NotificationTemplateRepository;import com.fasterxml.jackson.databind.ObjectMapper;import jakarta.servlet.http.HttpServletRequest;import java.time.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class NotificationTemplateService {
private final NotificationTemplateRepository templates;private final NotificationTemplateRenderer renderer;private final ObjectMapper mapper;private final AuditService audit;private final Clock clock;public NotificationTemplateService(NotificationTemplateRepository templates,NotificationTemplateRenderer renderer,ObjectMapper mapper,AuditService audit,Clock clock){this.templates=templates;this.renderer=renderer;this.mapper=mapper;this.audit=audit;this.clock=clock;}
@Transactional public NotificationTemplateResponse create(TenantPrincipal p,CreateNotificationTemplateRequest r,HttpServletRequest req){if(templates.existsByOrganizationIdAndCode(p.organizationId(),r.code().trim().toUpperCase(Locale.ROOT)))throw conflict("Notification template code already exists.");validateChannels(r.channels());renderer.validate(r.subjectTemplate(),r.bodyTemplate(),r.actionPathTemplate());NotificationTemplate entity;try{entity=new NotificationTemplate(UUID.randomUUID(),p.organizationId(),r.code().trim().toUpperCase(Locale.ROOT),r.name(),r.eventType(),r.recipientScope(),r.requiredPermission(),r.subjectTemplate(),r.bodyTemplate(),r.actionPathTemplate(),mapper.valueToTree(r.channels()),r.mandatory(),p.userId(),clock.instant());}catch(IllegalArgumentException|IllegalStateException ex){throw bad(ex.getMessage());}templates.saveAndFlush(entity);audit.record(p.organizationId(),p.userId(),"NOTIFICATION_TEMPLATE_CREATED","NOTIFICATION_TEMPLATE",entity.getId(),null,Map.of("eventType",entity.getEventType()),req);return map(entity);}
@Transactional(readOnly=true) public PageResult list(TenantPrincipal p,int page,int size){var pr=PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.ASC,"name"));var x=templates.findAllByOrganizationId(p.organizationId(),pr);return new PageResult(x.getContent().stream().map(NotificationTemplateService::map).toList(),x.getNumber(),x.getSize(),x.getTotalElements(),x.getTotalPages());}
@Transactional(readOnly=true) public NotificationTemplateResponse get(TenantPrincipal p,UUID id){return map(templates.findByOrganizationIdAndId(p.organizationId(),id).orElseThrow(NotificationTemplateService::notFound));}
@Transactional public NotificationTemplateResponse update(TenantPrincipal p,UUID id,SaveNotificationTemplateRequest r,HttpServletRequest req){var t=templates.findForUpdate(p.organizationId(),id).orElseThrow(NotificationTemplateService::notFound);if(t.getVersion()!=r.version())throw version();validateChannels(r.channels());renderer.validate(r.subjectTemplate(),r.bodyTemplate(),r.actionPathTemplate());try{t.update(r.name(),r.recipientScope(),r.requiredPermission(),r.subjectTemplate(),r.bodyTemplate(),r.actionPathTemplate(),mapper.valueToTree(r.channels()),r.mandatory(),p.userId(),clock.instant());}catch(IllegalArgumentException|IllegalStateException ex){throw bad(ex.getMessage());}templates.saveAndFlush(t);audit.record(p.organizationId(),p.userId(),"NOTIFICATION_TEMPLATE_UPDATED","NOTIFICATION_TEMPLATE",id,null,Map.of("eventType",t.getEventType()),req);return map(t);}
@Transactional public NotificationTemplateResponse archive(TenantPrincipal p,UUID id,long version,HttpServletRequest req){var t=templates.findForUpdate(p.organizationId(),id).orElseThrow(NotificationTemplateService::notFound);if(t.getVersion()!=version)throw version();t.archive(p.userId(),clock.instant());templates.saveAndFlush(t);audit.record(p.organizationId(),p.userId(),"NOTIFICATION_TEMPLATE_ARCHIVED","NOTIFICATION_TEMPLATE",id,null,Map.of(),req);return map(t);}
private static void validateChannels(List<String> channels){if(channels==null||channels.isEmpty()||channels.size()>2||channels.stream().distinct().count()!=channels.size()||channels.stream().anyMatch(c->!(c.equals("EMAIL")||c.equals("IN_APP"))))throw bad("Notification channels must contain unique EMAIL and/or IN_APP values.");}
private static NotificationTemplateResponse map(NotificationTemplate t){List<String> channels=new ArrayList<>();t.getChannels().forEach(v->channels.add(v.asText()));return new NotificationTemplateResponse(t.getId(),t.getCode(),t.getName(),t.getEventType(),t.getRecipientScope(),t.getRequiredPermission(),t.getSubjectTemplate(),t.getBodyTemplate(),t.getActionPathTemplate(),channels,t.isMandatory(),t.getStatus(),t.getUpdatedAt(),t.getVersion());}private static ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","Notification template was not found.");}private static ApiException version(){return new ApiException(HttpStatus.CONFLICT,"VERSION_CONFLICT","The notification template changed. Refresh and try again.");}private static ApiException conflict(String m){return new ApiException(HttpStatus.CONFLICT,"NOTIFICATION_TEMPLATE_CONFLICT",m);}private static ApiException bad(String m){return new ApiException(HttpStatus.BAD_REQUEST,"NOTIFICATION_TEMPLATE_INVALID",m);}public record PageResult(List<NotificationTemplateResponse> items,int page,int size,long totalElements,int totalPages){}
}
