package com.brainserve.onboarding.notifications.application.service;
import com.brainserve.onboarding.notifications.domain.model.*;import com.brainserve.onboarding.notifications.infrastructure.persistence.NotificationTemplateRepository;import com.fasterxml.jackson.databind.*;import java.time.*;import java.util.*;import org.slf4j.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;import org.springframework.transaction.support.TransactionTemplate;
@Component public class OutboxNotificationWorker {
    private static final Logger log=LoggerFactory.getLogger(OutboxNotificationWorker.class);private static final int MAX_ROUTING_ATTEMPTS=8;private static final Duration CLAIM_LEASE=Duration.ofMinutes(10);private final JdbcTemplate jdbc;private final NotificationTemplateRepository templates;private final NotificationRecipientResolver recipients;private final NotificationTemplateRenderer renderer;private final NotificationService notifications;private final ObjectMapper mapper;private final Clock clock;private final TransactionTemplate tx;
    public OutboxNotificationWorker(JdbcTemplate jdbc,NotificationTemplateRepository templates,NotificationRecipientResolver recipients,NotificationTemplateRenderer renderer,NotificationService notifications,ObjectMapper mapper,Clock clock,TransactionTemplate tx){this.jdbc=jdbc;this.templates=templates;this.recipients=recipients;this.renderer=renderer;this.notifications=notifications;this.mapper=mapper;this.clock=clock;this.tx=tx;}
    @Scheduled(fixedDelayString="${app.notifications.outbox-poll-ms:5000}") public void poll(){recoverStaleClaims();for(OutboxRow row:due()){try{process(row);}catch(RuntimeException ex){log.error("Notification routing failed for outbox event {}",row.id,ex);fail(row.id,ex);}}}
    private List<OutboxRow> due(){return jdbc.query("SELECT o.id,o.organization_id,o.event_type,o.aggregate_type,o.aggregate_id,o.payload::text,o.occurred_at FROM client_onboarding.outbox_events o LEFT JOIN client_onboarding.notification_event_receipts r ON r.outbox_event_id=o.id WHERE r.outbox_event_id IS NULL OR (r.status='FAILED' AND r.next_attempt_at<=CURRENT_TIMESTAMP) ORDER BY o.occurred_at,o.id LIMIT 50",(rs,n)->new OutboxRow(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getString(3),rs.getString(4),rs.getObject(5,UUID.class),rs.getString(6),rs.getTimestamp(7).toInstant()));}
    private void process(OutboxRow row){Boolean claimed=tx.execute(s->claim(row));if(!Boolean.TRUE.equals(claimed))return;int count=0;try{JsonNode payload=mapper.readTree(row.payload);NotificationTemplate t=templates.findByOrganizationIdAndEventTypeAndStatus(row.organizationId,row.eventType,"ACTIVE").orElse(null);if(t==null){complete(row.id,0,"SKIPPED",null);return;}UUID projectId=uuid(payload,"projectId");Map<String,Object> values=new HashMap<>();values.put("event_type",row.eventType);values.put("source_id",row.aggregateId);values.put("source_type",row.aggregateType);values.put("project_id",projectId==null?"":projectId.toString());values.put("status",text(payload,"status"));for(var recipient:recipients.resolve(row.organizationId,t.getRecipientScope(),t.getRequiredPermission(),projectId,payload)){values.put("recipient_name",recipient.displayName());String title=renderer.render(t.getSubjectTemplate(),values);String body=renderer.render(t.getBodyTemplate(),values);String action=renderer.render(t.getActionPathTemplate(),values);List<NotificationChannel> channels=new ArrayList<>();t.getChannels().forEach(n->channels.add(NotificationChannel.valueOf(n.asText())));String key="event:"+row.id+":"+recipient.userId();if(notifications.createForResolvedRecipient(row.organizationId,recipient.userId(),recipient.type(),recipient.email(),recipient.inAppEnabled(),recipient.emailEnabled(),t.getId(),row.eventType,row.aggregateType,row.aggregateId,projectId,title,body,action,key,channels,t.isMandatory()))count++;}complete(row.id,count,"PROCESSED",null);}catch(Exception ex){throw new IllegalStateException(ex);}}
    private boolean claim(OutboxRow row){Instant now=clock.instant();Instant leaseUntil=now.plus(CLAIM_LEASE);int inserted=jdbc.update("INSERT INTO client_onboarding.notification_event_receipts(id,organization_id,outbox_event_id,status,notifications_created,attempt_count,next_attempt_at,processed_at,last_error) VALUES(?,?,?,'PROCESSING',0,1,?,NULL,NULL) ON CONFLICT(outbox_event_id) DO NOTHING",UUID.randomUUID(),row.organizationId,row.id,leaseUntil);if(inserted==1)return true;return jdbc.update("UPDATE client_onboarding.notification_event_receipts SET status='PROCESSING',attempt_count=attempt_count+1,next_attempt_at=?,processed_at=NULL,last_error=NULL WHERE organization_id=? AND outbox_event_id=? AND status='FAILED' AND next_attempt_at<=? AND attempt_count<?",leaseUntil,row.organizationId,row.id,now,MAX_ROUTING_ATTEMPTS)==1;}
    private void complete(UUID eventId,int count,String status,String error){jdbc.update("UPDATE client_onboarding.notification_event_receipts SET status=?,notifications_created=?,processed_at=?,last_error=? WHERE outbox_event_id=?",status,count,clock.instant(),error,eventId);}
    private void fail(UUID eventId,RuntimeException ex){Instant now=clock.instant();jdbc.update("UPDATE client_onboarding.notification_event_receipts SET status=CASE WHEN attempt_count>=? THEN 'DEAD' ELSE 'FAILED' END,next_attempt_at=?,processed_at=CASE WHEN attempt_count>=? THEN ? ELSE NULL END,last_error=? WHERE outbox_event_id=?",MAX_ROUTING_ATTEMPTS,now.plusSeconds(60),MAX_ROUTING_ATTEMPTS,now,truncate(ex.getMessage()),eventId);}
    private void recoverStaleClaims(){jdbc.update("UPDATE client_onboarding.notification_event_receipts SET status=CASE WHEN attempt_count>=? THEN 'DEAD' ELSE 'FAILED' END,next_attempt_at=CURRENT_TIMESTAMP,processed_at=CASE WHEN attempt_count>=? THEN CURRENT_TIMESTAMP ELSE NULL END,last_error='Recovered stale notification routing claim' WHERE status='PROCESSING' AND next_attempt_at<=CURRENT_TIMESTAMP",MAX_ROUTING_ATTEMPTS,MAX_ROUTING_ATTEMPTS);}
    private static String truncate(String s){if(s==null)return "Notification routing failed";return s.substring(0,Math.min(1000,s.length()));}private static UUID uuid(JsonNode n,String key){String v=text(n,key);try{return v==null?null:UUID.fromString(v);}catch(IllegalArgumentException ex){return null;}}private static String text(JsonNode n,String key){JsonNode v=n==null?null:n.get(key);return v==null||v.isNull()?"":v.asText();}
    private record OutboxRow(UUID id,UUID organizationId,String eventType,String aggregateType,UUID aggregateId,String payload,Instant occurredAt){}
}
