"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback,useEffect,useState } from "react";
import { ArrowLeft,ArrowRight,FileSignature,Loader2 } from "lucide-react";
import { useClientAuth } from "@/auth/client-auth-provider";
import { EmptyState } from "@/components/shared/empty-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ApiClientError } from "@/services/api-client";
import type { ClientContractSummary } from "@/types/contracts";

export default function ClientContractsPage(){const{projectId}=useParams<{projectId:string}>();const{authorizedRequest}=useClientAuth();const[items,setItems]=useState<ClientContractSummary[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await authorizedRequest<ClientContractSummary[]>(`/client-portal/projects/${projectId}/contracts?size=50`))}catch(e){setError(e instanceof ApiClientError?e.message:"Contracts could not be loaded.")}finally{setLoading(false)}},[authorizedRequest,projectId]);useEffect(()=>{void load()},[load]);return <div className="mx-auto max-w-5xl"><Button asChild variant="ghost" size="sm" className="mb-5 -ml-2"><Link href={`/portal/projects/${projectId}`}><ArrowLeft className="size-4"/>Back to project</Link></Button><header className="mb-7"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[hsl(var(--primary))]"><FileSignature className="size-4"/>Contracts</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.045em]">Review and sign project agreements</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[hsl(var(--muted-foreground))]">Sent legal content is frozen. Signing happens through the configured e-signature provider and signed documents remain securely retained.</p></header>{loading?<div className="panel grid min-h-56 place-items-center text-sm text-[hsl(var(--muted-foreground))]"><span className="flex items-center gap-2"><Loader2 className="size-4 animate-spin"/>Loading contracts…</span></div>:error?<div className="panel p-6"><p className="font-semibold">Contracts unavailable</p><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{error}</p><Button className="mt-4" variant="secondary" onClick={()=>void load()}>Try again</Button></div>:items.length===0?<EmptyState title="No contracts yet" description="Contracts sent for this project will appear here."/>:<div className="space-y-3">{items.map(c=><Link key={c.id} href={`/portal/projects/${projectId}/contracts/${c.id}`} className="panel flex items-center gap-4 p-5 hover:bg-[hsl(var(--surface-subtle)/.55)]"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{c.subject}</p><StatusBadge status={c.status}/>{c.yourSignatureRequired&&<Badge variant="warning">Your signature</Badge>}</div><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{c.expiresAt?`Expires ${date(c.expiresAt)}`:c.sentAt?`Sent ${date(c.sentAt)}`:"Prepared for this project"}</p></div><ArrowRight className="size-4 text-[hsl(var(--muted-foreground))]"/></Link>)}</div>}</div>}
function date(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(v))}
