"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback,useEffect,useState } from "react";
import { ArrowDown,ArrowLeft,ArrowUp,CheckCircle2,FileQuestion,Layers3,Loader2,LockKeyhole,Plus,Rocket,Save,Trash2 } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError } from "@/services/api-client";
import type {FormField,FormFieldType,FormTemplate,FormVersion} from "@/types/forms";

const fieldTypes:FormFieldType[]=["TEXT","TEXTAREA","NUMBER","EMAIL","URL","DATE","DROPDOWN","RADIO","CHECKBOX","MULTI_SELECT","FILE","BOOLEAN"];
type DraftField=FormField & {conditionText:string;optionsText:string};
export default function FormBuilder(){const{formId}=useParams<{formId:string}>();const{authorizedRequest,hasPermission}=useAuth();const canRead=hasPermission("FORM_READ")||hasPermission("FORM_MANAGE");const canManage=hasPermission("FORM_MANAGE");const[form,setForm]=useState<FormTemplate|null>(null);const[selected,setSelected]=useState<FormVersion|null>(null);const[draft,setDraft]=useState<DraftField[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
 const loadVersion=useCallback(async(id:string)=>{const v=await authorizedRequest<FormVersion>(`/forms/versions/${id}`);setSelected(v);setDraft(v.fields.map(toDraft))},[authorizedRequest]);const load=useCallback(async()=>{setLoading(true);setError(null);try{const f=await authorizedRequest<FormTemplate>(`/forms/${formId}`);setForm(f);const choice=[...f.versions].sort((a,b)=>a.status==="DRAFT"?-1:b.versionNumber-a.versionNumber)[0];if(choice)await loadVersion(choice.id)}catch(e){setError(message(e,"Form could not be loaded."))}finally{setLoading(false)}},[authorizedRequest,formId,loadVersion]);useEffect(()=>{if(canRead)void load()},[canRead,load]);
 async function refresh(){if(!form)return;setForm(await authorizedRequest<FormTemplate>(`/forms/${form.id}`))}async function save(){if(!selected||selected.status!=="DRAFT")return;setBusy(true);setError(null);setNotice(null);try{const fields=draft.map((f,i)=>({fieldKey:f.fieldKey,label:f.label,helpText:f.helpText,fieldType:f.fieldType,displayOrder:i,required:f.required,conditionExpression:parseJson(f.conditionText),configuration:configuration(f)}));const v=await authorizedRequest<FormVersion>(`/forms/versions/${selected.id}`,{method:"PUT",body:JSON.stringify({version:selected.version,changeNote:selected.changeNote,fields})});setSelected(v);setDraft(v.fields.map(toDraft));setNotice("Draft saved and validated.");await refresh()}catch(e){setError(message(e,"Form draft could not be saved."))}finally{setBusy(false)}}async function publish(){if(!selected||selected.status!=="DRAFT"||!confirm("Publish this form version? Its field definition becomes immutable."))return;setBusy(true);setError(null);try{const v=await authorizedRequest<FormVersion>(`/forms/versions/${selected.id}/publish`,{method:"POST",body:JSON.stringify({version:selected.version})});setSelected(v);setDraft(v.fields.map(toDraft));setNotice(`Version ${v.versionNumber} published.`);await refresh()}catch(e){setError(message(e,"Form version could not be published."))}finally{setBusy(false)}}async function newVersion(){if(!form)return;setBusy(true);setError(null);try{const v=await authorizedRequest<FormVersion>(`/forms/${form.id}/versions`,{method:"POST",body:JSON.stringify({changeNote:"New revision"})});setSelected(v);setDraft(v.fields.map(toDraft));await refresh()}catch(e){setError(message(e,"A new form version could not be created."))}finally{setBusy(false)}}
 const hasDraft=form?.versions.some(v=>v.status==="DRAFT")??false;if(!canRead)return <PermissionState/>;if(loading)return <Loading/>;if(!form)return <FormMessage>{error??"Form not found."}</FormMessage>;return <><Button asChild variant="ghost" className="mb-5 -ml-2"><Link href="/app/forms"><ArrowLeft className="size-4"/>Back to forms</Link></Button><PageHeading eyebrow="Questionnaire builder" title={form.name} description={form.description||"Build a reusable questionnaire with deterministic conditional visibility and immutable published versions."} actions={<div className="flex gap-2">{canManage&&!hasDraft&&form.versions.some(v=>v.status==="PUBLISHED")&&<Button variant="secondary" onClick={()=>void newVersion()} disabled={busy}><Layers3 className="size-4"/>New version</Button>}{canManage&&selected?.status==="DRAFT"&&<><Button variant="secondary" onClick={()=>void save()} disabled={busy}><Save className="size-4"/>Save draft</Button><Button onClick={()=>void publish()} disabled={busy||draft.length===0}><Rocket className="size-4"/>Publish</Button></>}</div>}/>{(error||notice)&&<div className="mb-5">{error?<FormMessage>{error}</FormMessage>:<div className="rounded-xl bg-[hsl(var(--success-soft))] px-4 py-3 text-sm text-[hsl(var(--success))]"><CheckCircle2 className="mr-2 inline size-4"/>{notice}</div>}</div>}
 <div className="grid gap-6 xl:grid-cols-[17rem_minmax(0,1fr)]"><aside className="panel h-fit overflow-hidden xl:sticky xl:top-8"><div className="border-b p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">Versions</p></div><div className="p-2">{[...form.versions].sort((a,b)=>b.versionNumber-a.versionNumber).map(v=><button key={v.id} onClick={()=>void loadVersion(v.id)} className={`w-full rounded-xl px-3 py-3 text-left ${selected?.id===v.id?"bg-[hsl(var(--ink))] text-white":"hover:bg-[hsl(var(--surface-subtle))]"}`}><div className="flex items-center justify-between"><span className="text-sm font-semibold">Version {v.versionNumber}</span><Badge variant={v.status==="PUBLISHED"?"success":"warning"}>{v.status}</Badge></div><p className={`mt-1 text-xs ${selected?.id===v.id?"text-white/65":"text-[hsl(var(--muted-foreground))]"}`}>{v.fieldCount} fields</p></button>)}</div></aside>
 <main className="min-w-0"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b bg-[hsl(var(--surface-subtle)/.5)] p-5"><div><div className="flex items-center gap-2"><h2 className="font-semibold">Version {selected?.versionNumber}</h2>{selected&&<StatusBadge status={selected.status}/>} {selected?.status==="PUBLISHED"&&<Badge variant="neutral"><LockKeyhole className="mr-1 size-3"/>Immutable</Badge>}</div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Conditions may reference earlier fields only, preventing cyclic visibility rules.</p></div><span className="text-sm font-semibold">{draft.length} fields</span></div>{selected?.status==="DRAFT"?<div className="space-y-4 p-4 sm:p-5">{draft.length===0&&<div className="rounded-2xl border border-dashed p-8 text-center"><FileQuestion className="mx-auto size-7 text-[hsl(var(--muted-foreground))]"/><p className="mt-3 font-semibold">Add the first question</p></div>}{draft.map((field,i)=><FieldEditor key={field.id} field={field} index={i} earlier={draft.slice(0,i)} onChange={v=>setDraft(a=>a.map((x,n)=>n===i?v:x))} onRemove={()=>setDraft(a=>a.filter((_,n)=>n!==i))} onMove={d=>setDraft(a=>move(a,i,d))}/>)}<Button variant="secondary" className="w-full border-dashed" onClick={()=>setDraft(a=>[...a,newField(a.length)])}><Plus className="size-4"/>Add field</Button><p className="rounded-xl bg-[hsl(var(--info-soft))] p-4 text-xs leading-5">FILE fields use the secure Asset Management pipeline: direct private upload, content/signature policy checks, malware scanning and opaque clean-version references.</p></div>:<Published fields={draft}/>}</section></main></div></>}
function FieldEditor({field,index,earlier,onChange,onRemove,onMove}:{field:DraftField;index:number;earlier:DraftField[];onChange:(v:DraftField)=>void;onRemove:()=>void;onMove:(d:-1|1)=>void}){const set=<K extends keyof DraftField>(k:K,v:DraftField[K])=>onChange({...field,[k]:v});const choices=["DROPDOWN","RADIO","MULTI_SELECT"].includes(field.fieldType);return <article className="rounded-2xl border p-4 sm:p-5"><div className="mb-4 flex gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-[hsl(var(--ink))] text-xs font-bold text-white">{index+1}</div><Input value={field.label} onChange={e=>set("label",e.target.value)} maxLength={220} className="font-semibold"/><div className="flex"><Button variant="ghost" size="icon" onClick={()=>onMove(-1)} disabled={index===0}><ArrowUp className="size-4"/></Button><Button variant="ghost" size="icon" onClick={()=>onMove(1)}><ArrowDown className="size-4"/></Button><Button variant="ghost" size="icon" onClick={onRemove}><Trash2 className="size-4"/></Button></div></div><div className="grid gap-4 md:grid-cols-3"><F label="Field key"><Input value={field.fieldKey} onChange={e=>set("fieldKey",e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,"_"))}/></F><F label="Type"><Select value={field.fieldType} onChange={e=>set("fieldType",e.target.value as FormFieldType)}>{fieldTypes.map(t=><option key={t}>{t}</option>)}</Select></F><F label="Required"><Select value={field.required?"yes":"no"} onChange={e=>set("required",e.target.value==="yes")} disabled={field.fieldType==="FILE"}><option value="no">Optional</option><option value="yes">Required</option></Select></F></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><F label="Help text"><Textarea rows={3} value={field.helpText??""} onChange={e=>set("helpText",e.target.value||null)}/></F><F label="Visibility condition"><Textarea rows={3} className="font-mono text-xs" value={field.conditionText} onChange={e=>set("conditionText",e.target.value)}/><p className="mt-1 text-[11px] text-[hsl(var(--muted-foreground))]">Earlier keys: {earlier.map(x=>x.fieldKey).join(", ")||"none"}</p></F></div>{choices&&<div className="mt-4"><F label="Options (one per line)"><Textarea rows={4} value={field.optionsText} onChange={e=>set("optionsText",e.target.value)}/></F></div>}</article>}
function Published({fields}:{fields:DraftField[]}){return <div className="divide-y">{fields.map((f,i)=><div className="p-5" key={f.id}><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{i+1}. {f.label}</span><Badge variant="neutral">{f.fieldType}</Badge>{f.required&&<Badge variant="info">Required</Badge>}</div>{f.helpText&&<p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{f.helpText}</p>}</div>)}</div>}
function F({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function toDraft(f:FormField):DraftField{return{...f,conditionText:JSON.stringify(f.conditionExpression??{op:"ALWAYS"}),optionsText:Array.isArray(f.configuration?.options)?(f.configuration.options as string[]).join("\n"):""}}
function newField(i:number):DraftField{return{id:`draft-${crypto.randomUUID()}`,fieldKey:`FIELD_${i+1}`,label:"New question",helpText:null,fieldType:"TEXT",displayOrder:i,required:false,conditionExpression:{op:"ALWAYS"},configuration:{},conditionText:'{"op":"ALWAYS"}',optionsText:""}}
function configuration(f:DraftField){const base={...f.configuration};if(["DROPDOWN","RADIO","MULTI_SELECT"].includes(f.fieldType))return{...base,options:f.optionsText.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)};delete (base as {options?:unknown}).options;return base}
function parseJson(value:string){try{return JSON.parse(value)}catch{throw new Error("Visibility condition must be valid JSON.")}}
function move<T>(a:T[],i:number,d:-1|1){const j=i+d;if(j<0||j>=a.length)return a;const n=[...a];[n[i],n[j]]=[n[j],n[i]];return n}
function Loading(){return <div className="grid min-h-72 place-items-center text-sm text-[hsl(var(--muted-foreground))]"><span className="flex items-center gap-2"><Loader2 className="size-4 animate-spin"/>Loading form builder…</span></div>}
function message(e:unknown,f:string){return e instanceof ApiClientError?e.message:e instanceof Error?e.message:f}
