"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowLeft,CheckCircle2,ClipboardCheck,Loader2,LockKeyhole,RefreshCw,Rocket,RotateCcw,ShieldCheck } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError } from "@/services/api-client";
import type { FinalReviewChecklist,ProjectActivation } from "@/types/review";

export default function FinalReviewPage(){
 const params=useParams<{projectId:string}>();const{authorizedRequest,hasPermission}=useAuth();const canReview=hasPermission('ONBOARDING_REVIEW');const canApprove=hasPermission('ONBOARDING_APPROVE');const canActivate=hasPermission('PROJECT_ACTIVATE');
 const[data,setData]=useState<FinalReviewChecklist|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[selected,setSelected]=useState<string[]>([]);const[reason,setReason]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError(null);try{if(canReview||canApprove||canActivate)setData(await authorizedRequest<FinalReviewChecklist>(`/projects/${params.projectId}/review`))}catch(e){setError(msg(e,'Final review could not be loaded.'))}finally{setLoading(false)}},[authorizedRequest,canActivate,canApprove,canReview,params.projectId]);useEffect(()=>{void load()},[load]);
 const revisable=useMemo(()=>data?.requirements.filter(r=>r.revisable)??[],[data]);const latest=data?.history[0];const reviewStarted=latest?.action==='REVIEW_STARTED'&&latest.onboardingVersion===data?.onboardingVersion;
 async function command(path:string,body:unknown,success:string){if(!data)return;setBusy(true);setError(null);setNotice(null);try{setData(await authorizedRequest<FinalReviewChecklist>(path,{method:'POST',body:JSON.stringify(body)}));setNotice(success);setSelected([]);setReason('')}catch(e){setError(msg(e,'The review action could not be completed.'))}finally{setBusy(false)}}async function activate(){if(!data||!confirm('Activate this READY project? This begins delivery and is recorded in the audit log.'))return;setBusy(true);setError(null);try{const result=await authorizedRequest<ProjectActivation>(`/projects/${params.projectId}/activate`,{method:'POST',body:JSON.stringify({version:data.projectVersion})});setData({...data,projectStatus:result.status,projectVersion:result.version});setNotice('Project activated.');}catch(e){setError(msg(e,'Project could not be activated.'))}finally{setBusy(false)}}
 if(!canReview&&!canApprove&&!canActivate)return <PermissionState/>;if(loading)return <div className="panel flex min-h-72 items-center justify-center text-sm text-[hsl(var(--muted-foreground))]"><Loader2 className="mr-2 size-4 animate-spin"/>Loading final review…</div>;if(!data)return <div className="space-y-5"><Button asChild variant="ghost"><Link href={`/app/projects/${params.projectId}`}><ArrowLeft className="size-4"/>Back to project</Link></Button><FormMessage>{error??'Final review is unavailable.'}</FormMessage></div>;
 return <><Button asChild variant="ghost" className="mb-5 -ml-2"><Link href={`/app/projects/${params.projectId}`}><ArrowLeft className="size-4"/>Back to project</Link></Button><PageHeading eyebrow="Final review" title="Readiness is evidence, not a button" description="The server recomputes every blocking requirement before approval. Approval completes onboarding and moves the project to READY; activation remains a separate privileged action." actions={<Button variant="secondary" size="icon" onClick={()=>void load()} aria-label="Refresh review"><RefreshCw className="size-4"/></Button>}/>
 {(error||notice)&&<div className="mb-5">{error?<FormMessage>{error}</FormMessage>:<div className="rounded-xl border border-[hsl(var(--success)/.22)] bg-[hsl(var(--success-soft))] px-4 py-3 text-sm text-[hsl(var(--success))]">{notice}</div>}</div>}
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Onboarding" value={data.onboardingStatus.replaceAll('_',' ')} icon={ClipboardCheck}/><Metric label="Blocking complete" value={`${data.blockingCompleted}/${data.blockingTotal}`} icon={ShieldCheck}/><Metric label="Required complete" value={`${data.requiredCompleted}/${data.requiredTotal}`} icon={CheckCircle2}/><Metric label="Project" value={data.projectStatus.replaceAll('_',' ')} icon={Rocket}/></div>
 {data.projectStatus==='READY'&&<section className="mb-6 overflow-hidden rounded-2xl border border-[hsl(var(--success)/.28)] bg-[hsl(var(--success-soft)/.65)] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[hsl(var(--success))]">Ready for activation</p><h2 className="mt-1 text-lg font-semibold">Onboarding is approved and complete.</h2><p className="mt-2 max-w-2xl text-sm text-[hsl(var(--muted-foreground))]">Activation is intentionally separate from final review and requires PROJECT_ACTIVATE.</p></div>{canActivate?<Button disabled={busy} onClick={()=>void activate()}><Rocket className="size-4"/>Activate project</Button>:<Badge variant="neutral">Activation permission required</Badge>}</div></section>}
 {data.projectStatus==='ACTIVE'&&<section className="mb-6 rounded-2xl border border-[hsl(var(--success)/.25)] bg-[hsl(var(--success-soft))] p-5"><p className="flex items-center gap-2 font-semibold text-[hsl(var(--success))]"><CheckCircle2 className="size-5"/>Project is active</p><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">The audited READY → ACTIVE transition is complete.</p></section>}
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1.18fr)_minmax(22rem,.82fr)]"><section className="panel overflow-hidden"><div className="border-b p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Readiness checklist</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Only snapshotted, applicable workflow requirements participate.</p></div><Badge variant={data.ready?'success':'warning'}>{data.ready?'All blockers complete':'Blocking work remains'}</Badge></div></div><div className="divide-y">{data.requirements.map(r=><div key={r.stepId} className="grid gap-3 p-5 sm:grid-cols-[2rem_minmax(0,1fr)_auto] sm:items-start"><div className={`mt-0.5 grid size-8 place-items-center rounded-lg ${r.satisfied?'bg-[hsl(var(--success-soft))] text-[hsl(var(--success))]':'bg-[hsl(var(--surface-subtle))] text-[hsl(var(--muted-foreground))]'}`}>{r.satisfied?<CheckCircle2 className="size-4"/>:<LockKeyhole className="size-4"/>}</div><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{r.name}</p><Badge variant="neutral">{r.stepType}</Badge>{r.blocking&&<Badge variant="danger">Blocking</Badge>}{r.required&&<Badge variant="info">Required</Badge>}</div><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">{r.clientVisible?'Client-visible requirement':'Internal requirement'} · {r.revisable?'Can be returned for revision':'Final/non-reopenable fact'}</p></div><StatusBadge status={r.status}/></div>)}</div></section>
 <aside className="space-y-6"><section className="panel p-5"><h2 className="font-semibold">Reviewer actions</h2><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Actions use optimistic versions and re-check readiness inside the transaction.</p><div className="mt-4 space-y-3">{canReview&&data.onboardingStatus==='AWAITING_INTERNAL_REVIEW'&&!reviewStarted&&<Button className="w-full" variant="secondary" disabled={busy} onClick={()=>void command(`/onboardings/${data.onboardingId}/review`,{version:data.onboardingVersion},'Review started and recorded.')}><ClipboardCheck className="size-4"/>Start review</Button>}{canApprove&&data.canApprove&&<Button className="w-full" disabled={busy} onClick={()=>void command(`/onboardings/${data.onboardingId}/approve`,{version:data.onboardingVersion},'Onboarding approved. Project moved to READY.')}><CheckCircle2 className="size-4"/>Approve onboarding</Button>}{data.onboardingStatus!=='AWAITING_INTERNAL_REVIEW'&&data.projectStatus!=='READY'&&data.projectStatus!=='ACTIVE'&&<p className="rounded-xl bg-[hsl(var(--surface-subtle))] p-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Review actions unlock automatically only after every blocking requirement is complete.</p>}</div></section>
 {canReview&&data.onboardingStatus==='AWAITING_INTERNAL_REVIEW'&&revisable.length>0&&<section className="panel p-5"><h2 className="font-semibold">Request revision</h2><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Select only the requirements that genuinely need rework. Payment and signed-contract facts cannot be rewritten from final review.</p><div className="mt-4 max-h-56 space-y-2 overflow-auto">{revisable.map(r=><label key={r.stepId} className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" className="mt-0.5 size-4" checked={selected.includes(r.stepId)} onChange={e=>setSelected(cur=>e.target.checked?[...cur,r.stepId]:cur.filter(id=>id!==r.stepId))}/><span>{r.name}<span className="mt-0.5 block text-xs text-[hsl(var(--muted-foreground))]">{r.stepType}{r.blocking?' · blocking':''}</span></span></label>)}</div><div className="mt-4 space-y-2"><Label htmlFor="revision-reason">Reason</Label><Textarea id="revision-reason" rows={4} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain exactly what needs to change and how the client or team can recover."/></div><Button className="mt-4 w-full" variant="secondary" disabled={busy||selected.length===0||!reason.trim()} onClick={()=>void command(`/onboardings/${data.onboardingId}/request-revision`,{version:data.onboardingVersion,reason,stepIds:selected},'Revision requested and selected requirements reopened.')}><RotateCcw className="size-4"/>Request revision</Button></section>}
 <section className="panel overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Review history</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Append-only evidence</p></div>{data.history.length===0?<p className="p-5 text-sm text-[hsl(var(--muted-foreground))]">No review action has been recorded yet.</p>:<div className="divide-y">{data.history.map(h=><div key={h.id} className="p-4"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold">{h.action.replaceAll('_',' ')}</p><span className="text-[11px] text-[hsl(var(--muted-foreground))]">{format(h.createdAt)}</span></div>{h.reason&&<p className="mt-2 text-xs leading-5 text-[hsl(var(--muted-foreground))]">{h.reason}</p>}</div>)}</div>}</section></aside></div></>;
}
function Metric({label,value,icon:Icon}:{label:string;value:string;icon:typeof ClipboardCheck}){return <div className="panel p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-2 text-lg font-semibold tracking-[-.025em]">{value}</p></div><div className="grid size-10 place-items-center rounded-xl bg-[hsl(var(--surface-subtle))]"><Icon className="size-4.5"/></div></div></div>}function format(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}function msg(e:unknown,f:string){return e instanceof ApiClientError?e.message:f}
