"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { ArrowRight,FolderOpen,Loader2,RefreshCw,ShieldCheck } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { PageHeading } from "@/components/layout/page-heading";
import { EmptyState } from "@/components/shared/empty-state";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { ApiClientError } from "@/services/api-client";
import type { AssetSummary } from "@/types/assets";

export default function AssetsPage(){const{authorizedRequest,hasPermission}=useAuth();const canRead=hasPermission("ASSET_READ")||hasPermission("ASSET_REVIEW");const[items,setItems]=useState<AssetSummary[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await authorizedRequest<AssetSummary[]>("/assets?size=100"))}catch(e){setError(e instanceof ApiClientError?e.message:"Assets could not be loaded.")}finally{setLoading(false)}},[authorizedRequest]);useEffect(()=>{if(canRead)void load()},[canRead,load]);if(!canRead)return <PermissionState/>;return <><PageHeading eyebrow="Assets" title="Review files only after security checks pass" description="Project uploads are versioned, malware-scanned and policy-validated before they can reach normal review or download paths." actions={<Button variant="secondary" size="icon" onClick={()=>void load()} aria-label="Refresh assets"><RefreshCw className="size-4"/></Button>}/>{error&&<div className="mb-5 rounded-xl border p-4 text-sm">{error}</div>}{loading?<div className="panel grid min-h-64 place-items-center text-sm text-[hsl(var(--muted-foreground))]"><span className="flex items-center gap-2"><Loader2 className="size-4 animate-spin"/>Loading assets…</span></div>:items.length===0?<EmptyState title="No assets yet" description="Secure client uploads will appear here after onboarding requests are created."/>:<div className="grid gap-4 lg:grid-cols-2">{items.map(a=><Link key={a.assetId} href={`/app/assets/${a.assetId}`} className="panel flex items-center gap-4 p-5 hover:bg-[hsl(var(--surface-subtle)/.55)]"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[hsl(var(--primary-soft))] text-[hsl(var(--primary))]">{a.status==="APPROVED"?<ShieldCheck className="size-5"/>:<FolderOpen className="size-5"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{a.requirementName}</p><StatusBadge status={a.status}/></div><p className="mt-1 truncate text-sm text-[hsl(var(--muted-foreground))]">{a.currentFilename||"No clean file available yet"}</p><p className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">Updated {date(a.updatedAt)}</p></div><ArrowRight className="size-4 text-[hsl(var(--muted-foreground))]"/></Link>)}</div>}</>}
function date(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v))}
