"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowLeft,CheckCircle2,Loader2,Save,Send } from "lucide-react";
import { useClientAuth } from "@/auth/client-auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError } from "@/services/api-client";
import { AssetUploadPanel } from "@/features/assets/asset-upload-panel";
import type {ClientFormStep,FormField} from "@/types/forms";

type Answers=Record<string,unknown>;
export default function ClientQuestionnaire(){const{projectId,stepId}=useParams<{projectId:string;stepId:string}>();const{authorizedRequest}=useClientAuth();const[data,setData]=useState<ClientFormStep|null>(null);const[answers,setAnswers]=useState<Answers>({});const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<"save"|"submit"|null>(null);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const v=await authorizedRequest<ClientFormStep>(`/client-portal/projects/${projectId}/forms/${stepId}`);setData(v);setAnswers(v.currentSubmission?.answers??{})}catch(e){setError(msg(e,"Questionnaire could not be loaded."))}finally{setLoading(false)}},[authorizedRequest,projectId,stepId]);useEffect(()=>{void load()},[load]);const visible=useMemo(()=>data?.fields.filter(f=>evaluate(f.conditionExpression,answers))??[],[answers,data]);const editable=data&&["AVAILABLE","IN_PROGRESS","NEEDS_REVISION"].includes(data.stepStatus)&&(!data.currentSubmission||data.currentSubmission.status==="DRAFT");
 async function save(){if(!data||!editable)return;setBusy("save");setError(null);setNotice(null);try{const v=await authorizedRequest<ClientFormStep>(`/client-portal/projects/${projectId}/forms/${stepId}/draft`,{method:"PUT",body:JSON.stringify({version:data.currentSubmission?.version??0,answers})});setData(v);setAnswers(v.currentSubmission?.answers??answers);setNotice("Draft saved. You can safely return later.")}catch(e){setError(msg(e,"Draft could not be saved."))}finally{setBusy(null)}}async function submit(){if(!data||!editable)return;if(!data.currentSubmission){setError("Save your draft before submitting.");return}if(!confirm("Submit this questionnaire to your project team?"))return;setBusy("submit");setError(null);setNotice(null);try{const v=await authorizedRequest<ClientFormStep>(`/client-portal/projects/${projectId}/forms/${stepId}/submit`,{method:"POST",body:JSON.stringify({version:data.currentSubmission.version})});setData(v);setAnswers(v.currentSubmission?.answers??answers);setNotice(v.requiresReview?"Submitted. Your project team will review your answers.":"Submitted and completed.")}catch(e){setError(msg(e,"Questionnaire could not be submitted."))}finally{setBusy(null)}}
 if(loading)return <Loading/>;if(error&&!data)return <div className="panel p-7"><FormMessage>{error}</FormMessage><Button asChild variant="secondary" className="mt-5"><Link href={`/portal/projects/${projectId}`}><ArrowLeft className="size-4"/>Back to project</Link></Button></div>;if(!data)return null;return <div className="mx-auto max-w-4xl"><Button asChild variant="ghost" className="mb-5 -ml-2"><Link href={`/portal/projects/${projectId}`}><ArrowLeft className="size-4"/>Back to project</Link></Button><header className="mb-6"><div className="flex flex-wrap items-center gap-2"><Badge variant="neutral">{data.formName} v{data.formVersionNumber}</Badge><StatusBadge status={data.stepStatus}/></div><h1 className="mt-3 text-3xl font-semibold tracking-[-.045em]">{data.stepName}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[hsl(var(--muted-foreground))]">{data.stepDescription||"Complete the information below so our team can prepare your project."}</p>{data.currentSubmission?.revisionNote&&<div className="mt-4 rounded-2xl border border-[hsl(var(--warning)/.25)] bg-[hsl(var(--warning-soft))] p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[hsl(var(--warning))]">Revision requested</p><p className="mt-2 text-sm">{data.currentSubmission.revisionNote}</p></div>}</header>{(error||notice)&&<div className="mb-5">{error?<FormMessage>{error}</FormMessage>:<div className="rounded-xl bg-[hsl(var(--success-soft))] px-4 py-3 text-sm text-[hsl(var(--success))]"><CheckCircle2 className="mr-2 inline size-4"/>{notice}</div>}</div>}
 <section className="panel overflow-hidden"><div className="border-b bg-[hsl(var(--surface-subtle)/.45)] px-5 py-4 sm:px-7"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">Your information</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Only fields relevant to your answers are shown.</p></div>{data.currentSubmission&&<Badge variant="neutral">Attempt {data.currentSubmission.submissionNumber}</Badge>}</div></div><div className="space-y-7 p-5 sm:p-7">{visible.map(field=><Question key={field.id} projectId={projectId} stepId={stepId} field={field} value={answers[field.fieldKey]} disabled={!editable||busy!==null} onChange={value=>setAnswers(a=>({...a,[field.fieldKey]:value}))}/>)}{visible.length===0&&<p className="text-sm text-[hsl(var(--muted-foreground))]">No questions are currently applicable.</p>}</div>{editable&&<div className="flex flex-col-reverse gap-3 border-t bg-[hsl(var(--surface-subtle)/.35)] p-5 sm:flex-row sm:justify-end sm:px-7"><Button variant="secondary" disabled={busy!==null} onClick={()=>void save()}>{busy==="save"?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Save draft</Button><Button disabled={busy!==null} onClick={()=>void submit()}>{busy==="submit"?<Loader2 className="size-4 animate-spin"/>:<Send className="size-4"/>}Submit for {data.requiresReview?"review":"completion"}</Button></div>}</section><div className="mt-5 rounded-2xl bg-[hsl(var(--surface-subtle))] p-4 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Previous submissions remain traceable after revision. Submitted answers cannot be silently changed; a revision creates a new response version.</div></div>}
function Question({projectId,stepId,field,value,disabled,onChange}:{projectId:string;stepId:string;field:FormField;value:unknown;disabled:boolean;onChange:(v:unknown)=>void}){const id=`field-${field.id}`;const common=<><Label htmlFor={id}>{field.label}{field.required&&<span className="ml-1 text-[hsl(var(--danger))]">*</span>}</Label>{field.helpText&&<p className="text-xs leading-5 text-[hsl(var(--muted-foreground))]">{field.helpText}</p>}</>;const opts=Array.isArray(field.configuration?.options)?field.configuration.options as string[]:[];return <div className="space-y-2.5">{common}{field.fieldType==="TEXT"&&<Input id={id} value={String(value??"")} disabled={disabled} onChange={e=>onChange(e.target.value)}/>} {field.fieldType==="TEXTAREA"&&<Textarea id={id} rows={5} value={String(value??"")} disabled={disabled} onChange={e=>onChange(e.target.value)}/>} {field.fieldType==="NUMBER"&&<Input id={id} type="number" value={value==null?"":String(value)} disabled={disabled} onChange={e=>onChange(e.target.value===""?null:Number(e.target.value))}/>} {field.fieldType==="EMAIL"&&<Input id={id} type="email" value={String(value??"")} disabled={disabled} onChange={e=>onChange(e.target.value)}/>} {field.fieldType==="URL"&&<Input id={id} type="url" value={String(value??"")} disabled={disabled} onChange={e=>onChange(e.target.value)}/>} {field.fieldType==="DATE"&&<Input id={id} type="date" value={String(value??"")} disabled={disabled} onChange={e=>onChange(e.target.value)}/>} {["DROPDOWN","RADIO"].includes(field.fieldType)&&<Select id={id} value={String(value??"")} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Select an option</option>{opts.map(o=><option key={o}>{o}</option>)}</Select>} {field.fieldType==="MULTI_SELECT"&&<Select id={id} multiple className="min-h-32" value={Array.isArray(value)?value.map(String):[]} disabled={disabled} onChange={e=>onChange(Array.from(e.target.selectedOptions).map(o=>o.value))}>{opts.map(o=><option key={o}>{o}</option>)}</Select>} {["BOOLEAN","CHECKBOX"].includes(field.fieldType)&&<label className="flex items-center gap-3 rounded-xl border p-3 text-sm"><input id={id} type="checkbox" checked={Boolean(value)} disabled={disabled} onChange={e=>onChange(e.target.checked)} className="size-4"/>Yes</label>} {field.fieldType==="FILE"&&<FormFileUpload projectId={projectId} stepId={stepId} field={field} disabled={disabled} onChange={onChange}/>}</div>}
function FormFileUpload({projectId,stepId,field,disabled,onChange}:{projectId:string;stepId:string;field:FormField;disabled:boolean;onChange:(v:unknown)=>void}){const{authorizedRequest}=useClientAuth();const resource=`/client-portal/projects/${projectId}/forms/${stepId}/files/${field.id}`;return <AssetUploadPanel authorizedRequest={authorizedRequest} resourcePath={resource} compact disabled={disabled} onCleanVersion={onChange} downloadPath={(assetId,versionId)=>`${resource}/assets/${assetId}/versions/${versionId}/download-url`}/>}

function evaluate(condition:Record<string,unknown>,answers:Answers):boolean{const op=String(condition?.op??"ALWAYS").toUpperCase();if(op==="ALWAYS")return true;if(op==="ALL")return Array.isArray(condition.conditions)&&(condition.conditions as Record<string,unknown>[]).every(c=>evaluate(c,answers));if(op==="ANY")return Array.isArray(condition.conditions)&&(condition.conditions as Record<string,unknown>[]).some(c=>evaluate(c,answers));if(op==="NOT")return !evaluate((condition.condition??{}) as Record<string,unknown>,answers);const key=String(condition.field??"").toUpperCase();const actual=answers[key];if(op==="EXISTS")return has(actual);if(op==="NOT_EXISTS")return !has(actual);if(op==="IS_TRUE")return actual===true;if(op==="IS_FALSE")return actual!==true;const eq=(a:unknown,b:unknown)=>String(a??"").trim().toUpperCase()===String(b??"").trim().toUpperCase();if(op==="EQ")return Array.isArray(actual)?actual.some(a=>eq(a,condition.value)):eq(actual,condition.value);if(op==="NEQ")return !(Array.isArray(actual)?actual.some(a=>eq(a,condition.value)):eq(actual,condition.value));const values=Array.isArray(condition.values)?condition.values:[];const inside=Array.isArray(actual)?actual.some(a=>values.some(v=>eq(a,v))):values.some(v=>eq(actual,v));return op==="IN"?inside:op==="NOT_IN"?!inside:true}
function has(v:unknown){return !(v==null||v===""||(Array.isArray(v)&&v.length===0))}function Loading(){return <div className="grid min-h-80 place-items-center text-sm text-[hsl(var(--muted-foreground))]"><span className="flex items-center gap-2"><Loader2 className="size-4 animate-spin"/>Loading questionnaire…</span></div>}function msg(e:unknown,f:string){return e instanceof ApiClientError?e.message:f}
