"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { Bell,CheckCheck,Loader2,Mail,RefreshCw,Settings2 } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { EmptyState } from "@/components/shared/empty-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ApiClientError } from "@/services/api-client";
import type { NotificationDelivery,NotificationItem,NotificationPreferences,NotificationTemplate } from "@/types/notifications";
export default function NotificationsPage(){const{authorizedRequest,hasPermission}=useAuth();const canManage=hasPermission("NOTIFICATION_MANAGE");const[items,setItems]=useState<NotificationItem[]>([]);const[prefs,setPrefs]=useState<NotificationPreferences|null>(null);const[templates,setTemplates]=useState<NotificationTemplate[]>([]);const[deliveries,setDeliveries]=useState<NotificationDelivery[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const base=await Promise.all([authorizedRequest<NotificationItem[]>("/notifications?size=100"),authorizedRequest<NotificationPreferences>("/notifications/preferences")]);setItems(base[0]);setPrefs(base[1]);if(canManage){const[a,b]=await Promise.all([authorizedRequest<NotificationTemplate[]>("/notification-templates?size=100"),authorizedRequest<NotificationDelivery[]>("/notification-deliveries?size=100")]);setTemplates(a);setDeliveries(b)}}catch(e){setError(msg(e,"Notifications could not be loaded."))}finally{setLoading(false)}},[authorizedRequest,canManage]);useEffect(()=>{void load()},[load]);const unread=items.filter(i=>!i.readAt).length;const failed=deliveries.filter(d=>d.status==='FAILED'||d.status==='DEAD').length;
 async function readOne(item:NotificationItem){if(item.readAt)return;await authorizedRequest(`/notifications/${item.id}/read`,{method:"POST"});setItems(cur=>cur.map(v=>v.id===item.id?{...v,readAt:new Date().toISOString()}:v))}async function readAll(){await authorizedRequest('/notifications/read-all',{method:'POST'});setItems(cur=>cur.map(v=>({...v,readAt:v.readAt??new Date().toISOString()})))}async function updatePrefs(key:keyof NotificationPreferences){if(!prefs)return;const next={...prefs,[key]:!prefs[key]};setPrefs(await authorizedRequest<NotificationPreferences>('/notifications/preferences',{method:'PUT',body:JSON.stringify(next)}))}
 return <><PageHeading eyebrow="Notifications" title="A calm, traceable notification center" description="In-app and email delivery remain separate from business state so provider failures cannot corrupt onboarding." actions={<div className="flex gap-2"><Button variant="secondary" size="icon" onClick={()=>void load()} aria-label="Refresh notifications"><RefreshCw className="size-4"/></Button>{unread>0&&<Button variant="secondary" onClick={()=>void readAll()}><CheckCheck className="size-4"/>Mark all read</Button>}</div>}/>{error&&<div className="mb-5"><FormMessage>{error}</FormMessage></div>}
 <div className="mb-6 grid gap-4 sm:grid-cols-3"><Metric label="Unread" value={unread} icon={Bell}/><Metric label="Email failures" value={failed} icon={Mail}/><Metric label="Active templates" value={templates.filter(t=>t.status==='ACTIVE').length} icon={Settings2}/></div>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(20rem,.8fr)]"><section className="panel overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Inbox</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Only in-app deliveries allowed by your preferences appear here.</p></div>{loading?<Loading/>:items.length===0?<EmptyState title="You are all caught up" description="Transactional project events will appear here when they need your attention."/>:<div className="divide-y">{items.map(item=><button type="button" key={item.id} onClick={()=>void readOne(item)} className="block w-full p-5 text-left hover:bg-[hsl(var(--surface-subtle)/.55)]"><div className="flex items-start gap-3"><span className={`mt-1 size-2 rounded-full ${item.readAt?'bg-[hsl(var(--border))]':'bg-[hsl(var(--primary))]'}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.title}</p><Badge variant="neutral">{item.eventType}</Badge></div><p className="mt-1 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{item.body}</p><p className="mt-2 text-[11px] text-[hsl(var(--muted-foreground))]">{format(item.createdAt)}</p>{item.actionUrl&&<Link href={item.actionUrl} onClick={e=>e.stopPropagation()} className="mt-2 inline-block text-xs font-semibold text-[hsl(var(--primary))]">Open related work</Link>}</div></div></button>)}</div>}</section>
 <aside className="space-y-6"><section className="panel p-5"><h2 className="font-semibold">Delivery preferences</h2><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Mandatory security/transactional messages may remain enabled by policy.</p>{prefs&&<div className="mt-4 space-y-3"><Toggle label="In-app" value={prefs.inAppEnabled} onClick={()=>void updatePrefs('inAppEnabled')}/><Toggle label="Email" value={prefs.emailEnabled} onClick={()=>void updatePrefs('emailEnabled')}/></div>}</section>{canManage&&<><section className="panel overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Templates</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Allowlisted variables and safe application links only.</p></div><div className="divide-y">{templates.slice(0,10).map(t=><div key={t.id} className="p-4"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold">{t.name}</p><StatusBadge status={t.status}/></div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{t.eventType} · {t.channels.join(' + ')}</p></div>)}</div></section><section className="panel overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Delivery health</h2></div><div className="divide-y">{deliveries.slice(0,10).map(d=><div key={d.id} className="flex items-center justify-between gap-3 p-4"><div><p className="text-xs font-medium">{d.channel}</p><p className="mt-1 text-[11px] text-[hsl(var(--muted-foreground))]">Attempt {d.attemptCount}</p></div><StatusBadge status={d.status}/></div>)}</div></section></>}</aside></div></>}
function Toggle({label,value,onClick}:{label:string;value:boolean;onClick:()=>void}){return <div className="flex items-center justify-between rounded-xl border p-3"><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-[hsl(var(--muted-foreground))]">{value?'Enabled':'Suppressed'}</p></div><Button size="sm" variant={value?'default':'secondary'} onClick={onClick}>{value?'On':'Off'}</Button></div>}function Metric({label,value,icon:Icon}:{label:string;value:number;icon:typeof Bell}){return <div className="panel p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">{label}</p><p className="mt-2 text-3xl font-semibold tracking-[-.04em]">{value}</p></div><div className="grid size-10 place-items-center rounded-xl bg-[hsl(var(--surface-subtle))]"><Icon className="size-4.5"/></div></div></div>}function Loading(){return <div className="flex items-center justify-center py-14 text-sm text-[hsl(var(--muted-foreground))]"><Loader2 className="mr-2 size-4 animate-spin"/>Loading notifications…</div>}function format(v:string){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}function msg(e:unknown,f:string){return e instanceof ApiClientError?e.message:f}
