package com.brainserve.onboarding.contracts.application.service;
import com.brainserve.onboarding.common.error.ApiException;import com.brainserve.onboarding.contracts.domain.model.ContractTemplateVersionStatus;import com.brainserve.onboarding.contracts.infrastructure.persistence.ContractTemplateVersionRepository;import com.brainserve.onboarding.workflow.application.service.WorkflowStepConfigurationValidator;import com.brainserve.onboarding.workflow.domain.model.WorkflowStepType;import com.fasterxml.jackson.databind.JsonNode;import java.util.UUID;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;
@Service
public class ContractWorkflowConfigurationValidator implements WorkflowStepConfigurationValidator{
 private final ContractTemplateVersionRepository versions;public ContractWorkflowConfigurationValidator(ContractTemplateVersionRepository versions){this.versions=versions;}
 public boolean supports(WorkflowStepType type){return type==WorkflowStepType.CONTRACT;}
 public void validate(UUID org,String stepKey,JsonNode cfg){if(cfg==null||!cfg.isObject())throw invalid(stepKey,"CONTRACT steps require an object configuration.");String raw=cfg.path("contractTemplateVersionId").asText("").trim();UUID id;try{id=UUID.fromString(raw);}catch(RuntimeException ex){throw invalid(stepKey,"contractTemplateVersionId must reference a published contract template version.");}var v=versions.findByOrganizationIdAndId(org,id).orElseThrow(()->invalid(stepKey,"contract template version was not found in this organization."));if(v.getStatus()!=ContractTemplateVersionStatus.PUBLISHED)throw invalid(stepKey,"contract template version must be published.");JsonNode days=cfg.get("expiresAfterDays");if(days!=null&&!days.isNull()&&(!days.canConvertToInt()||days.intValue()<1||days.intValue()>365))throw invalid(stepKey,"expiresAfterDays must be between 1 and 365.");}
 private static ApiException invalid(String k,String m){return new ApiException(HttpStatus.CONFLICT,"WORKFLOW_CONTRACT_CONFIGURATION_INVALID","Step "+k+": "+m);}
}
