package com.brainserve.onboarding.payments.domain.model;

import jakarta.persistence.Column;import jakarta.persistence.Entity;import jakarta.persistence.EnumType;import jakarta.persistence.Enumerated;import jakarta.persistence.Id;import jakarta.persistence.Table;import jakarta.persistence.Version;
import java.time.Instant;import java.util.UUID;
@Entity @Table(name="refunds",schema="client_onboarding")
public class Refund{
 @Id private UUID id; @Column(name="organization_id",nullable=false)private UUID organizationId;@Column(name="invoice_id",nullable=false)private UUID invoiceId;@Column(name="payment_id",nullable=false)private UUID paymentId;
 @Column(nullable=false,length=40)private String provider;@Column(name="provider_refund_id",length=180)private String providerRefundId;@Column(name="amount_minor",nullable=false)private long amountMinor;@Column(nullable=false,length=3)private String currency;
 @Enumerated(EnumType.STRING)@Column(nullable=false,length=24)private RefundStatus status;@Column(nullable=false,length=2000)private String reason;@Column(name="idempotency_key",nullable=false,length=128)private String idempotencyKey;
 @Column(name="failure_reason",length=1000)private String failureReason;@Column(name="requested_at",nullable=false)private Instant requestedAt;@Column(name="completed_at")private Instant completedAt;@Column(name="created_by",nullable=false)private UUID createdBy;@Column(name="updated_at",nullable=false)private Instant updatedAt;@Version private long version;
 protected Refund(){}
 public Refund(UUID id,UUID organizationId,UUID invoiceId,UUID paymentId,String provider,long amountMinor,String currency,String reason,String idempotencyKey,UUID actorId,Instant now){this.id=id;this.organizationId=organizationId;this.invoiceId=invoiceId;this.paymentId=paymentId;this.provider=provider;if(amountMinor<=0)throw new IllegalArgumentException("Refund amount must be positive");this.amountMinor=amountMinor;this.currency=currency;this.reason=require(reason,"Refund reason",2000);this.idempotencyKey=require(idempotencyKey,"Idempotency key",128);this.status=RefundStatus.PENDING;this.requestedAt=now;this.createdBy=actorId;this.updatedAt=now;}
 public void providerAccepted(String providerRefundId,Instant now){this.providerRefundId=require(providerRefundId,"Provider refund id",180);this.updatedAt=now;}
 public void captured(Instant now){this.status=RefundStatus.CAPTURED;this.completedAt=now;this.failureReason=null;this.updatedAt=now;}
 public void failed(String reason,Instant now){this.status=RefundStatus.FAILED;this.failureReason=optional(reason,1000);this.completedAt=now;this.updatedAt=now;}
 private static String require(String v,String l,int m){if(v==null||v.isBlank())throw new IllegalArgumentException(l+" is required");String n=v.trim();if(n.length()>m)throw new IllegalArgumentException(l+" is too long");return n;}private static String optional(String v,int m){if(v==null||v.isBlank())return null;String n=v.trim();return n.length()<=m?n:n.substring(0,m);}
 public UUID getId(){return id;}public UUID getOrganizationId(){return organizationId;}public UUID getInvoiceId(){return invoiceId;}public UUID getPaymentId(){return paymentId;}public String getProvider(){return provider;}public String getProviderRefundId(){return providerRefundId;}public long getAmountMinor(){return amountMinor;}public String getCurrency(){return currency;}public RefundStatus getStatus(){return status;}public String getReason(){return reason;}public String getIdempotencyKey(){return idempotencyKey;}public String getFailureReason(){return failureReason;}public Instant getRequestedAt(){return requestedAt;}public Instant getCompletedAt(){return completedAt;}public UUID getCreatedBy(){return createdBy;}public Instant getUpdatedAt(){return updatedAt;}public long getVersion(){return version;}
}
