package com.brainserve.onboarding.payments.domain.model;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="webhook_events",schema="client_onboarding")
public class WebhookEvent{
 @Id private UUID id;@Column(name="organization_id",nullable=false)private UUID organizationId;@Column(nullable=false,length=40)private String provider;@Column(name="provider_event_id",nullable=false,length=180)private String providerEventId;@Column(name="event_type",nullable=false,length=80)private String eventType;@Column(name="payload_hash",nullable=false,length=64)private String payloadHash;@Column(name="received_at",nullable=false)private Instant receivedAt;@Column(name="processed_at")private Instant processedAt;@Enumerated(EnumType.STRING)@Column(name="processing_status",nullable=false,length=24)private WebhookProcessingStatus processingStatus;@Column(name="attempt_count",nullable=false)private int attemptCount;@Column(name="last_error",length=2000)private String lastError;
 protected WebhookEvent(){}public WebhookEvent(UUID id,UUID org,String provider,String eventId,String eventType,String hash,Instant now){this.id=id;this.organizationId=org;this.provider=provider;this.providerEventId=eventId;this.eventType=eventType;this.payloadHash=hash;this.receivedAt=now;this.processingStatus=WebhookProcessingStatus.RECEIVED;}
 public void processed(Instant now){attemptCount++;processingStatus=WebhookProcessingStatus.PROCESSED;processedAt=now;lastError=null;}public void ignored(Instant now){attemptCount++;processingStatus=WebhookProcessingStatus.IGNORED;processedAt=now;lastError=null;}public void failed(String reason,Instant now){attemptCount++;processingStatus=WebhookProcessingStatus.FAILED;lastError=reason==null?null:reason.substring(0,Math.min(2000,reason.length()));processedAt=now;}
 public UUID getId(){return id;}public UUID getOrganizationId(){return organizationId;}public String getProvider(){return provider;}public String getProviderEventId(){return providerEventId;}public String getEventType(){return eventType;}public String getPayloadHash(){return payloadHash;}public WebhookProcessingStatus getProcessingStatus(){return processingStatus;}public int getAttemptCount(){return attemptCount;}
}
