package com.brainserve.onboarding.reminders.application.service;
import com.brainserve.onboarding.onboarding.application.service.*;import com.brainserve.onboarding.onboarding.domain.model.OnboardingStepStatus;import com.brainserve.onboarding.reminders.domain.model.*;import com.brainserve.onboarding.reminders.infrastructure.persistence.ScheduledReminderRepository;import com.brainserve.onboarding.workflow.domain.model.WorkflowStepType;import java.time.*;import java.util.UUID;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class ReminderScheduleService implements OnboardingStepInitializer,OnboardingStepTransitionListener {
private final ReminderPolicyService policies;private final ScheduledReminderRepository schedules;private final Clock clock;public ReminderScheduleService(ReminderPolicyService policies,ScheduledReminderRepository schedules,Clock clock){this.policies=policies;this.schedules=schedules;this.clock=clock;}
@Override public boolean supports(WorkflowStepType stepType){return true;}
@Override @Transactional public void initialize(OnboardingStepInitializer.StepCreated s){if(s.reminderPolicyId()==null)return;ReminderPolicy p=policies.require(s.organizationId(),s.reminderPolicyId());if(p.getStatus()!=ReminderPolicyStatus.ACTIVE)return;Instant first=firstDue(s.occurredAt(),p);schedules.findByOrganizationIdAndStepIdAndReminderPolicyId(s.organizationId(),s.stepId(),p.getId()).orElseGet(()->{ScheduledReminder reminder=new ScheduledReminder(UUID.randomUUID(),s.organizationId(),p.getId(),s.projectId(),s.onboardingId(),s.stepId(),first,s.occurredAt());if(s.status()==OnboardingStepStatus.LOCKED)reminder.suppress("Waiting for workflow prerequisites",s.occurredAt());return schedules.save(reminder);});}
@Override @Transactional public void onTransition(OnboardingStepTransitionListener.StepTransition t){if(t.after()!=OnboardingStepStatus.COMPLETED&&t.after()!=OnboardingStepStatus.CANCELLED&&t.after()!=OnboardingStepStatus.AVAILABLE&&t.after()!=OnboardingStepStatus.IN_PROGRESS&&t.after()!=OnboardingStepStatus.NEEDS_REVISION)return;var existing=schedules.findByOrganizationIdAndStepId(t.organizationId(),t.stepId()).orElse(null);if(existing==null)return;ReminderPolicy p=policies.require(t.organizationId(),existing.getReminderPolicyId());Instant now=t.occurredAt();if(t.after()==OnboardingStepStatus.COMPLETED||t.after()==OnboardingStepStatus.CANCELLED){existing.complete("Workflow step is "+t.after().name().toLowerCase(),now);}else if(p.getStatus()==ReminderPolicyStatus.ACTIVE&&existing.getStatus()!=ScheduledReminderStatus.ACTIVE){existing.reactivate(firstDue(now,p),now);}else if(p.getStatus()!=ReminderPolicyStatus.ACTIVE){existing.suppress("Reminder policy is archived",now);}schedules.save(existing);}
private static Instant firstDue(Instant base,ReminderPolicy p){return base.plusSeconds((long)p.getInitialDelayMinutes()*60L);}
}
