package com.brainserve.onboarding.reminders.application.service;
import com.brainserve.onboarding.audit.application.service.AuditService;import com.brainserve.onboarding.common.error.ApiException;import com.brainserve.onboarding.common.security.TenantPrincipal;import com.brainserve.onboarding.reminders.api.request.*;import com.brainserve.onboarding.reminders.api.response.*;import com.brainserve.onboarding.reminders.domain.model.*;import com.brainserve.onboarding.reminders.infrastructure.persistence.*;import com.brainserve.onboarding.workflow.application.service.WorkflowReminderPolicyValidator;import com.fasterxml.jackson.databind.ObjectMapper;import jakarta.servlet.http.HttpServletRequest;import java.time.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class ReminderPolicyService implements WorkflowReminderPolicyValidator {private final ReminderPolicyRepository policies;private final ScheduledReminderRepository schedules;private final ObjectMapper mapper;private final AuditService audit;private final Clock clock;public ReminderPolicyService(ReminderPolicyRepository policies,ScheduledReminderRepository schedules,ObjectMapper mapper,AuditService audit,Clock clock){this.policies=policies;this.schedules=schedules;this.mapper=mapper;this.audit=audit;this.clock=clock;}
@Transactional public ReminderPolicyResponse create(TenantPrincipal p,CreateReminderPolicyRequest r,HttpServletRequest req){if(policies.existsByOrganizationIdAndNameIgnoreCase(p.organizationId(),r.name().trim()))throw conflict("Reminder policy name already exists.");validateChannels(r.channels());ReminderPolicy x;try{x=new ReminderPolicy(UUID.randomUUID(),p.organizationId(),r.name(),r.description(),r.initialDelayMinutes(),r.repeatIntervalMinutes(),r.maximumReminders(),r.businessHoursOnly(),r.timezone(),mapper.valueToTree(r.channels()),r.stopWhenCompleted(),p.userId(),clock.instant());}catch(IllegalArgumentException|IllegalStateException ex){throw bad(ex.getMessage());}x=policies.saveAndFlush(x);audit.record(p.organizationId(),p.userId(),"REMINDER_POLICY_CREATED","REMINDER_POLICY",x.getId(),null,Map.of("name",x.getName()),req);return map(x);}
@Transactional(readOnly=true)public PageResult list(TenantPrincipal p,int page,int size){var q=PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.ASC,"name"));var x=policies.findAllByOrganizationId(p.organizationId(),q);return new PageResult(x.getContent().stream().map(ReminderPolicyService::map).toList(),x.getNumber(),x.getSize(),x.getTotalElements(),x.getTotalPages());}
@Transactional(readOnly=true)public ReminderPolicyResponse get(TenantPrincipal p,UUID id){return map(require(p.organizationId(),id));}
@Transactional public ReminderPolicyResponse update(TenantPrincipal p,UUID id,UpdateReminderPolicyRequest r,HttpServletRequest req){var x=policies.findForUpdate(p.organizationId(),id).orElseThrow(ReminderPolicyService::notFound);if(x.getVersion()!=r.version())throw version();validateChannels(r.channels());try{x.update(r.name(),r.description(),r.initialDelayMinutes(),r.repeatIntervalMinutes(),r.maximumReminders(),r.businessHoursOnly(),r.timezone(),mapper.valueToTree(r.channels()),r.stopWhenCompleted(),p.userId(),clock.instant());}catch(IllegalArgumentException|IllegalStateException ex){throw bad(ex.getMessage());}policies.saveAndFlush(x);audit.record(p.organizationId(),p.userId(),"REMINDER_POLICY_UPDATED","REMINDER_POLICY",id,null,Map.of("name",x.getName()),req);return map(x);}
@Transactional public ReminderPolicyResponse archive(TenantPrincipal p,UUID id,long version,HttpServletRequest req){var x=policies.findForUpdate(p.organizationId(),id).orElseThrow(ReminderPolicyService::notFound);if(x.getVersion()!=version)throw version();x.archive(p.userId(),clock.instant());policies.saveAndFlush(x);audit.record(p.organizationId(),p.userId(),"REMINDER_POLICY_ARCHIVED","REMINDER_POLICY",id,null,Map.of(),req);return map(x);}
@Transactional(readOnly=true)public SchedulesResult schedules(TenantPrincipal p,int page,int size){var q=PageRequest.of(Math.max(0,page),Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.ASC,"nextRunAt"));var x=schedules.findAllByOrganizationId(p.organizationId(),q);return new SchedulesResult(x.getContent().stream().map(ReminderPolicyService::mapSchedule).toList(),x.getNumber(),x.getSize(),x.getTotalElements(),x.getTotalPages());}
@Override @Transactional(readOnly=true)public void validate(UUID org,UUID policyId){ReminderPolicy p=require(org,policyId);if(p.getStatus()!=ReminderPolicyStatus.ACTIVE)throw new ApiException(HttpStatus.BAD_REQUEST,"REMINDER_POLICY_INVALID","Workflow steps can reference only active reminder policies.");}
public ReminderPolicy require(UUID org,UUID id){return policies.findByOrganizationIdAndId(org,id).orElseThrow(ReminderPolicyService::notFound);}private static void validateChannels(List<String> c){if(c==null||c.isEmpty()||c.size()>2||c.stream().distinct().count()!=c.size()||c.stream().anyMatch(x->!(x.equals("EMAIL")||x.equals("IN_APP"))))throw bad("Reminder channels must contain unique EMAIL and/or IN_APP values.");}
private static ReminderPolicyResponse map(ReminderPolicy p){List<String> c=new ArrayList<>();p.getChannels().forEach(v->c.add(v.asText()));return new ReminderPolicyResponse(p.getId(),p.getName(),p.getDescription(),p.getInitialDelayMinutes(),p.getRepeatIntervalMinutes(),p.getMaximumReminders(),p.isBusinessHoursOnly(),p.getTimezone(),c,p.isStopWhenCompleted(),p.getStatus(),p.getUpdatedAt(),p.getVersion());}private static ScheduledReminderResponse mapSchedule(ScheduledReminder r){return new ScheduledReminderResponse(r.getId(),r.getReminderPolicyId(),r.getProjectId(),r.getOnboardingId(),r.getStepId(),r.getStatus(),r.getNextRunAt(),r.getSentCount(),r.getLastSentAt(),r.getSuppressionReason(),r.getVersion());}private static ApiException notFound(){return new ApiException(HttpStatus.NOT_FOUND,"RESOURCE_NOT_FOUND","Reminder policy was not found.");}private static ApiException conflict(String m){return new ApiException(HttpStatus.CONFLICT,"REMINDER_POLICY_CONFLICT",m);}private static ApiException version(){return new ApiException(HttpStatus.CONFLICT,"VERSION_CONFLICT","The reminder policy changed. Refresh and try again.");}private static ApiException bad(String m){return new ApiException(HttpStatus.BAD_REQUEST,"REMINDER_POLICY_INVALID",m);}public record PageResult(List<ReminderPolicyResponse>items,int page,int size,long totalElements,int totalPages){}public record SchedulesResult(List<ScheduledReminderResponse>items,int page,int size,long totalElements,int totalPages){}
}
