package com.brainserve.onboarding.reminders.application.service;
import com.brainserve.onboarding.notifications.application.service.*;import com.brainserve.onboarding.notifications.domain.model.NotificationChannel;import com.fasterxml.jackson.databind.*;import java.time.*;import java.time.temporal.TemporalAdjusters;import java.util.*;import org.slf4j.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Component;
@Component public class ReminderWorker {
private static final Logger log=LoggerFactory.getLogger(ReminderWorker.class);private final JdbcTemplate jdbc;private final NotificationRecipientResolver recipients;private final NotificationService notifications;private final ObjectMapper mapper;private final Clock clock;public ReminderWorker(JdbcTemplate jdbc,NotificationRecipientResolver recipients,NotificationService notifications,ObjectMapper mapper,Clock clock){this.jdbc=jdbc;this.recipients=recipients;this.notifications=notifications;this.mapper=mapper;this.clock=clock;}
@Scheduled(fixedDelayString="${app.reminders.poll-ms:60000}")public void poll(){for(Row r:due()){if(!claim(r.id))continue;try{process(r);}catch(RuntimeException ex){log.error("Reminder processing failed id={}",r.id,ex);release(r.id,clock.instant().plusSeconds(300),"Processing failed: "+shortText(ex.getMessage()));}}}
private List<Row> due(){return jdbc.query("SELECT sr.id,sr.organization_id,sr.reminder_policy_id,sr.project_id,sr.onboarding_id,sr.step_id,sr.sent_count,p.repeat_interval_minutes,p.maximum_reminders,p.business_hours_only,p.timezone,p.channels::text,p.stop_when_completed,p.status,osi.status,osi.name,osi.client_visible,osi.assigned_role_id,oi.status FROM client_onboarding.scheduled_reminders sr JOIN client_onboarding.reminder_policies p ON p.organization_id=sr.organization_id AND p.id=sr.reminder_policy_id JOIN client_onboarding.onboarding_step_instances osi ON osi.organization_id=sr.organization_id AND osi.id=sr.step_id JOIN client_onboarding.onboarding_instances oi ON oi.organization_id=sr.organization_id AND oi.id=sr.onboarding_id WHERE sr.status='ACTIVE' AND sr.next_run_at<=CURRENT_TIMESTAMP AND (sr.lease_until IS NULL OR sr.lease_until<CURRENT_TIMESTAMP) ORDER BY sr.next_run_at,sr.id LIMIT 50",(rs,n)->new Row(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getObject(3,UUID.class),rs.getObject(4,UUID.class),rs.getObject(5,UUID.class),rs.getObject(6,UUID.class),rs.getInt(7),rs.getInt(8),rs.getInt(9),rs.getBoolean(10),rs.getString(11),rs.getString(12),rs.getBoolean(13),rs.getString(14),rs.getString(15),rs.getString(16),rs.getBoolean(17),rs.getObject(18,UUID.class),rs.getString(19)));}
private boolean claim(UUID id){Instant now=clock.instant();return jdbc.update("UPDATE client_onboarding.scheduled_reminders SET lease_until=?,updated_at=? WHERE id=? AND status='ACTIVE' AND next_run_at<=? AND (lease_until IS NULL OR lease_until<?)",now.plusSeconds(300),now,id,now,now)==1;}
private void process(Row r){Instant now=clock.instant();if(!"ACTIVE".equals(r.policyStatus)){suppress(r.id,"Reminder policy is archived");return;}if(Set.of("PAUSED","CANCELLED","COMPLETED","EXPIRED").contains(r.onboardingStatus)){suppress(r.id,"Onboarding is "+r.onboardingStatus.toLowerCase());return;}if(Set.of("COMPLETED","CANCELLED").contains(r.stepStatus)){suppress(r.id,"Step is "+r.stepStatus.toLowerCase());return;}if(r.sentCount>=r.maximum){complete(r.id,"Maximum reminders reached");return;}if("LOCKED".equals(r.stepStatus)){release(r.id,now.plusSeconds(Math.max(900L,(long)r.repeatMinutes*60L)),null);return;}if(r.businessHours){Instant business=nextBusinessInstant(now,r.timezone);if(business.isAfter(now.plusSeconds(1))){release(r.id,business,null);return;}}
boolean waitingForInternal = Set.of("SUBMITTED","UNDER_REVIEW").contains(r.stepStatus);boolean clientAction = r.clientVisible&&!waitingForInternal;List<NotificationRecipientResolver.Recipient> resolved=clientAction?recipients.resolve(r.organizationId,"PROJECT_CLIENTS",null,r.projectId,mapper.createObjectNode()):r.assignedRoleId!=null?recipients.resolveRole(r.organizationId,r.assignedRoleId):recipients.resolve(r.organizationId,"PROJECT_MEMBERS",null,r.projectId,mapper.createObjectNode());if(resolved.isEmpty()){suppress(r.id,"No eligible reminder recipients");return;}List<NotificationChannel> channels=parseChannels(r.channelsJson);int nextOrdinal=r.sentCount+1;for(var u:resolved)notifications.createForResolvedRecipient(r.organizationId,u.userId(),u.type(),u.email(),u.inAppEnabled(),u.emailEnabled(),null,"REMINDER_DUE","ONBOARDING_STEP",r.stepId,r.projectId,"Reminder: "+r.stepName,"This onboarding requirement still needs attention.",clientAction?"/portal/projects/"+r.projectId:"/app/projects/"+r.projectId,"reminder:"+r.id+":"+nextOrdinal+":"+u.userId(),channels,false);Instant next=now.plusSeconds((long)r.repeatMinutes*60L);jdbc.update("UPDATE client_onboarding.scheduled_reminders SET sent_count=sent_count+1,last_sent_at=?,next_run_at=?,status=CASE WHEN sent_count+1>=? THEN 'COMPLETED' ELSE 'ACTIVE' END,suppression_reason=CASE WHEN sent_count+1>=? THEN 'Maximum reminders reached' ELSE NULL END,lease_until=NULL,updated_at=? WHERE id=?",now,next,r.maximum,r.maximum,now,r.id);}
private List<NotificationChannel> parseChannels(String json){try{JsonNode n=mapper.readTree(json);List<NotificationChannel> out=new ArrayList<>();n.forEach(v->out.add(NotificationChannel.valueOf(v.asText())));return out;}catch(Exception ex){return List.of(NotificationChannel.IN_APP);}}
private void suppress(UUID id,String reason){jdbc.update("UPDATE client_onboarding.scheduled_reminders SET status='SUPPRESSED',suppression_reason=?,lease_until=NULL,updated_at=? WHERE id=?",shortText(reason),clock.instant(),id);}private void complete(UUID id,String reason){jdbc.update("UPDATE client_onboarding.scheduled_reminders SET status='COMPLETED',suppression_reason=?,lease_until=NULL,updated_at=? WHERE id=?",shortText(reason),clock.instant(),id);}private void release(UUID id,Instant next,String reason){jdbc.update("UPDATE client_onboarding.scheduled_reminders SET next_run_at=?,lease_until=NULL,suppression_reason=?,updated_at=? WHERE id=?",next,reason,clock.instant(),id);}
static Instant nextBusinessInstant(Instant now,String zone){ZoneId z=ZoneId.of(zone);ZonedDateTime local=now.atZone(z);DayOfWeek day=local.getDayOfWeek();LocalTime time=local.toLocalTime();boolean weekday=day!=DayOfWeek.SATURDAY&&day!=DayOfWeek.SUNDAY;if(weekday&&!time.isBefore(LocalTime.of(9,0))&&time.isBefore(LocalTime.of(17,0)))return now;ZonedDateTime target=local.withHour(9).withMinute(0).withSecond(0).withNano(0);if(!weekday||!time.isBefore(LocalTime.of(9,0))){target=target.plusDays(1);while(target.getDayOfWeek()==DayOfWeek.SATURDAY||target.getDayOfWeek()==DayOfWeek.SUNDAY)target=target.plusDays(1);}return target.toInstant();}
private static String shortText(String s){if(s==null)return null;return s.substring(0,Math.min(500,s.length()));}
private record Row(UUID id,UUID organizationId,UUID policyId,UUID projectId,UUID onboardingId,UUID stepId,int sentCount,int repeatMinutes,int maximum,boolean businessHours,String timezone,String channelsJson,boolean stopWhenCompleted,String policyStatus,String stepStatus,String stepName,boolean clientVisible,UUID assignedRoleId,String onboardingStatus){}
}
