"use client";
import Link from "next/link";
import { useState } from "react";
import { Loader2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FormMessage } from "@/components/auth/form-message";
import { apiRequest, ApiClientError } from "@/services/api-client";
export function ResetPasswordForm({token}:{token:string}){const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState<string|null>(null);async function submit(e:React.FormEvent){e.preventDefault();if(password!==confirm){setError("Passwords do not match.");return}setBusy(true);setError(null);try{await apiRequest("/auth/reset-password",{method:"POST",body:JSON.stringify({token,newPassword:password})});setDone(true);}catch(err){setError(err instanceof ApiClientError?err.message:"Password could not be reset.");}finally{setBusy(false)}}if(!token)return <FormMessage>This password reset link is missing its security token.</FormMessage>;if(done)return <div className="space-y-4"><FormMessage tone="success">Password changed. Existing sessions were invalidated.</FormMessage><Button className="w-full" asChild><Link href="/login">Sign in with new password</Link></Button></div>;return <form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="password">New password</Label><Input id="password" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} maxLength={128} required/><p className="text-xs text-[hsl(var(--muted-foreground))]">Use 12–128 characters and avoid common or account-related phrases.</p></div><div className="space-y-2"><Label htmlFor="confirm">Confirm password</Label><Input id="confirm" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></div>{error&&<FormMessage>{error}</FormMessage>}<Button className="w-full" size="lg" disabled={busy}>{busy?<Loader2 className="size-4 animate-spin"/>:<ShieldCheck className="size-4"/>} Update password</Button></form>}
