"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useCurrentUser } from "@/features/settings/internal-shell";
import { formsApi } from "./forms-api";
import { formControl, QuestionFields } from "./question-fields";
import { fieldTypes, type Answers, type FormDefinition, type FormField, type FormTemplate } from "./types";

export function FormBuilder({ formId }: { formId: string }) {
  const user = useCurrentUser(); const canManage = user.permissions.includes("FORM_MANAGE"); const allowed = canManage || user.permissions.includes("FORM_READ");
  const [template, setTemplate] = useState<FormTemplate>(); const [versions, setVersions] = useState<FormDefinition[]>([]);
  const [selected, setSelected] = useState<FormDefinition>(); const [fields, setFields] = useState<FormField[]>([]); const [page, setPage] = useState(0);
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [dirty, setDirty] = useState(false);
  const [preview, setPreview] = useState(false); const [answers, setAnswers] = useState<Answers>({}); const [archiveConfirm, setArchiveConfirm] = useState(false);
  const editable = canManage && selected?.status === "DRAFT" && !template?.archivedAt;
  function choose(value: FormDefinition) { setSelected(value); setFields(value.fields); setDirty(false); setAnswers({}); }
  useEffect(() => { if (!allowed) return; let active = true; Promise.all([formsApi.template(formId), formsApi.versions(formId)]).then(([t, v]) => { if (active) { setTemplate(t); setVersions(v); if (v[0]) choose(v[0]); } }).catch((e) => { if (active) setError(e.message); }); return () => { active = false; }; }, [formId, allowed]);
  useEffect(() => { const leave = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault(); }; window.addEventListener("beforeunload", leave); return () => window.removeEventListener("beforeunload", leave); }, [dirty]);
  async function action(kind: "save" | "publish" | "new" | "archive") {
    if (!template || !selected) return; setPending(true); setError(""); setMessage("");
    try {
      if (kind === "archive") { await formsApi.archive(formId, template.version); setTemplate(await formsApi.template(formId)); setMessage("Archived. Existing responses retain their form version."); }
      else { const value = kind === "save" ? await formsApi.save(selected.id, selected.version, fields) : kind === "publish" ? await formsApi.publish(selected.id, selected.version) : await formsApi.newVersion(formId, selected.status === "PUBLISHED" ? selected.id : undefined); choose(value); setVersions(await formsApi.versions(formId)); setPage(0); setMessage(kind === "publish" ? "Published. This version can now be selected in a workflow." : kind === "new" ? "New draft created from the selected version." : "Draft saved."); }
    } catch (e) { setError(e instanceof Error ? e.message : "The form could not be updated."); } finally { setPending(false); }
  }
  function update(index: number, changes: Partial<FormField>) { setFields((old) => old.map((field, i) => i === index ? { ...field, ...changes } : field)); setDirty(true); setMessage(""); }
  function reorder(index: number, direction: number) { const next = [...fields]; [next[index], next[index + direction]] = [next[index + direction], next[index]]; setFields(next); setDirty(true); }
  async function versionPage(next: number) { if (dirty && !window.confirm("Discard unsaved field changes?")) return; setPending(true); try { const values = await formsApi.versions(formId, next); setVersions(values); setPage(next); if (values[0]) choose(values[0]); } catch (e) { setError(e instanceof Error ? e.message : "Could not load versions."); } finally { setPending(false); } }
  if (!allowed) return <Alert>You do not have permission to read form templates.</Alert>;
  return <><Link href="/app/forms" className="inline-flex min-h-11 items-center font-semibold text-primary" onClick={(e) => { if (dirty && !window.confirm("Discard unsaved field changes?")) e.preventDefault(); }}>← All forms</Link>{error && <Alert tone="error" className="mt-5">{error}</Alert>}{!template ? !error && <p className="mt-5" aria-busy="true">Loading form builder…</p> : <>
    <div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{template.name}</h1><p className="mt-3 text-muted-foreground">{template.description || "Build the questions your team needs answered."}</p></div><Badge>{template.archivedAt ? "ARCHIVED" : selected?.status ?? "NO VERSION"}</Badge></div>
    {message && <Alert tone="success" className="mt-5">{message}</Alert>}
    <div className="mt-6 flex flex-wrap items-end gap-3"><label className="min-w-0 text-sm font-semibold">Form version<select className={formControl} value={selected?.id ?? ""} disabled={pending} onChange={(e) => { if (dirty && !window.confirm("Discard unsaved field changes?")) return; const v = versions.find((v) => v.id === e.target.value); if (v) choose(v); }}>{versions.map((v) => <option key={v.id} value={v.id}>Version {v.versionNumber} · {v.status}</option>)}</select></label><Button variant="outline" disabled={pending || page === 0} onClick={() => versionPage(page - 1)}>Newer versions</Button><Button variant="outline" disabled={pending || versions.length < 20} onClick={() => versionPage(page + 1)}>Older versions</Button>{canManage && !template.archivedAt && selected?.status === "PUBLISHED" && <Button variant="outline" disabled={pending} onClick={() => action("new")}>Create next draft</Button>}<Button variant="outline" onClick={() => setPreview(!preview)}>{preview ? "Edit fields" : "Preview questionnaire"}</Button></div>
    {selected?.status === "PUBLISHED" && <Alert className="mt-5">This published version is immutable. Create a new draft to change future questionnaires.</Alert>}
    {preview ? <Card className="mt-6 max-w-3xl"><h2 className="mb-5 text-xl font-bold">Questionnaire preview</h2>{fields.length ? <QuestionFields fields={fields} answers={answers} update={(key, value) => setAnswers((old) => { const next = { ...old }; if (value === undefined) delete next[key]; else next[key] = value; return next; })} /> : <p>Add fields to preview your form.</p>}</Card> : <div className="mt-6 space-y-4">{fields.length === 0 && <Card><h2 className="font-bold">Add your first question</h2><p className="mt-2 text-sm text-muted-foreground">Choose a type, write a label, and decide whether an answer is required.</p></Card>}{fields.map((field, index) => <FieldEditor key={index} field={field} index={index} fields={fields} disabled={!editable || pending} update={(changes) => update(index, changes)} move={(direction) => reorder(index, direction)} remove={() => { setFields((old) => old.filter((_, i) => i !== index)); setDirty(true); }} />)}</div>}
    {editable && <div className="mt-6 flex flex-wrap items-center gap-3"><Button variant="outline" disabled={pending || fields.length >= 100} onClick={() => { let key = `question_${fields.length + 1}`; while (fields.some((f) => f.key === key)) key += "_new"; setFields([...fields, { key, label: "New question", type: "TEXT", required: false, options: [] }]); setDirty(true); }}>Add question</Button><Button variant="outline" disabled={pending || !dirty || !fields.length} onClick={() => action("save")}>Save draft</Button><Button disabled={pending || dirty || !fields.length} onClick={() => action("publish")}>{pending ? "Working…" : "Publish version"}</Button><span className="text-sm text-muted-foreground" role="status">{dirty ? "Unsaved changes" : "Draft is saved"}</span></div>}
    {canManage && !template.archivedAt && <div className="mt-10 border-t pt-5"><Button variant="ghost" onClick={() => setArchiveConfirm(!archiveConfirm)}>Archive form</Button>{archiveConfirm && <div className="mt-3"><p className="text-sm text-muted-foreground">Stop new workflows from using this form? Existing responses will remain available.</p><Button variant="danger" className="mt-3" disabled={pending} onClick={() => action("archive")}>Confirm archive</Button></div>}</div>}
  </>}</>;
}

function FieldEditor({ field, index, fields, disabled, update, move, remove }: { field: FormField; index: number; fields: FormField[]; disabled: boolean; update: (changes: Partial<FormField>) => void; move: (direction: number) => void; remove: () => void }) {
  const choice = ["DROPDOWN", "RADIO", "CHECKBOX", "MULTI_SELECT"].includes(field.type);
  return <Card><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="min-w-0 font-bold [overflow-wrap:anywhere]">Question {index + 1}: {field.label}</h2><div className="flex flex-wrap gap-2"><Button size="sm" variant="ghost" disabled={disabled || index === 0} onClick={() => move(-1)} aria-label={`Move question ${index + 1} up`}>Move up</Button><Button size="sm" variant="ghost" disabled={disabled || index === fields.length - 1} onClick={() => move(1)} aria-label={`Move question ${index + 1} down`}>Move down</Button><Button size="sm" variant="ghost" disabled={disabled} onClick={remove} aria-label={`Remove question ${index + 1}`}>Remove</Button></div></div>
    <fieldset disabled={disabled} className="mt-4 grid min-w-0 gap-4 sm:grid-cols-2"><legend className="sr-only">Question {index + 1} settings</legend><label className="text-sm font-semibold">Question label<Input className="mt-2" value={field.label} maxLength={180} onChange={(e) => update({ label: e.target.value })} /></label><label className="text-sm font-semibold">Field key<Input className="mt-2" value={field.key} maxLength={60} onChange={(e) => update({ key: e.target.value })} /></label><label className="text-sm font-semibold">Answer type<select className={formControl} value={field.type} onChange={(e) => { const type = e.target.value as FormField["type"]; update({ type, options: ["DROPDOWN", "RADIO", "CHECKBOX", "MULTI_SELECT"].includes(type) ? field.options : [], min: undefined, max: undefined }); }}>{fieldTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="flex min-h-12 items-center gap-3 text-sm font-semibold"><input className="size-4 accent-primary" type="checkbox" checked={field.required} onChange={(e) => update({ required: e.target.checked })} />Required answer</label><label className="text-sm font-semibold sm:col-span-2">Help text<Input className="mt-2" value={field.helpText ?? ""} maxLength={1000} onChange={(e) => update({ helpText: e.target.value })} /></label>
      {choice && <label className="text-sm font-semibold sm:col-span-2">Options (one per line)<textarea className={`${formControl} min-h-24`} value={field.options.join("\n")} onChange={(e) => update({ options: e.target.value.split("\n") })} /></label>}
      {field.type === "NUMBER" ? <>{(["min", "max"] as const).map((key) => <label key={key} className="text-sm font-semibold">{key === "min" ? "Minimum number" : "Maximum number"}<Input type="number" step="any" className="mt-2" value={field[key] ?? ""} onChange={(e) => update({ [key]: e.target.value === "" ? undefined : Number(e.target.value) })} /></label>)}</> : !choice && field.type !== "BOOLEAN" && <label className="text-sm font-semibold">Maximum characters<Input className="mt-2" type="number" min={1} max={10000} value={field.maxLength ?? 2000} onChange={(e) => update({ maxLength: e.target.value ? Number(e.target.value) : undefined })} /></label>}
      <label className="text-sm font-semibold">Show question when<select className={formControl} value={field.condition?.fieldKey ?? ""} onChange={(e) => { const source = fields.find((f) => f.key === e.target.value); update({ condition: e.target.value ? { fieldKey: e.target.value, operator: source && ["CHECKBOX", "MULTI_SELECT"].includes(source.type) ? "CONTAINS" : "EQUALS", value: "" } : undefined }); }}><option value="">Always show</option>{fields.slice(0, index).map((f) => <option key={f.key} value={f.key}>{f.label}</option>)}</select></label>
      {field.condition && <><label className="text-sm font-semibold">Condition operator<select className={formControl} value={field.condition.operator} onChange={(e) => update({ condition: { ...field.condition!, operator: e.target.value as "EQUALS" | "NOT_EQUALS" | "CONTAINS" } })}><option value="EQUALS">Equals</option><option value="NOT_EQUALS">Does not equal</option><option value="CONTAINS">Contains choice</option></select></label><label className="text-sm font-semibold">Condition value<Input className="mt-2" maxLength={200} value={field.condition.value} onChange={(e) => update({ condition: { ...field.condition!, value: e.target.value } })} /><span className="mt-1 block font-normal text-muted-foreground">For a Yes/No answer, use true or false.</span></label></>}
    </fieldset></Card>;
}
