package com.brainserve.onboarding.notifications.domain.model;
import com.fasterxml.jackson.databind.JsonNode;import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;import org.hibernate.annotations.JdbcTypeCode;import org.hibernate.type.SqlTypes;
@Entity @Table(name="notification_templates",schema="client_onboarding")
public class NotificationTemplate {
@Id private UUID id; @Column(name="organization_id",nullable=false) private UUID organizationId; @Column(nullable=false,length=100) private String code; @Column(nullable=false,length=180) private String name; @Column(name="event_type",nullable=false,length=100) private String eventType; @Column(name="recipient_scope",nullable=false,length=32) private String recipientScope; @Column(name="required_permission",length=100) private String requiredPermission; @Column(name="subject_template",nullable=false,length=300) private String subjectTemplate; @Column(name="body_template",nullable=false,length=6000) private String bodyTemplate; @Column(name="action_path_template",length=1000) private String actionPathTemplate; @JdbcTypeCode(SqlTypes.JSON) @Column(nullable=false,columnDefinition="jsonb") private JsonNode channels; @Column(nullable=false) private boolean mandatory; @Column(nullable=false,length=20) private String status; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="created_by") private UUID createdBy; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="updated_by") private UUID updatedBy; @Version private long version;
protected NotificationTemplate(){}
public NotificationTemplate(UUID id,UUID org,String code,String name,String eventType,String recipientScope,String requiredPermission,String subject,String body,String action,JsonNode channels,boolean mandatory,UUID actor,Instant now){this.id=id;this.organizationId=org;this.code=norm(code,100,"Template code").toUpperCase(java.util.Locale.ROOT);this.name=norm(name,180,"Template name");this.eventType=norm(eventType,100,"Event type").toUpperCase(java.util.Locale.ROOT);this.recipientScope=scope(recipientScope);this.requiredPermission=optional(requiredPermission,100);if("PERMISSION".equals(this.recipientScope)&&this.requiredPermission==null)throw new IllegalArgumentException("Required permission is required for PERMISSION templates");this.subjectTemplate=norm(subject,300,"Subject template");this.bodyTemplate=norm(body,6000,"Body template");this.actionPathTemplate=optional(action,1000);this.channels=channels.deepCopy();this.mandatory=mandatory;this.status="ACTIVE";this.createdAt=now;this.updatedAt=now;this.createdBy=actor;this.updatedBy=actor;}
public void update(String name,String recipientScope,String requiredPermission,String subject,String body,String action,JsonNode channels,boolean mandatory,UUID actor,Instant now){if(!"ACTIVE".equals(status))throw new IllegalStateException("Archived notification templates cannot be edited");this.name=norm(name,180,"Template name");this.recipientScope=scope(recipientScope);this.requiredPermission=optional(requiredPermission,100);if("PERMISSION".equals(this.recipientScope)&&this.requiredPermission==null)throw new IllegalArgumentException("Required permission is required for PERMISSION templates");this.subjectTemplate=norm(subject,300,"Subject template");this.bodyTemplate=norm(body,6000,"Body template");this.actionPathTemplate=optional(action,1000);this.channels=channels.deepCopy();this.mandatory=mandatory;this.updatedBy=actor;this.updatedAt=now;} public void archive(UUID actor,Instant now){status="ARCHIVED";updatedBy=actor;updatedAt=now;}
private static String norm(String v,int max,String l){if(v==null||v.isBlank())throw new IllegalArgumentException(l+" is required");String n=v.trim();if(n.length()>max)throw new IllegalArgumentException(l+" is too long");return n;}private static String optional(String v,int max){if(v==null||v.isBlank())return null;String n=v.trim();if(n.length()>max)throw new IllegalArgumentException("Value is too long");return n;}private static String scope(String v){String n=norm(v,32,"Recipient scope").toUpperCase(java.util.Locale.ROOT);if(!java.util.Set.of("PROJECT_CLIENTS","PROJECT_MEMBERS","PERMISSION","ACTOR").contains(n))throw new IllegalArgumentException("Unsupported recipient scope");return n;}
public UUID getId(){return id;}public UUID getOrganizationId(){return organizationId;}public String getCode(){return code;}public String getName(){return name;}public String getEventType(){return eventType;}public String getRecipientScope(){return recipientScope;}public String getRequiredPermission(){return requiredPermission;}public String getSubjectTemplate(){return subjectTemplate;}public String getBodyTemplate(){return bodyTemplate;}public String getActionPathTemplate(){return actionPathTemplate;}public JsonNode getChannels(){return channels.deepCopy();}public boolean isMandatory(){return mandatory;}public String getStatus(){return status;}public Instant getUpdatedAt(){return updatedAt;}public long getVersion(){return version;}
}
