package com.brainserve.onboarding.contracts.infrastructure.storage;
import com.brainserve.onboarding.common.util.CryptoSupport;import com.brainserve.onboarding.contracts.infrastructure.config.ContractStorageProperties;import java.time.Clock;import software.amazon.awssdk.core.sync.RequestBody;import software.amazon.awssdk.services.s3.S3Client;import software.amazon.awssdk.services.s3.model.PutObjectRequest;import software.amazon.awssdk.services.s3.model.GetObjectRequest;import software.amazon.awssdk.services.s3.presigner.S3Presigner;import software.amazon.awssdk.services.s3.presigner.model.GetObjectPresignRequest;
public class S3ContractDocumentStorage implements ContractDocumentStorage{
 private final ContractStorageProperties props;private final S3Client client;private final S3Presigner presigner;private final Clock clock;
 public S3ContractDocumentStorage(ContractStorageProperties props,S3Client client,S3Presigner presigner,Clock clock){this.props=props;this.client=client;this.presigner=presigner;this.clock=clock;}
 public boolean available(){return true;}
 public StoredDocument storeSignedPdf(String key,byte[] bytes){if(bytes==null||bytes.length<5||bytes[0]!='%'||bytes[1]!='P'||bytes[2]!='D'||bytes[3]!='F'||bytes[4]!='-')throw new IllegalArgumentException("Signed contract document is not a PDF");String sha=CryptoSupport.sha256Hex(bytes);client.putObject(PutObjectRequest.builder().bucket(props.bucket()).key(key).contentType("application/pdf").metadata(java.util.Map.of("sha256",sha,"document-kind","signed-contract")).build(),RequestBody.fromBytes(bytes));return new StoredDocument(props.bucket(),key,sha,bytes.length,"application/pdf",clock.instant());}
 public DownloadOperation presignDownload(String bucket,String key,String filename){String safe=filename==null?"signed-contract.pdf":filename.replace("\"","").replace("\r","").replace("\n","");var req=GetObjectRequest.builder().bucket(bucket).key(key).responseContentType("application/pdf").responseContentDisposition("attachment; filename=\""+safe+"\"").build();var signed=presigner.presignGetObject(GetObjectPresignRequest.builder().signatureDuration(props.downloadUrlTtl()).getObjectRequest(req).build());return new DownloadOperation(signed.url().toString(),clock.instant().plus(props.downloadUrlTtl()));}
}
