"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Archive, ArrowLeft, CirclePause, GitBranch, Loader2, Pencil, Play, Plus, Save, Trash2, UsersRound, XCircle } from "lucide-react";
import { useAuth } from "@/auth/auth-provider";
import { FormMessage } from "@/components/auth/form-message";
import { PageHeading } from "@/components/layout/page-heading";
import { EmptyState } from "@/components/shared/empty-state";
import { PermissionState } from "@/components/shared/permission-state";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ApiClientError } from "@/services/api-client";
import type { ActivityItem } from "@/types/activity";
import type { Client } from "@/types/client";
import type { OrganizationUser } from "@/types/organization";
import type { Onboarding } from "@/types/onboarding";
import type { Project, ProjectMember } from "@/types/project";
import type { ServiceDefinition } from "@/types/service";
import type { WorkflowTemplateSummary } from "@/types/workflow";

export default function ProjectDetailPage(){
  const params=useParams<{projectId:string}>();const router=useRouter();const{authorizedRequest,hasPermission}=useAuth();const canRead=hasPermission("PROJECT_READ");const canUpdate=hasPermission("PROJECT_UPDATE");const canReadUsers=hasPermission("USER_READ")||hasPermission("USER_MANAGE");
  const[project,setProject]=useState<Project|null>(null);const[members,setMembers]=useState<ProjectMember[]>([]);const[activity,setActivity]=useState<ActivityItem[]>([]);const[people,setPeople]=useState<OrganizationUser[]>([]);const[clients,setClients]=useState<Client[]>([]);const[services,setServices]=useState<ServiceDefinition[]>([]);const[loading,setLoading]=useState(true);const[editing,setEditing]=useState(false);const[showMember,setShowMember]=useState(false);const[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!params.projectId)return;setLoading(true);setError(null);try{const[p,m,a]=await Promise.all([authorizedRequest<Project>(`/projects/${params.projectId}`),authorizedRequest<ProjectMember[]>(`/projects/${params.projectId}/members`),authorizedRequest<ActivityItem[]>(`/projects/${params.projectId}/activity?size=100`)]);setProject(p);setMembers(m);setActivity(a)}catch(requestError){setError(message(requestError,"Project details could not be loaded."))}finally{setLoading(false)}},[authorizedRequest,params.projectId]);
  const loadPeople=useCallback(async()=>{if(!canReadUsers)return;try{setPeople(await authorizedRequest<OrganizationUser[]>("/organization-users?size=100"))}catch(requestError){setError(message(requestError,"Team members could not be loaded."))}},[authorizedRequest,canReadUsers]);
  const loadOptions=useCallback(async()=>{if(!hasPermission("CLIENT_READ")||!(hasPermission("SERVICE_READ")||hasPermission("SERVICE_MANAGE")))return;try{const[c,s]=await Promise.all([authorizedRequest<Client[]>("/clients?size=100"),authorizedRequest<ServiceDefinition[]>("/services?size=100")]);setClients(c.filter(x=>x.status!=="ARCHIVED"));setServices(s.filter(x=>x.status==="ACTIVE"))}catch(requestError){setError(message(requestError,"Editable project relationships could not be loaded."))}},[authorizedRequest,hasPermission]);
  useEffect(()=>{if(canRead)void load()},[canRead,load]);useEffect(()=>{if(showMember)void loadPeople()},[showMember,loadPeople]);useEffect(()=>{if(editing)void loadOptions()},[editing,loadOptions]);
  const personMap=useMemo(()=>new Map(people.map(person=>[person.membershipId,person])),[people]);

  async function transition(action:"cancel"|"hold"|"resume"|"archive") {if(!project)return;if((action==="cancel"||action==="archive")&&!confirm(`${action==="cancel"?"Cancel":"Archive"} ${project.name}?`))return;setError(null);try{const updated=await authorizedRequest<Project>(`/projects/${project.id}/${action}`,{method:"POST",body:JSON.stringify({version:project.version})});if(updated.status==="ARCHIVED"){router.push("/app/projects");return}setProject(updated);await load()}catch(requestError){setError(message(requestError,`Project could not be ${action}d.`))}}

  if(!canRead)return <PermissionState/>;
  if(loading)return <div className="panel flex min-h-64 items-center justify-center text-sm text-[hsl(var(--muted-foreground))]"><Loader2 className="mr-2 size-4 animate-spin"/>Loading project…</div>;
  if(!project)return <><Button asChild variant="ghost" className="mb-5"><Link href="/app/projects"><ArrowLeft className="size-4"/>Back to projects</Link></Button><div className="panel p-8">{error?<FormMessage>{error}</FormMessage>:<EmptyState title="Project not found" description="The project may be archived or outside your organization."/>}</div></>;

  const canHold=["ONBOARDING","READY","ACTIVE"].includes(project.status);const canResume=project.status==="ON_HOLD";const canCancel=["DRAFT","ONBOARDING","READY","ACTIVE","ON_HOLD"].includes(project.status);const canArchive=["CANCELLED","COMPLETED"].includes(project.status);
  return <>
    <Button asChild variant="ghost" className="mb-5 -ml-3"><Link href="/app/projects"><ArrowLeft className="size-4"/>Back to projects</Link></Button>
    <PageHeading eyebrow="Project core" title={project.name} description="Project lifecycle remains independent from onboarding, billing, contracts, and readiness. Each transition is validated by its owning domain and recorded for audit." actions={canUpdate?<div className="flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={()=>setEditing(v=>!v)}><Pencil className="size-4"/>Edit</Button>{canHold&&<Button variant="secondary" onClick={()=>void transition("hold")}><CirclePause className="size-4"/>Put on hold</Button>}{canResume&&<Button variant="secondary" onClick={()=>void transition("resume")}><Play className="size-4"/>Resume</Button>}{canCancel&&<Button variant="destructive" onClick={()=>void transition("cancel")}><XCircle className="size-4"/>Cancel</Button>}{canArchive&&<Button variant="secondary" onClick={()=>void transition("archive")}><Archive className="size-4"/>Archive</Button>}</div>:undefined}/>
    {error&&<div className="mb-5"><FormMessage>{error}</FormMessage></div>}
    <div className="grid gap-6 xl:grid-cols-[.82fr_1.18fr]">
      <div className="space-y-6">
        <section className="panel overflow-hidden"><div className="border-b px-5 py-4"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">Project profile</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Core commercial-delivery relationship</p></div><StatusBadge status={project.status}/></div></div>{editing?<ProjectEditor project={project} clients={clients} services={services} onDone={()=>{setEditing(false);void load()}} onError={setError}/>:<dl className="divide-y"><Fact label="Client">{project.clientName}</Fact><Fact label="Service">{project.serviceName}</Fact><Fact label="Description">{project.description||"No description provided."}</Fact><Fact label="Created">{formatDate(project.createdAt)}</Fact><Fact label="Record ID"><span className="break-all font-mono text-[11px]">{project.id}</span></Fact></dl>}</section>
        <OnboardingPanel project={project} onProjectChanged={()=>void load()}/>
        <section className="rounded-2xl border border-[hsl(var(--primary)/.16)] bg-[hsl(var(--primary-soft))] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[hsl(var(--primary))]">Lifecycle integrity</p><p className="mt-2 text-sm font-semibold">Readiness does not activate a project automatically.</p><p className="mt-1 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Final review completes onboarding and moves the project to READY. The separate READY → ACTIVE transition requires PROJECT_ACTIVATE.</p></section>
      </div>
      <div className="space-y-6">
        <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><p className="font-semibold">Project team</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Internal organization memberships assigned to this project</p></div>{canUpdate&&canReadUsers&&!["CANCELLED","COMPLETED","ARCHIVED"].includes(project.status)&&<Button size="sm" onClick={()=>setShowMember(v=>!v)}><Plus className="size-4"/>Add member</Button>}</div>{showMember&&<MemberCreator project={project} people={people} existing={members} onDone={()=>{setShowMember(false);void load()}} onCancel={()=>setShowMember(false)}/>} {members.length===0?<EmptyState title="No project members assigned" description="Assign internal teammates when responsibility for this project is known."/>:<div className="divide-y">{members.map(member=><MemberRow key={member.id} member={member} person={personMap.get(member.organizationUserId)} canRemove={canUpdate&&!["CANCELLED","COMPLETED","ARCHIVED"].includes(project.status)} onRemoved={()=>void load()} onError={setError}/>)}</div>}</section>
        <section className="panel overflow-hidden"><div className="flex items-center gap-3 border-b px-5 py-4"><div className="grid size-9 place-items-center rounded-lg bg-[hsl(var(--surface-subtle))]"><Activity className="size-4"/></div><div><p className="font-semibold">Activity timeline</p><p className="mt-0.5 text-xs text-[hsl(var(--muted-foreground))]">Tenant-scoped project changes recorded in chronological context</p></div></div>{activity.length===0?<EmptyState title="No activity recorded" description="Project changes will appear here as they happen."/>:<ol className="divide-y">{activity.map(item=><li key={item.id} className="grid gap-2 px-5 py-4 sm:grid-cols-[8.5rem_1fr]"><time className="text-xs text-[hsl(var(--muted-foreground))]">{formatDateTime(item.occurredAt)}</time><div><p className="text-sm font-medium">{item.summary}</p><p className="mt-1 text-[11px] font-semibold uppercase tracking-[.08em] text-[hsl(var(--muted-foreground))]">{item.action.replaceAll("_"," ")}</p></div></li>)}</ol>}</section>
      </div>
    </div>
  </>
}

function OnboardingPanel({project,onProjectChanged}:{project:Project;onProjectChanged:()=>void}){
  const{authorizedRequest,hasPermission}=useAuth();const router=useRouter();
  const canStart=hasPermission("ONBOARDING_START")&&(hasPermission("WORKFLOW_READ")||hasPermission("WORKFLOW_MANAGE"));const canRead=hasPermission("ONBOARDING_READ");const canReview=hasPermission("ONBOARDING_REVIEW")||hasPermission("ONBOARDING_APPROVE")||hasPermission("PROJECT_ACTIVATE");
  const[workflows,setWorkflows]=useState<WorkflowTemplateSummary[]>([]);const[selected,setSelected]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{if(project.status!=="DRAFT"||!canStart)return;void authorizedRequest<WorkflowTemplateSummary[]>("/workflow-templates?size=100").then(values=>setWorkflows(values.filter(value=>Boolean(value.latestPublishedVersionId)))).catch(requestError=>setError(message(requestError,"Published workflows could not be loaded.")))},[authorizedRequest,canStart,project.status]);
  async function start(){if(!selected)return;setBusy(true);setError(null);try{const onboarding=await authorizedRequest<Onboarding>(`/projects/${project.id}/onboarding`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({templateVersionId:selected,projectVersion:project.version})});onProjectChanged();if(canRead)router.push(`/app/projects/${project.id}/onboarding`)}catch(requestError){setError(message(requestError,"Onboarding could not be started."))}finally{setBusy(false)}}
  if(project.status==="DRAFT")return <section className="panel overflow-hidden"><div className="flex items-start gap-3 border-b bg-[hsl(var(--surface-subtle)/.55)] px-5 py-4"><div className="grid size-9 place-items-center rounded-xl bg-[hsl(var(--primary-soft))] text-[hsl(var(--primary))]"><GitBranch className="size-4"/></div><div><p className="font-semibold">Start onboarding</p><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Choose a published workflow version. The server snapshots it so later template edits cannot change this project.</p></div></div>{canStart?<div className="space-y-4 p-5"><div className="space-y-2"><Label htmlFor="project-workflow">Published workflow</Label><Select id="project-workflow" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a workflow</option>{workflows.map(workflow=><option key={workflow.id} value={workflow.latestPublishedVersionId??""}>{workflow.name} — v{workflow.latestPublishedVersion}</option>)}</Select></div>{workflows.length===0&&<p className="text-xs leading-5 text-[hsl(var(--muted-foreground))]">No published workflow is available yet. Publish one from the Workflow Builder first.</p>}{error&&<FormMessage>{error}</FormMessage>}<Button className="w-full" disabled={busy||!selected} onClick={()=>void start()}>{busy?<Loader2 className="size-4 animate-spin"/>:<Play className="size-4"/>}Create immutable onboarding snapshot</Button></div>:<div className="p-5 text-sm text-[hsl(var(--muted-foreground))]">You do not have permission to start onboarding for this project.</div>}</section>;
  if(["ONBOARDING","READY","ACTIVE"].includes(project.status))return <section className="panel p-5"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[hsl(var(--info-soft))] text-[hsl(var(--info))]"><GitBranch className="size-4.5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{project.status==="ONBOARDING"?"Onboarding workflow attached":project.status==="READY"?"Ready for activation":"Project active"}</p><StatusBadge status={project.status}/></div><p className="mt-1 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{project.status==="ONBOARDING"?"The immutable onboarding snapshot drives readiness and final review.":project.status==="READY"?"Final review is complete. Activation remains a separate privileged action.":"The project passed final review and the audited activation transition."}</p>{(canRead||canReview)&&<div className="mt-3 flex flex-wrap gap-2">{canRead&&<Button asChild variant="secondary" size="sm"><Link href={`/app/projects/${project.id}/onboarding`}>View workflow snapshot</Link></Button>}{project.status==="ONBOARDING"&&canStart&&canRead&&<Button asChild variant="secondary" size="sm"><Link href={`/app/projects/${project.id}/client-access`}>Manage client access</Link></Button>}{canReview&&<Button asChild size="sm"><Link href={`/app/projects/${project.id}/review`}>{project.status==="READY"?"Activate project":"Open final review"}</Link></Button>}</div>}</div></div></section>;
  return null;
}

function ProjectEditor({project,clients,services,onDone,onError}:{project:Project;clients:Client[];services:ServiceDefinition[];onDone:()=>void;onError:(value:string|null)=>void}){const{authorizedRequest}=useAuth();const[name,setName]=useState(project.name);const[description,setDescription]=useState(project.description??"");const[clientId,setClientId]=useState(project.clientId);const[serviceId,setServiceId]=useState(project.serviceId);const[busy,setBusy]=useState(false);const relationshipsEditable=project.status==="DRAFT";async function save(event:React.FormEvent){event.preventDefault();setBusy(true);onError(null);try{await authorizedRequest(`/projects/${project.id}`,{method:"PATCH",body:JSON.stringify({clientId,serviceId,name,description:description||null,version:project.version})});onDone()}catch(error){onError(message(error,"Project could not be updated."))}finally{setBusy(false)}}return <form onSubmit={save} className="space-y-4 p-5"><div className="space-y-2"><Label htmlFor="project-edit-name">Project name</Label><Input id="project-edit-name" value={name} onChange={e=>setName(e.target.value)} required maxLength={180}/></div>{relationshipsEditable&&clients.length>0&&services.length>0?<div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="project-edit-client">Client</Label><Select id="project-edit-client" value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></div><div className="space-y-2"><Label htmlFor="project-edit-service">Service</Label><Select id="project-edit-service" value={serviceId} onChange={e=>setServiceId(e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></div></div>:<p className="rounded-xl bg-[hsl(var(--surface-subtle))] p-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Client and service relationships are immutable after DRAFT. Existing relationship IDs are preserved on this edit.</p>}<div className="space-y-2"><Label htmlFor="project-edit-description">Description</Label><Textarea id="project-edit-description" value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000}/></div><div className="flex justify-end"><Button disabled={busy||!name.trim()}>{busy?<Loader2 className="size-4 animate-spin"/>:<Save className="size-4"/>}Save project</Button></div></form>}

function MemberCreator({project,people,existing,onDone,onCancel}:{project:Project;people:OrganizationUser[];existing:ProjectMember[];onDone:()=>void;onCancel:()=>void}){const{authorizedRequest}=useAuth();const existingIds=new Set(existing.map(x=>x.organizationUserId));const options=people.filter(person=>person.status==="ACTIVE"&&!existingIds.has(person.membershipId));const[membershipId,setMembershipId]=useState("");const[responsibility,setResponsibility]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError(null);try{await authorizedRequest(`/projects/${project.id}/members`,{method:"POST",body:JSON.stringify({organizationUserId:membershipId,responsibility:responsibility||null})});onDone()}catch(requestError){setError(message(requestError,"Project member could not be added."))}finally{setBusy(false)}}return <form onSubmit={save} className="border-b bg-[hsl(var(--surface-subtle))] p-5"><div className="grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div className="space-y-2"><Label htmlFor="project-member">Person</Label><Select id="project-member" value={membershipId} onChange={e=>setMembershipId(e.target.value)} required><option value="">Choose a teammate</option>{options.map(person=><option key={person.membershipId} value={person.membershipId}>{person.displayName} — {person.email}</option>)}</Select></div><div className="space-y-2"><Label htmlFor="member-responsibility">Responsibility</Label><Input id="member-responsibility" value={responsibility} onChange={e=>setResponsibility(e.target.value)} maxLength={120} placeholder="Account lead"/></div><div className="flex gap-2"><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button><Button disabled={busy||!membershipId}>{busy&&<Loader2 className="size-4 animate-spin"/>}Add</Button></div></div>{options.length===0&&<p className="mt-3 text-xs text-[hsl(var(--muted-foreground))]">Every active visible teammate is already assigned.</p>}{error&&<div className="mt-3"><FormMessage>{error}</FormMessage></div>}</form>}

function MemberRow({member,person,canRemove,onRemoved,onError}:{member:ProjectMember;person?:OrganizationUser;canRemove:boolean;onRemoved:()=>void;onError:(value:string|null)=>void}){const{authorizedRequest}=useAuth();const[busy,setBusy]=useState(false);async function remove(){setBusy(true);onError(null);try{await authorizedRequest(`/projects/${member.projectId}/members/${member.id}`,{method:"DELETE"});onRemoved()}catch(error){onError(message(error,"Project member could not be removed."))}finally{setBusy(false)}}return <div className="flex items-center gap-3 px-5 py-4"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-[hsl(var(--surface-subtle))]"><UsersRound className="size-4"/></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{person?.displayName??"Assigned organization member"}</p><div className="mt-1 flex flex-wrap gap-2 text-xs text-[hsl(var(--muted-foreground))]">{person?.email&&<span>{person.email}</span>}{member.responsibility&&<Badge>{member.responsibility}</Badge>}{!person&&<span className="font-mono text-[10px]">{member.organizationUserId}</span>}</div></div>{canRemove&&<Button variant="ghost" size="icon" onClick={()=>void remove()} disabled={busy} aria-label="Remove project member">{busy?<Loader2 className="size-4 animate-spin"/>:<Trash2 className="size-4"/>}</Button>}</div>}
function Fact({label,children}:{label:string;children:React.ReactNode}){return <div className="grid grid-cols-[7rem_1fr] gap-4 px-5 py-4"><dt className="text-xs font-medium text-[hsl(var(--muted-foreground))]">{label}</dt><dd className="text-sm leading-6">{children}</dd></div>}
function formatDate(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value))}
function formatDateTime(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function message(error:unknown,fallback:string){return error instanceof ApiClientError?error.message:fallback}
