package com.brainserve.onboarding.forms.domain.model;
import com.fasterxml.jackson.databind.JsonNode; import jakarta.persistence.*; import java.time.Instant; import java.util.Locale; import java.util.UUID; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes;
@Entity @Table(name="form_fields",schema="client_onboarding")
public class FormField {
 @Id private UUID id; @Column(name="organization_id",nullable=false) private UUID organizationId; @Column(name="form_version_id",nullable=false) private UUID formVersionId; @Column(name="field_key",nullable=false,length=80) private String fieldKey; @Column(nullable=false,length=220) private String label; @Column(name="help_text",length=1000) private String helpText; @Enumerated(EnumType.STRING) @Column(name="field_type",nullable=false,length=24) private FormFieldType fieldType; @Column(name="display_order",nullable=false) private int displayOrder; @Column(nullable=false) private boolean required; @JdbcTypeCode(SqlTypes.JSON) @Column(name="condition_expression",nullable=false,columnDefinition="jsonb") private JsonNode conditionExpression; @JdbcTypeCode(SqlTypes.JSON) @Column(name="configuration_json",nullable=false,columnDefinition="jsonb") private JsonNode configurationJson; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="created_by",nullable=false) private UUID createdBy; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="updated_by",nullable=false) private UUID updatedBy; @Version private long version;
 protected FormField(){} public FormField(UUID id,UUID org,UUID version,String key,String label,String help,FormFieldType type,int order,boolean required,JsonNode condition,JsonNode config,UUID actor,Instant now){this.id=id;organizationId=org;formVersionId=version;fieldKey=normalizeKey(key);this.label=FormTemplate.text(label,"Field label",220);helpText=FormTemplate.optional(help,1000);fieldType=java.util.Objects.requireNonNull(type);if(order<0)throw new IllegalArgumentException("Display order cannot be negative");displayOrder=order;this.required=required;conditionExpression=condition.deepCopy();configurationJson=config.deepCopy();createdAt=now;createdBy=actor;updatedAt=now;updatedBy=actor;}
 public static String normalizeKey(String input){if(input==null)throw new IllegalArgumentException("Field key is required");String v=input.trim().toUpperCase(Locale.ROOT).replaceAll("[^A-Z0-9]+","_").replaceAll("^_+|_+$","");if(v.isBlank()||v.length()>80)throw new IllegalArgumentException("Field key is invalid");return v;}
 public UUID getId(){return id;} public UUID getOrganizationId(){return organizationId;} public UUID getFormVersionId(){return formVersionId;} public String getFieldKey(){return fieldKey;} public String getLabel(){return label;} public String getHelpText(){return helpText;} public FormFieldType getFieldType(){return fieldType;} public int getDisplayOrder(){return displayOrder;} public boolean isRequired(){return required;} public JsonNode getConditionExpression(){return conditionExpression.deepCopy();} public JsonNode getConfigurationJson(){return configurationJson.deepCopy();} public long getVersion(){return version;}
}
