package com.brainserve.onboarding.forms.domain.model;
import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="form_versions",schema="client_onboarding")
public class FormTemplateVersion {
 @Id private UUID id; @Column(name="organization_id",nullable=false) private UUID organizationId; @Column(name="form_id",nullable=false) private UUID formId; @Column(name="version_number",nullable=false) private int versionNumber; @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private FormVersionStatus status; @Column(name="change_note",length=500) private String changeNote; @Column(name="published_at") private Instant publishedAt; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="created_by",nullable=false) private UUID createdBy; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="updated_by",nullable=false) private UUID updatedBy; @Version private long version;
 protected FormTemplateVersion(){} public FormTemplateVersion(UUID id,UUID org,UUID formId,int number,String note,UUID actor,Instant now){this.id=id;organizationId=org;this.formId=formId;versionNumber=number;status=FormVersionStatus.DRAFT;changeNote=FormTemplate.optional(note,500);createdAt=now;createdBy=actor;updatedAt=now;updatedBy=actor;}
 public void revise(String note,UUID actor,Instant now){requireDraft();changeNote=FormTemplate.optional(note,500);updatedBy=actor;updatedAt=now;} public void publish(UUID actor,Instant now){requireDraft();status=FormVersionStatus.PUBLISHED;publishedAt=now;updatedBy=actor;updatedAt=now;} public void requireDraft(){if(status!=FormVersionStatus.DRAFT)throw new IllegalStateException("Published form versions are immutable");}
 public UUID getId(){return id;} public UUID getOrganizationId(){return organizationId;} public UUID getFormId(){return formId;} public int getVersionNumber(){return versionNumber;} public FormVersionStatus getStatus(){return status;} public String getChangeNote(){return changeNote;} public Instant getPublishedAt(){return publishedAt;} public Instant getUpdatedAt(){return updatedAt;} public long getVersion(){return version;}
}
