package com.brainserve.onboarding.forms.domain.model;
import jakarta.persistence.*; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="forms",schema="client_onboarding")
public class FormTemplate {
 @Id private UUID id; @Column(name="organization_id",nullable=false) private UUID organizationId; @Column(nullable=false,length=180) private String name; @Column(length=1000) private String description;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=24) private FormStatus status; @Column(name="archived_at") private Instant archivedAt; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="created_by",nullable=false) private UUID createdBy; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="updated_by",nullable=false) private UUID updatedBy; @Version private long version;
 protected FormTemplate(){} public FormTemplate(UUID id,UUID org,String name,String description,UUID actor,Instant now){this.id=id;this.organizationId=org;this.name=text(name,"Form name",180);this.description=optional(description,1000);this.status=FormStatus.ACTIVE;this.createdAt=now;this.createdBy=actor;this.updatedAt=now;this.updatedBy=actor;}
 public void update(String name,String description,UUID actor,Instant now){if(status!=FormStatus.ACTIVE)throw new IllegalStateException("Archived forms cannot be edited");this.name=text(name,"Form name",180);this.description=optional(description,1000);updatedBy=actor;updatedAt=now;} public void archive(UUID actor,Instant now){if(status==FormStatus.ARCHIVED)return;status=FormStatus.ARCHIVED;archivedAt=now;updatedBy=actor;updatedAt=now;}
 public UUID getId(){return id;} public UUID getOrganizationId(){return organizationId;} public String getName(){return name;} public String getDescription(){return description;} public FormStatus getStatus(){return status;} public Instant getArchivedAt(){return archivedAt;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;} public long getVersion(){return version;}
 public static String text(String v,String label,int max){if(v==null||v.trim().isEmpty())throw new IllegalArgumentException(label+" is required");String n=v.trim();if(n.length()>max)throw new IllegalArgumentException(label+" is too long");return n;} public static String optional(String v,int max){if(v==null||v.isBlank())return null;String n=v.trim();if(n.length()>max)throw new IllegalArgumentException("Text is too long");return n;}
}
