"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ExternalLink, Loader2, ReceiptText, ShieldCheck } from "lucide-react";
import { useClientAuth } from "@/auth/client-auth-provider";
import { StatusBadge } from "@/components/shared/status-badge";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ApiClientError } from "@/services/api-client";
import type { ClientInvoice, PaymentSession } from "@/types/billing";

export default function ClientInvoiceDetailPage(){
  const{projectId,invoiceId}=useParams<{projectId:string;invoiceId:string}>();
  const{authorizedRequest}=useClientAuth();
  const[data,setData]=useState<ClientInvoice|null>(null);const[loading,setLoading]=useState(true);const[paying,setPaying]=useState(false);const[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const value=await authorizedRequest<ClientInvoice>(`/client-portal/projects/${projectId}/invoices/${invoiceId}/view`,{method:"POST"});setData(value)}catch(e){setError(e instanceof ApiClientError?e.message:"Invoice could not be loaded.")}finally{setLoading(false)}},[authorizedRequest,projectId,invoiceId]);
  useEffect(()=>{void load()},[load]);
  async function pay(){setPaying(true);setError(null);try{const session=await authorizedRequest<PaymentSession>(`/client-portal/projects/${projectId}/invoices/${invoiceId}/payment-session`,{method:"POST",headers:{"Idempotency-Key":`portal-${invoiceId}-${Date.now()}`},body:JSON.stringify({})});const url=safeCheckout(session.checkoutUrl);if(!url)throw new Error("Unsafe checkout URL returned by payment provider.");window.location.assign(url)}catch(e){setError(e instanceof Error?e.message:"Payment could not be started.");setPaying(false)}}
  if(loading)return <div className="grid min-h-72 place-items-center text-sm text-[hsl(var(--muted-foreground))]"><span className="flex items-center gap-2"><Loader2 className="size-4 animate-spin"/>Loading invoice…</span></div>;
  if(error&&!data)return <div className="panel p-6"><p className="font-semibold">Invoice unavailable</p><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{error}</p></div>;
  if(!data)return null;const payable=data.balanceDueMinor>0&&!['PAID','VOID','CANCELLED','REFUNDED'].includes(data.status);
  return <div className="mx-auto max-w-5xl"><Button asChild variant="ghost" size="sm" className="mb-5 -ml-2"><Link href={`/portal/projects/${projectId}/invoices`}><ArrowLeft className="size-4"/>Invoices</Link></Button><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[hsl(var(--primary))]"><ReceiptText className="size-4"/>Invoice</div><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">{data.invoiceNumber}</h1><div className="mt-3 flex flex-wrap gap-2"><StatusBadge status={data.status}/><Badge variant="neutral">{data.paymentPolicy.replaceAll('_',' ')}</Badge></div></div>{payable&&<Button onClick={()=>void pay()} disabled={paying}>{paying?<Loader2 className="size-4 animate-spin"/>:<ExternalLink className="size-4"/>}Pay securely</Button>}</header>{error&&<div className="mb-5 rounded-xl border p-4 text-sm">{error}</div>}<div className="grid gap-5 lg:grid-cols-[1fr_22rem]"><section className="panel overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Invoice items</h2></div><div className="divide-y">{data.items.map(item=><div key={item.id} className="grid grid-cols-[1fr_auto] gap-4 p-5"><div><p className="font-medium">{item.description}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{item.quantity} × {money(item.unitAmountMinor,data.currency)}</p></div><p className="font-semibold">{money(item.lineTotalMinor,data.currency)}</p></div>)}</div>{data.memo&&<div className="border-t p-5"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))]">Note</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{data.memo}</p></div>}</section><aside className="space-y-4"><div className="panel p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[hsl(var(--muted-foreground))]">Payment summary</p><Summary label="Total" value={money(data.totalMinor,data.currency)}/><Summary label="Paid" value={money(data.amountPaidMinor,data.currency)}/><Summary label="Refunded" value={money(data.amountRefundedMinor,data.currency)}/><div className="mt-4 border-t pt-4"><Summary label="Remaining" value={money(data.balanceDueMinor,data.currency)} strong/></div>{data.dueAt&&<p className="mt-4 text-xs text-[hsl(var(--muted-foreground))]">Due {date(data.dueAt)}</p>}</div><div className="rounded-2xl border bg-[hsl(var(--surface-subtle))] p-4"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-4"/>Payment security</div><p className="mt-2 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Checkout opens only through the configured payment provider. Payment status is updated from verified provider events rather than browser redirects.</p></div></aside></div></div>;
}
function Summary({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className="mt-3 flex items-center justify-between gap-3"><span className="text-sm text-[hsl(var(--muted-foreground))]">{label}</span><span className={strong?"text-lg font-semibold":"text-sm font-semibold"}>{value}</span></div>}
function money(value:number,currency:string){try{return new Intl.NumberFormat(undefined,{style:"currency",currency}).format(value/100)}catch{return `${currency} ${(value/100).toFixed(2)}`}}
function date(value:string){return new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value))}
function safeCheckout(value:string){try{const u=new URL(value,window.location.origin);if(u.protocol==="https:")return u.toString();if((u.hostname==="localhost"||u.hostname==="127.0.0.1")&&u.protocol==="http:")return u.toString();return null}catch{return null}}
