"use client";
import { useEffect, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useCurrentUser } from "@/features/settings/internal-shell";
import { assetsApi } from "./assets-api";
import { control, fileSize, mimeLabels, type AssetRequirement } from "./types";

export function AssetRequirements() {
  const user = useCurrentUser(); const canManage = user.permissions.includes("ASSET_MANAGE");
  const allowed = canManage || user.permissions.some((p) => ["ASSET_READ", "ASSET_REVIEW"].includes(p));
  const [rows, setRows] = useState<AssetRequirement[]>(); const [search, setSearch] = useState(""); const [page, setPage] = useState(0);
  const [name, setName] = useState(""); const [instructions, setInstructions] = useState(""); const [mimes, setMimes] = useState(["application/pdf"]); const [limit, setLimit] = useState(10);
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false); const [revision, setRevision] = useState(0); const [confirm, setConfirm] = useState<string>();
  useEffect(() => { if (!allowed) return; let active = true; const timer = setTimeout(() => assetsApi.list(search, page).then((value) => { if (active) { setRows(value); setError(""); } }).catch((e) => { if (active) setError(e.message); }), 250); return () => { active = false; clearTimeout(timer); }; }, [allowed, search, page, revision]);
  async function create(event: React.FormEvent) { event.preventDefault(); setPending(true); setError(""); try { await assetsApi.create(name, instructions, mimes, Math.round(limit * 1048576)); setName(""); setInstructions(""); setPage(0); setRevision((n) => n + 1); setMessage("Requirement created. Attach it to a file upload step in Workflows."); } catch (e) { setError(e instanceof Error ? e.message : "The requirement could not be created."); } finally { setPending(false); } }
  async function archive(row: AssetRequirement) { setPending(true); setError(""); try { await assetsApi.archive(row.id, row.version); setConfirm(undefined); setRevision((n) => n + 1); setMessage("Requirement archived. Existing project files remain available."); } catch (e) { setError(e instanceof Error ? e.message : "The requirement could not be archived."); } finally { setPending(false); } }
  if (!allowed) return <Alert>You do not have permission to read asset requirements.</Alert>;
  return <><h1 className="max-w-5xl text-3xl font-bold tracking-tight sm:text-4xl">Asset requirements</h1><p className="mt-3 max-w-2xl text-muted-foreground">Tell clients which files to provide and how to prepare them. Attach each requirement to a file upload step in a workflow.</p>
    {error && <Alert className="mt-5" tone="error">{error}</Alert>}{message && <Alert className="mt-5" tone="success">{message}</Alert>}
    <div className="mt-8 grid grid-flow-dense gap-6 lg:grid-cols-12"><section className={canManage ? "min-w-0 lg:col-span-7" : "min-w-0 lg:col-span-12"} aria-label="Asset requirements"><label htmlFor="asset-search" className="text-sm font-semibold">Search requirements</label><Input id="asset-search" className="mt-2" value={search} maxLength={180} onChange={(e) => { setSearch(e.target.value); setPage(0); }} />
      {!rows ? <p className="mt-6" aria-busy="true">Loading requirements…</p> : !rows.length ? <Card className="mt-5"><h2 className="font-bold">No requirements found</h2><p className="mt-2 text-sm text-muted-foreground">{search ? "Try a different search." : "Create a requirement for a logo, document, image or video."}</p></Card> : <ul className="mt-5 space-y-3">{rows.map((row) => <li key={row.id}><Card><h2 className="font-bold [overflow-wrap:anywhere]">{row.name}</h2><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground [overflow-wrap:anywhere]">{row.instructions}</p><p className="mt-3 text-sm">{row.allowedMimes.map((m) => mimeLabels[m]).join(", ")} · Up to {fileSize(row.maxBytes)}</p>{canManage && <div className="mt-4">{confirm === row.id ? <><p className="mb-3 text-sm">Archive this requirement? Existing projects keep their files and rules.</p><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={pending} onClick={() => archive(row)}>Confirm archive</Button><Button variant="ghost" onClick={() => setConfirm(undefined)}>Keep requirement</Button></div></> : <Button variant="ghost" disabled={pending} onClick={() => setConfirm(row.id)}>Archive {row.name}</Button>}</div>}</Card></li>)}</ul>}
      <div className="mt-5 flex gap-3"><Button variant="outline" disabled={pending || page === 0} onClick={() => setPage(page - 1)}>Previous requirements</Button><Button variant="outline" disabled={pending || !rows || rows.length < 20} onClick={() => setPage(page + 1)}>More requirements</Button></div></section>
      {canManage && <Card className="h-fit lg:col-span-5"><h2 className="text-xl font-bold">Create a requirement</h2><p className="mt-2 text-sm text-muted-foreground">Requirements keep their original rules. Create a new one when file types or size limits change.</p><form className="mt-5 space-y-4" onSubmit={create}><label className="block text-sm font-semibold">Requirement name<Input className="mt-2" required maxLength={180} value={name} onChange={(e) => setName(e.target.value)} /></label><label className="block text-sm font-semibold">Instructions<textarea className={`${control} min-h-24`} value={instructions} maxLength={2000} onChange={(e) => setInstructions(e.target.value)} /></label><fieldset><legend className="text-sm font-semibold">Permitted file types</legend><div className="mt-2">{Object.entries(mimeLabels).map(([mime, label]) => <label key={mime} className="flex min-h-11 cursor-pointer items-center gap-3 text-sm"><input type="checkbox" className="size-4 accent-primary" checked={mimes.includes(mime)} onChange={(e) => setMimes((v) => e.target.checked ? [...v, mime] : v.filter((m) => m !== mime))} />{label}</label>)}</div></fieldset><label className="block text-sm font-semibold">Maximum file size (MiB)<Input className="mt-2" type="number" min={1} max={50} required value={limit} onChange={(e) => setLimit(Number(e.target.value))} /></label><Button type="submit" disabled={pending || !mimes.length}>{pending ? "Creating…" : "Create requirement"}</Button></form></Card>}</div></>;
}

export function AssetRequirementPicker({ value, disabled, onChange }: { value?: string; disabled: boolean; onChange: (id: string) => void }) {
  const [rows, setRows] = useState<AssetRequirement[]>([]); const [search, setSearch] = useState(""); const [page, setPage] = useState(0); const [error, setError] = useState("");
  useEffect(() => { if (disabled) return; let active = true; const timer = setTimeout(() => assetsApi.list(search, page).then((v) => { if (active) { setRows(v); setError(""); } }).catch((e) => { if (active) setError(e.message); }), 250); return () => { active = false; clearTimeout(timer); }; }, [search, page, disabled]);
  if (disabled) return <p className="mt-5 text-sm text-muted-foreground">{value ? "An immutable asset requirement is attached." : "No asset requirement attached."}</p>;
  return <fieldset className="mt-5 rounded-lg border p-4"><legend className="px-1 text-sm font-bold">File upload requirement</legend>{error && <Alert tone="error">{error}</Alert>}<label className="block text-sm font-semibold">Find an asset requirement<Input className="mt-2" value={search} maxLength={180} onChange={(e) => { setSearch(e.target.value); setPage(0); }} /></label><label className="mt-3 block text-sm font-semibold">Asset requirement<select className={control} value={value ?? ""} onChange={(e) => onChange(e.target.value)}><option value="">Select a requirement</option>{value && !rows.some((r) => r.id === value) && <option value={value}>Previously selected requirement</option>}{rows.map((r) => <option key={r.id} value={r.id}>{r.name} · {fileSize(r.maxBytes)}</option>)}</select></label><div className="mt-3 flex flex-wrap gap-2"><Button variant="ghost" disabled={page === 0} onClick={() => setPage(page - 1)}>Previous requirements</Button><Button variant="ghost" disabled={rows.length < 20} onClick={() => setPage(page + 1)}>More requirements</Button></div><p className="mt-2 text-sm text-muted-foreground">Create requirements in Assets. Each step accepts one file with replacement history.</p></fieldset>;
}
