package com.brainserve.onboarding.contracts.infrastructure.provider;

import com.brainserve.onboarding.common.util.CryptoSupport;
import com.brainserve.onboarding.contracts.infrastructure.config.ContractProperties;
import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;import java.time.Instant;import java.util.*;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import org.springframework.stereotype.Component;

@Component
public class SignedSandboxESignatureProvider implements ESignatureProvider{
 private static final String TS="x-contract-timestamp", SIG="x-contract-signature";private final ContractProperties props;private final ObjectMapper mapper;
 public SignedSandboxESignatureProvider(ContractProperties props,ObjectMapper mapper){this.props=props;this.mapper=mapper;}
 public String providerCode(){return "SIGNED_SANDBOX";}public boolean available(){return providerCode().equals(props.provider())&&secret().length>=32;}
 public void voidDocument(String providerDocumentId,String reason){if(!available())throw new IllegalStateException("Contract provider unavailable");if(providerDocumentId==null||providerDocumentId.isBlank())throw new IllegalArgumentException("Provider document id is required");}
 public SendResult send(SendCommand c){String stable=c.organizationId()+":"+c.contractId()+":"+c.idempotencyKey();String doc="doc_"+UUID.nameUUIDFromBytes(stable.getBytes(StandardCharsets.UTF_8)).toString().replace("-","");Map<String,String> ids=new LinkedHashMap<>();for(var r:c.recipients())ids.put(r.email().toLowerCase(Locale.ROOT),"recipient_"+UUID.nameUUIDFromBytes((stable+":"+r.email()).getBytes(StandardCharsets.UTF_8)).toString().replace("-",""));String sep=props.signingBaseUrl().contains("?")?"&":"?";return new SendResult(doc,props.signingBaseUrl()+sep+"documentId="+doc+"&contractId="+c.contractId(),ids);}
 public VerifiedCallback verifyWebhook(byte[] body,Map<String,String> headers,Instant now){if(!available())throw new SecurityException("Contract provider unavailable");String ts=header(headers,TS),sig=header(headers,SIG);long seconds;try{seconds=Long.parseLong(ts);}catch(RuntimeException ex){throw new SecurityException("Invalid contract webhook timestamp",ex);}Instant stamp=Instant.ofEpochSecond(seconds);if(stamp.isBefore(now.minus(props.webhookMaxAge()))||stamp.isAfter(now.plusSeconds(60)))throw new SecurityException("Contract webhook timestamp outside replay window");byte[] supplied;try{supplied=HexFormat.of().parseHex(sig.trim().toLowerCase(Locale.ROOT));}catch(RuntimeException ex){throw new SecurityException("Invalid contract webhook signature",ex);}if(!CryptoSupport.constantTimeEquals(hmac(ts+"."+new String(body,StandardCharsets.UTF_8)),supplied))throw new SecurityException("Invalid contract webhook signature");try{JsonNode root=mapper.readTree(body);return new VerifiedCallback(text(root,"eventId",180),text(root,"eventType",80),uuid(root,"organizationId"),uuid(root,"contractId"),uuid(root,"contractVersionId"),text(root,"providerDocumentId",180),optional(root,"providerSignatureId",180),optional(root,"recipientEmail",320),optional(root,"signatoryName",160),Instant.parse(text(root,"occurredAt",80)));}catch(SecurityException ex){throw ex;}catch(Exception ex){throw new IllegalArgumentException("Invalid contract webhook payload",ex);}}
 public SignedDocument downloadSignedDocument(String providerDocumentId){String safe=providerDocumentId==null?"unknown":providerDocumentId.replaceAll("[^A-Za-z0-9_-]","");String pdf="%PDF-1.4\n% Signed contract sandbox artifact\n1 0 obj<< /Type /Catalog >>endobj\n% "+safe+"\n%%EOF\n";return new SignedDocument(pdf.getBytes(StandardCharsets.UTF_8),"application/pdf");}
 public SignedWebhook signedEvent(String eventType,UUID org,UUID contractId,UUID versionId,String documentId,String recipientEmail,String signatoryName,Instant now){try{Map<String,Object> p=new LinkedHashMap<>();p.put("eventId","cevt_"+UUID.randomUUID().toString().replace("-",""));p.put("eventType",eventType);p.put("organizationId",org);p.put("contractId",contractId);p.put("contractVersionId",versionId);p.put("providerDocumentId",documentId);p.put("providerSignatureId","sig_"+UUID.randomUUID().toString().replace("-",""));if(recipientEmail!=null)p.put("recipientEmail",recipientEmail);if(signatoryName!=null)p.put("signatoryName",signatoryName);p.put("occurredAt",now.toString());byte[] body=mapper.writeValueAsBytes(p);String ts=Long.toString(now.getEpochSecond());return new SignedWebhook(body,Map.of(TS,ts,SIG,HexFormat.of().formatHex(hmac(ts+"."+new String(body,StandardCharsets.UTF_8)))));}catch(Exception ex){throw new IllegalStateException(ex);}}
 private byte[] hmac(String v){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret(),"HmacSHA256"));return mac.doFinal(v.getBytes(StandardCharsets.UTF_8));}catch(Exception ex){throw new IllegalStateException(ex);}}
 private byte[] secret(){if(props.webhookSecretBase64()==null||props.webhookSecretBase64().isBlank())return new byte[0];try{return Base64.getDecoder().decode(props.webhookSecretBase64().trim());}catch(IllegalArgumentException ex){throw new IllegalStateException("Contract webhook secret must be Base64",ex);}}
 private static String header(Map<String,String> h,String k){return h.entrySet().stream().filter(e->e.getKey().equalsIgnoreCase(k)).map(Map.Entry::getValue).filter(v->v!=null&&!v.isBlank()).findFirst().orElseThrow(()->new SecurityException("Required contract webhook header missing"));}
 private static String text(JsonNode r,String n,int m){String v=optional(r,n,m);if(v==null)throw new IllegalArgumentException(n+" is required");return v;}private static String optional(JsonNode r,String n,int m){JsonNode x=r.get(n);if(x==null||x.isNull())return null;if(!x.isTextual())throw new IllegalArgumentException(n+" must be text");String v=x.asText().trim();if(v.isBlank())return null;if(v.length()>m)throw new IllegalArgumentException(n+" too long");return v;}private static UUID uuid(JsonNode r,String n){return UUID.fromString(text(r,n,64));}
 public record SignedWebhook(byte[] body,Map<String,String> headers){}
}
