"use client";

import { Plus, RefreshCw, Save, Send } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Alert } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import { ApiClientError } from "@/lib/api-client";
import { useCurrentUser } from "./internal-shell";
import { settingsApi } from "./settings-api";
import type { AuditEntry, Member, Organization, Role } from "./types";

function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-sm font-bold uppercase tracking-[0.15em] text-primary">{eyebrow}</p><h1 className="mt-3 text-3xl font-bold tracking-[-0.035em] sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{description}</p></div>; }
function Pending() { return <div className="mt-9 rounded-xl border p-5" aria-busy="true" aria-label="Loading settings"><p className="text-sm text-muted-foreground">Loading settings…</p><div className="mt-5 space-y-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="h-14 animate-pulse rounded-lg bg-muted" />)}</div></div>; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="mt-8"><Alert tone="error">{message}</Alert><Button className="mt-4" variant="outline" onClick={retry}><RefreshCw aria-hidden="true" />Retry</Button></div>; }
const errorMessage = (error: unknown) => error instanceof ApiClientError ? `${error.message}${error.requestId ? ` Request ${error.requestId}.` : ""}` : "The request could not be completed.";

export function OrganizationSettings() {
  const user = useCurrentUser(); const [item, setItem] = useState<Organization>(); const [name, setName] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [pending, setPending] = useState(false);
  const load = () => { settingsApi.organization(user.organizationId).then((value) => { setItem(value); setName(value.name); }).catch((cause) => setError(errorMessage(cause))); };
  useEffect(load, [user.organizationId]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!item) return; setPending(true); setError(""); setSuccess(""); try { const updated = await settingsApi.updateOrganization(item.id, name, item.version); setItem(updated); setSuccess("Organization profile saved."); } catch (cause) { setError(errorMessage(cause)); } finally { setPending(false); } }
  return <><Header eyebrow="Tenant profile" title="Organization" description="This profile identifies the tenant boundary used by every protected repository query." />{error && !item ? <ErrorState message={error} retry={load} /> : !item ? <Pending /> : <Card className="mt-9 max-w-2xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Workspace profile</h2><p className="mt-1 text-sm text-muted-foreground">Slug: <code className="font-mono">{item.slug}</code></p></div><Badge tone="success">{item.status}</Badge></div>{error && <Alert tone="error" className="mt-5">{error}</Alert>}{success && <Alert tone="success" className="mt-5">{success}</Alert>}<form onSubmit={submit} className="mt-6 space-y-5"><FormField label="Organization name" htmlFor="name"><Input id="name" required maxLength={160} value={name} onChange={(event) => setName(event.target.value)} /></FormField><Button type="submit" disabled={pending || name.trim() === item.name}><Save aria-hidden="true" />{pending ? "Saving…" : "Save changes"}</Button></form></Card>}</>;
}

export function MemberSettings() {
  const [members, setMembers] = useState<Member[]>(); const [roles, setRoles] = useState<Role[]>([]); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [roleId, setRoleId] = useState("");
  const load = () => { Promise.all([settingsApi.members(), settingsApi.roles()]).then(([memberData, roleData]) => { setMembers(memberData); setRoles(roleData.filter((role) => !role.archivedAt)); setRoleId((value) => value || roleData.find((role) => !role.archivedAt)?.id || ""); }).catch((cause) => setError(errorMessage(cause))); };
  useEffect(load, []);
  async function invite(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); try { await settingsApi.inviteMember(email, name, roleId); setEmail(""); setName(""); load(); } catch (cause) { setError(errorMessage(cause)); } finally { setPending(false); } }
  return <><Header eyebrow="Access roster" title="Members" description="Invite internal users, assign one explicit role, and review membership status inside this organization." />{error && <Alert tone="error" className="mt-7">{error}</Alert>}<Card className="mt-8"><h2 className="text-lg font-bold">Invite a member</h2><form onSubmit={invite} className="mt-5 grid gap-4 md:grid-cols-2"><FormField label="Full name" htmlFor="member-name"><Input id="member-name" required maxLength={160} value={name} onChange={(event) => setName(event.target.value)} /></FormField><FormField label="Work email" htmlFor="member-email"><Input id="member-email" required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} /></FormField><div><label htmlFor="member-role" className="mb-2 block text-sm font-semibold">Role</label><select id="member-role" required className="h-12 w-full cursor-pointer rounded-md border bg-background px-3.5 text-base" value={roleId} onChange={(event) => setRoleId(event.target.value)}>{roles.map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select></div><div className="flex items-end"><Button type="submit" className="w-full md:w-auto" disabled={pending || !roleId}><Send aria-hidden="true" />{pending ? "Sending…" : "Send invitation"}</Button></div></form></Card>{!members ? <Pending /> : members.length === 0 ? <Card className="mt-5"><h2 className="font-semibold">No members yet</h2><p className="mt-2 text-sm text-muted-foreground">Use the invitation form to add the first teammate.</p></Card> : <div className="mt-5 overflow-hidden rounded-xl border bg-card"><div className="hidden grid-cols-[1fr_1fr_9rem] gap-4 border-b bg-muted/50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-muted-foreground md:grid"><span>Member</span><span>Role</span><span>Status</span></div>{members.map((member) => <div key={member.id} className="grid gap-3 border-b px-5 py-4 last:border-b-0 md:grid-cols-[1fr_1fr_9rem] md:items-center"><div className="min-w-0"><p className="truncate font-semibold">{member.displayName}</p><p className="truncate text-sm text-muted-foreground">{member.email}</p></div><div><span className="text-xs font-bold uppercase text-muted-foreground md:hidden">Role · </span><span className="text-sm">{member.roleName}</span></div><Badge tone={member.status === "ACTIVE" ? "success" : "warning"}>{member.status}</Badge></div>)}</div>}</>;
}

export function RoleSettings() {
  const [roles, setRoles] = useState<Role[]>(); const [permissions, setPermissions] = useState<string[]>([]); const [selected, setSelected] = useState<string[]>([]); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const load = () => { Promise.all([settingsApi.roles(), settingsApi.permissions()]).then(([roleData, permissionData]) => { setRoles(roleData); setPermissions(permissionData); }).catch((cause) => setError(errorMessage(cause))); };
  useEffect(load, []);
  async function create(event: FormEvent) { event.preventDefault(); setPending(true); setError(""); try { await settingsApi.createRole(name, description, selected); setName(""); setDescription(""); setSelected([]); load(); } catch (cause) { setError(errorMessage(cause)); } finally { setPending(false); } }
  return <><Header eyebrow="Permission model" title="Roles" description="Roles are tenant-owned permission bundles. Application code authorizes permissions, never hard-coded role names." />{error && <Alert tone="error" className="mt-7">{error}</Alert>}<Card className="mt-8"><h2 className="text-lg font-bold">Create a role</h2><form onSubmit={create} className="mt-5 space-y-5"><div className="grid gap-4 md:grid-cols-2"><FormField label="Role name" htmlFor="role-name"><Input id="role-name" required maxLength={100} value={name} onChange={(event) => setName(event.target.value)} /></FormField><FormField label="Description" htmlFor="role-description"><Input id="role-description" maxLength={240} value={description} onChange={(event) => setDescription(event.target.value)} /></FormField></div><fieldset><legend className="text-sm font-semibold">Permissions</legend><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{permissions.map((permission) => <label key={permission} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-md border px-3 text-sm transition-colors hover:bg-muted"><input type="checkbox" className="size-4 accent-primary" checked={selected.includes(permission)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, permission] : current.filter((item) => item !== permission))} /><span className="break-all font-mono text-xs">{permission}</span></label>)}</div></fieldset><Button type="submit" disabled={pending}><Plus aria-hidden="true" />{pending ? "Creating…" : "Create role"}</Button></form></Card>{!roles ? <Pending /> : <div className="mt-5 grid gap-4 md:grid-cols-2">{roles.map((role) => <Card key={role.id} className={role.archivedAt ? "opacity-65" : ""}><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold">{role.name}</h2><p className="mt-1 text-sm text-muted-foreground">{role.description || "No description"}</p></div>{role.archivedAt && <Badge>Archived</Badge>}</div><div className="mt-5 flex flex-wrap gap-1.5">{role.permissions.length ? role.permissions.map((permission) => <Badge key={permission}>{permission}</Badge>) : <span className="text-sm text-muted-foreground">No permissions assigned</span>}</div></Card>)}</div>}</>;
}

export function AuditSettings() {
  const [entries, setEntries] = useState<AuditEntry[]>(); const [error, setError] = useState(""); const load = () => { settingsApi.audit().then(setEntries).catch((cause) => setError(errorMessage(cause))); }; useEffect(load, []);
  return <><Header eyebrow="Security evidence" title="Audit log" description="Append-oriented records show privileged and security-sensitive changes for this organization." />{error ? <ErrorState message={error} retry={load} /> : !entries ? <Pending /> : entries.length === 0 ? <Card className="mt-8"><h2 className="font-semibold">No audit events yet</h2><p className="mt-2 text-sm text-muted-foreground">Security and administrative activity will appear here.</p></Card> : <div className="mt-8 overflow-hidden rounded-xl border bg-card">{entries.map((entry) => <div key={entry.id} className="grid gap-2 border-b px-5 py-4 last:border-b-0 md:grid-cols-[1fr_11rem_12rem] md:items-center"><div><p className="font-mono text-sm font-semibold">{entry.action}</p><p className="mt-1 text-xs text-muted-foreground">{entry.entityType}{entry.entityId ? ` · ${entry.entityId}` : ""}</p></div><Badge>{entry.source}</Badge><time className="text-sm text-muted-foreground md:text-right" dateTime={entry.createdAt}>{new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(entry.createdAt))}</time></div>)}</div>}</>;
}
